### ISSUE TITLE
Support for other SQL Databases?

### ISSUE THREAD

**Issue by Staja** [neos-sdi/adfsmfa#103]
Support for other SQL databases (Eg: PostgreSQL, MySQL/MariaDB) would be useful, this would allow users to utilise NEOS-SDI ADFS MFA utilising [suggested best practice](https://github.com/neos-sdi/adfsmfa/wiki/06-Data-Storage) without the high cost of deploying MSSQL.

From what I've seen, other than the encrypted columns columns feature, I haven't seen any other feature that depends specifically on MSSQL's functionality over other SQL databases?

Is the SQL Database functionality completely encapsulated in [SQLDataRepositoryService](https://github.com/neos-sdi/adfsmfa/blob/master/Neos.IdentityServer%203.0/Neos.IdentityServer.MutltiFactor.Data/Neos.IdentityServer.MultiFactor.SQLServer.cs)? Would it be theoretically possible to create new classes that implement DataRepositoryService, IDataRepositorySQLConnection, IWebAuthNDataRepositoryService in order to support other database types?

**Comment by redhook62** [comment]
Hi @Staja 

Yes, The "SQL Server" runtime part is encapsulated in SQLDataRepositoryService, and relies entirely on the interfaces mentioned. 

It is possible to make an evolution to support the loading of a custom "database" pluggin . 
On the other hand the PowerShell cmdlets, and the administration console will not offer the database creation functionalities.

Remember, however, that ADFS itself requires SQL Server (express or full) and Active Directory. it is obviously evolutions on this side as well as the possibility of replacing / adding primary authentication modules which would be welcome.

Please wait a few days to be able to offer this functionality

Regards

**Comment by redhook62** [comment]
Hi @Staja 

Done in version 3.0.2006.0
You must develop your own solution. A sample is provided, and you can get inspired with the SQL-Server implemenation.
Documentation, will be updated soon.

Regards
