### ISSUE TITLE
Wordpress login

### ISSUE THREAD

**Issue by molsen6** [neos-sdi/adfsmfa#104]
Wordpress plugin https://github.com/onelogin/wordpress-saml works fine as normal saml login. 
When using TOTP provider it fails. It gives an server error at wordpress site. (Bad gateway.)

Any idea on this?

**Comment by redhook62** [comment]
Hi @molsen6 

Please verify that your plugin ignore all unknown Claims.
By default stanrdard MFA add some claims to prove that security has been well applied.

It's a server error, we have seen often these kind of errors when using SAML/SAML2 Java or PHP Frameworks.

Some samples

http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows

http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/kerberos

**http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/ws/2012/12/authmethod/otp**

**http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/claims/multipleauthn**

Regards

**Comment by molsen6** [comment]
Hi


Thanks for your answer.

Just for my understanding, I should look at the plugin, to get it to ignore unknown Claims?
I seems that there are no options in the current plugin, to ignore unknown Claims in the plugin.

Thanks
Michael



________________________________
Fra: redhook <notifications@github.com>
Sendt: 3. juni 2020 16:42
Til: neos-sdi/adfsmfa
Cc: Michael Olsen; Mention
Emne: Re: [neos-sdi/adfsmfa] Wordpress login (#104)


Hi @molsen6<https://github.com/molsen6>

Please verify that your plugin ignore all unknown Claims.
By default stanrdard MFA add some claims to prove that security has been well applied.

It's a server error, we have seen often these kind of errors when using SAML/SAML2 Java or PHP Frameworks.

Some samples

http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/windows

http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/ws/2008/06/identity/authenticationmethod/kerberos

http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/ws/2012/12/authmethod/otp

http://schemas.microsoft.com/claims/authnmethodsreferences -> http://schemas.microsoft.com/claims/multipleauthn

Regards

**Comment by redhook62** [comment]
Hi

Yes, of course you can look at the code of your PHP pluggin.
But don't you think it would be desirable to pose the problem to the authors ?

Regards

If you have some news, you can reopen this issue
