### ISSUE TITLE
Installation Error 2.0.2.966

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#11]
Hi,
We've started to test this ADFS MFA solution in our ADFS environment.
We downloaded the latest .msi, adfsmfa 2.0.2.966.msi, installed it and run:
Register-MFASystem -Activate -RestartFarm -Verbose

The MFA module seems to get registered and enabled (we can see it is added in ADFS under MFA Methods). But when the registration process is restarting the farm, we get the error: 
"Register-MFASystem : The specified network name is no longer available"

Also when we try to start the MFA mmc from the desktop icon, we get "The specified network name is no longer available".

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Hi,
Can you send us more complete informations.

The problem seems related to the internal messaging system (communication between servers), or related with the connection to ADDS or SQL. The system is using Mailsots to send notifications.

- Which version of windows server do you use ?
- How many ADFS Servers in your Farm ?
- Output of Get-MFAComputers and Get-MFAConfig
- Output of Get-MFAConfigADDS an Get-MFAConfigSQL

- Detailled errors related forom the EventLog

- Does the MMC launch correctly or crash ?

Please anonymize confidential parts.

Best Regards
redhook

**Comment by anorstrom** [comment]
Hi,
Thanks for replying. Here are some more information.

-We're on Windows Server 2016 (Farm upgraded from 2012 R2).

-We're in DEV right now, so only one ADFS and one WAP (we've had two ADFS Farms in the DEV domain, but the other Farm has been removed, so only one left now).

-PS C:\Windows\system32> Get-MFAComputers
FQDN                      : server01.domain.org
BehaviorLevel             : 3
HeartbeatTmeStamp         : 2/13/2018 5:11:00 AM
NodeType                  : PrimaryComputer
CurrentVersion            : 6.3
ProductName               : Windows Server 2016 Standard
InstallationType          : Server
CurrentBuild              : 14393
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
MachineName               : SERVER01

-PS C:\Windows\system32> Get-MFAConfigADDS
Account                  : 
DomainAddress            : 
KeyAttribute             : msDS-cloudExtensionAttribute10
MailAttribute            : msDS-cloudExtensionAttribute11
MethodAttribute          : msDS-cloudExtensionAttribute13
NotifCheckDateAttribute  : msDS-cloudExtensionAttribute16
NotifCreateDateAttribute : msDS-cloudExtensionAttribute14
NotifValidityAttribute   : msDS-cloudExtensionAttribute15
Password                 : 
PhoneAttribute           : msDS-cloudExtensionAttribute12
TOTPAttribute            : msDS-cloudExtensionAttribute17
TOTPEnabledAttribute     : msDS-cloudExtensionAttribute18

-Errors from Event Log:
Event ID 1026 - NET Runtime
Application: Neos.IdentityServer.MultiFactor.NotificationHub.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ComponentModel.Win32Exception
   at Neos.IdentityServer.MultiFactor.BaseMailSlotClient`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].WriteMailslot(System.__Canon)
   at Neos.IdentityServer.MultiFactor.MailSlotClientDispatcher.UnRegister(System.String, System.String, Int32, Boolean, Boolean, Boolean)
   at Neos.IdentityServer.MultiFactor.MailSlotServer.Dispose(Boolean)
   at Neos.IdentityServer.MultiFactor.BaseMailSlotServer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose()
   at Neos.IdentityServer.MultiFactor.MailSlotServerManager.Dispose(Boolean)
   at Neos.IdentityServer.MultiFactor.BaseMailSlotServer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Dispose()
   at Neos.IdentityServer.MultiFactor.MFANOTIFHUB.Dispose(Boolean)
   at System.ComponentModel.Component.Dispose()
   at System.ServiceProcess.ServiceBase.Run(System.ServiceProcess.ServiceBase[])
   at Neos.IdentityServer.MultiFactor.NotificationHub.Program.Main()

Event ID 1000 - Application Error
Faulting application name: Neos.IdentityServer.MultiFactor.NotificationHub.exe, version: 2.0.2.966, time stamp: 0x5a551b1f
Faulting module name: KERNELBASE.dll, version: 10.0.14393.1770, time stamp: 0x59bf2ba6
Exception code: 0xe0434352
Fault offset: 0x0000000000033c58
Faulting process id: 0xf1c
Faulting application start time: 0x01d3a4b1a0b0b14c
Faulting application path: C:\Program Files\MFA\Neos.IdentityServer.MultiFactor.NotificationHub.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 3704264d-519d-48d9-8efe-5d0b9a83741f
Faulting package full name: 
Faulting package-relative application ID: 

-The MMC crashes

Thanks,
Andreas

**Comment by redhook62** [comment]
Hi,

Ok, 
When we disable NetBios over tcp-ip. we run the same problem. 
Mailslots cannot be delivered in this case.

You must choose de Default option for netbios on tcp-ip stack.
At this time, it seems a prerequisite. It's required for Windows Mailslots.
Mailslots can broadcast small message on the lan or for specific machines (that's we do betwwen ADFS servers).

Let us know if the problem disappear.

Regards

redhook

**Comment by anorstrom** [comment]
Hi,
That solved the problem, it now registers nicely.
Thank you so much for your quick response!

Thank you,
Andreas
