### ISSUE TITLE
MFA-Configuration auxiliary class defined as 

### ISSUE THREAD

**Issue by zjorz** [neos-sdi/adfsmfa#110]
Hi,

I have analysed the AD schema extension for the MFA Adapter for ADFS and noticed that the MFA-Configuration auxiliary class definition is configured with systemFlags: 16

systemFlags: 16 means: When set, indicates the object is a category 1 object. A category 1 object is a class or attribute that is included in the base schema included with the system

Why is that done?

dn: CN=MFA-Configuration,CN=Schema,CN=Configuration,DC=X
changetype: ntdsSchemaAdd
adminDescription: MFA-Configuration
adminDisplayName: MFA-Configuration
defaultSecurityDescriptor: D:(A;;;;;DA)S:
governsID: 1.2.840.113556.1.8000.2554.43963.64993.29055.17455.46959.14109314.12081420
lDAPDisplayName: MFA-Configuration
name: MFA-Configuration
objectCategory: CN=Class-Schema,CN=Schema,CN=Configuration,DC=X
objectClass: classSchema
objectClassCategory: 3
**systemFlags: 16**
showInAdvancedViewOnly: TRUE
rDNAttID: cn
schemaIdGuid:: Pd68TF6uRXmql6LCWgtm0g==
subClassOf: top
possSuperiors: user
mayContain: MFA-TOTPKey
mayContain: MFA-TOTPEmail
mayContain: MFA-TOTPExternal
mayContain: MFA-SelectedMethod
mayContain: MFA-SpecificMethod
mayContain: MFA-PinCode
mayContain: MFA-WebAuthNCredential
mayContain: MFA-EnabledStatus
mayContain: MFA-ClientCertificate
mayContain: MFA-RSACertificate

**Comment by redhook62** [comment]
Hi @zjorz 

To be sure that all these attributes are well replicated if needed

Regards
