### ISSUE TITLE
Logos and Images not displaying, only broken icons

### ISSUE THREAD

**Issue by zjorz** [neos-sdi/adfsmfa#111]
When triggering MFA and using this MFA adapter on ADFS 2019, all images from the MFA adapter are not displaying. Instead an icon is shown as if the image is not available. Right clicking that icon and opening it in new tab does show the image/code.
What an I missing?
regards,
Jorge

**Comment by zjorz** [comment]
For another product I had configured security headers (Content-Security-Policy) in ADFS.
Running the following solved the issue: Set-AdfsResponseHeaders -RemoveHeaders "Content-Security-Policy"

**Comment by SkorpionMars** [comment]
Might be useful to someone, the problem with images not loading was missing **img-src 'self' data:;** in Content-Security-Policy
Get-AdfsResponseHeaders | Select -ExpandProperty ResponseHeaders

After executing the command Set-AdfsResponseHeaders -SetHeaderName "Content-Security-Policy" -SetHeaderValue "default-src 'self' 'unsafe-inline' 'unsafe-eval'; img-src 'self' data:;" everything worked. For some reason, when installing the MFA, this parameter was not added.

Before adding, I advise you to look at what you have here Get-AdfsResponseHeaders | Select -ExpandProperty ResponseHeaders are already there and add what you need to the end.
