### ISSUE TITLE
enroll after registration

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#113]
Hi,

I've noticed that often when user want to reconfigure mfa settings (access my options after authentication), after clicking on enroll authentication app or email address it redirect user to application not to mfa configuration.

Same situation is when user want to registrate mfa. Enroll process is interrupt and redirect to application or  start registration again.

Any ideas, what might be causing this?

Yesterday i was upgraded mfa provider to 3.0.2008.0 version, last registration tests i checked before upgrade and i think everything was ok. But now return to older version not help.

**Comment by redhook62** [comment]
Hi @Tryglav 

What you are describing is truly surprising.
We have not been able to reproduce the problem you submit.
Can you send us your configuration file (Export-MFASystemConfiguration (PowerShell)) and send it to us at the address indicated in the source codes.

Regards

**Comment by Tryglav** [comment]
Hi @redhook62 

Thank you for response. I'm probably blind, but i couldn't find any address in the source code. Where exactly i can find it?

Regards

**Comment by redhook62** [comment]
Adfsmfa@gmail.com

Regards

**Comment by Tryglav** [comment]
Thank You. I sent my mfa configuration.
Regards

**Comment by Tryglav** [comment]
Hi

My new observation. Situation appears on Chromium based web browsers. I've checked on Opera, new Edge, SRWare Iron. On FireFox i didn't noticed this situation.

Regards

**Comment by redhook62** [comment]
Hi, @Tryglav 

So I tested with your configuration, and with a few minor modifications (XORKey), I had no problems.

However, if I understood your problem correctly, you want to switch automatically to the English language. 
in fact, can you tell me what is your default language ? what is your client workstation language (because you do not want to use the languages defined by the browsers). are you in the languages supported by ADFS ?, by MFA?

I propose to restrict the translations to the only translations available in the component, with a fallback on the English language (why not French in the future ...)

Last point you still have some settings to make ...
You only have a secondary server indicated in your config, this does not seem to have impatcs, but be aware that the functionalities are restricted on a secondary server.

Regards

**Comment by Tryglav** [comment]
Hi, @redhook62

Yes exacly, i would like to mfa provider use only english language, no matter if user set different language on his browser as default.
My default language is polish, we are polish company but operate in other countrys.

So you think the problems might be caused by swaping all language resources? I've swaped only supported languages (de, es, fr, it, nl, pl, pt).

**Comment by Tryglav** [comment]
Hi, @redhook62 

I just confirmed. I've deleted all language resources from ResourceSet and problem doesn't appear again. But now service use my default browser languge (polish). I'll check if i didn't mixed up something with language resource files.
But is there a way to get the same effect by using native configuration of mfa provider, without swaping language resource files

Regards

**Comment by redhook62** [comment]
Hi **@Tryglav** 

OKAY,

Several points.

- **It is not possible for the component to change the language that ADFS will display for a user**, especially during the identification phase (Login), the component tries at best to follow the language indicated by ADFS.

- **It is not possible to deactivate ADFS's multi-language support**

- [Language support for ADFS](https://github.com/neos-sdi/adfsmfa/wiki/11-Localization#adfs-supported-lcid)

- [Language support for adfsmfa](https://github.com/neos-sdi/adfsmfa/wiki/11-Localization#builtin-languages)

- By default .net (asp.net) use the user session language (user's operating system language)

- With recent browsers it is possible to change the default language (with a modification of the UserLanguages property in the headers of the http request), but this is only possible in the MFA part (you must activate / deactivate the configuration property  **UseOfUserLanguages** in the general settings of MFA)

- When a language is not supported by ADFS or adfsmfa (see the indicated list), the language switches to English / American

What to consider

- Force MFA in a particular language, it is possible to implement in a future version this functionality !
```
But remember, that you will certainly have a language difference between the Login (Microsoft) and MFA (adfsmfa) part.
for example, the login in Portuguese and the mfa in English
```
- Simply, maybe you find that some translations are incorrect for some languages. we are fully aware of that.

- This project is open-source and we are working on it in addition to our usual work, it is not a product. Not having proven linguistic skills, we use Microsoft Azure Cognitive Services to provide a first basic version (Yes, AI and the rest ... remain a dream ...).
We therefore leave this task to the community, and we undertake to integrate their submissions (Pull Requests), and try to maintain them.

- Several contributors have provided us with translations of their mother language (Italian **@AlessandroMenti**, German **@klpo-mt**, English **@Ikke**), these languages are maintained by us and those of the contributors

You can watch here: https://github.com/neos-sdi/adfsmfa/wiki/11-Localization

If you really want to force the MFA part in a specific language, please let us know, we will do it in a future release.

Regards

**Comment by Tryglav** [comment]
@redhook62 

Thank You for explenation.  My concerns was especialy for polish translation, polish language is quite strange (many forms, gramatic etc.). I've even try to correct translation by myself, but many same phrase are used in different steps of registration, but in polish languge forms often change and phrase used in the previous step on next one lose context.

So best solution for me was change polish translation to english.

**Comment by redhook62** [comment]
Hi @Tryglav 

We will do the necessary for the procaine version to force a language like EN-US.
In the meantime you can delete the resource assemblies in the GAC for the languages you do not want to have.

![image](https://user-images.githubusercontent.com/26826945/90782883-acb06280-e2ff-11ea-955d-98358c1b6c2c.png)

Regards

**Comment by redhook62** [comment]
Done
