### ISSUE TITLE
"Access my options after authentication" for biometrics doesn't seem to work

### ISSUE THREAD

**Issue by gtbuchanan** [neos-sdi/adfsmfa#115]
If biometrics is set as my primary authentication provider and I click "Cancel" during the first attempt, the "Access my options after authentication" option doesn't seem to work.

![Annotation 2020-08-25 132325](https://user-images.githubusercontent.com/715687/91212917-7fd0c680-e6d6-11ea-9af9-01d7fe535bcb.png)

![Annotation 2020-08-25 132655](https://user-images.githubusercontent.com/715687/91213094-b9a1cd00-e6d6-11ea-9f99-52d9efcc206a.png)

At this point, if I click "Sign In" and use my security key, I am directly logged in and not taken to the options page. This forces me to click "I do not have the code" and use another authentication method if I want to change my options (for instance, add a backup security key).

**Comment by redhook62** [comment]
Hi @gtbuchanan 

We use this procedure quite regularly, and it seems to work without problems.
What system and what browser do you use?

Regards

**Comment by redhook62** [comment]
When you switch the primary authentication mode to the adfsmfa component 
you must run this command. 

Set-MFAPrimaryAuthenticationStatus (adfsmfa must be removed from second factors)

all the connected authentication modes are then disabled for security reasons (Email, Phone, Azure MFA)

Regards

**Comment by gtbuchanan** [comment]
@redhook62 The issue only seems to occur with biometrics. If I select the option while on another authentication method (for instance, after selecting "I do not have the code"), it works fine. ADFS is on Windows Server 2019 and I've tried the option in the latest Firefox and Chrome. I have run `Set-MFAPrimaryAuthenticationStatus $true`.

**Comment by redhook62** [comment]
Hi **@gtbuchanan** 

We cannot reproduce your problem.
Everything work as well, In "standard mode (MFA)" or as "Primary Authentication".

We will ship a new build today, Can you test again with this upcoming new version

Regards

**Comment by redhook62** [comment]
Hi **@gtbuchanan** 

Done in version 3.0.2008.4 (8/27/20)

Regards

**Comment by gtbuchanan** [comment]
@redhook62 Just confirmed the issue is resolved. Thank you!
