### ISSUE TITLE
"Remember my selection" option should not be selected by default when choosing a secondary method

### ISSUE THREAD

**Issue by gtbuchanan** [neos-sdi/adfsmfa#116]
If biometrics is set as my primary authentication method and I click "Cancel" during the first attempt in order to choose a secondary method (for example, I don't have my security key available), there is the possibility I may accidentally set a secondary method as my primary because "Remember my selection" is enabled by default.

![Annotation 2020-08-25 133906](https://user-images.githubusercontent.com/715687/91214485-c3c4cb00-e6d8-11ea-8a42-c0e19f28ce22.png)
![Annotation 2020-08-25 133654](https://user-images.githubusercontent.com/715687/91214488-c4f5f800-e6d8-11ea-8857-9207e2b03c15.png)

I propose this option be unselected by default so the user is less likely to accidentally set a secondary method (like email) as primary.

**Comment by redhook62** [comment]
Hi **@gtbuchanan** 

Yes, it was the default behavior until version 2.2, 
At this time we were asked to enable it by default.

What is the best solution?

Let's consider a setting to handle this dilemma, maybe in a future release...

Regards

**Comment by gtbuchanan** [comment]
Interesting. I can't think of why someone would want this enabled by default unless it was during an initial configuration where the user doesn't have a default already. If that's the case, then I agree it would be good as a setting.

**Comment by redhook62** [comment]
Yes, in fact it doesn't really matter, we will disable it by default, as before
