### ISSUE TITLE
is there a chance to customise the emails

### ISSUE THREAD

**Issue by ImenTurki** [neos-sdi/adfsmfa#118]
can any one knows how to customise the sended email? Add / remove  AD information , customise the theme ( add html content ), any idea ?

**Comment by redhook62** [comment]
Hi, @ImenTurki 

To customiez emails see : [Customizing email templates](https://github.com/neos-sdi/adfsmfa/wiki/08C-MFA%20Email%20Provider#replacing-default-emails-templates)

To add / remove AD information : please be more precise, we don't anderstand your needs

To customize Themes : 
- Not possible at this time, you must modify our project and recompile it.
- For security reasons, adfs only allows very few things at the theme level. All the html, media or other elements must come from 
  its database under the url /ADFS/Portal in which case these resources are not considered safe.
- This is something that has been reflected for a long time without being a priority, 
  If you wish we can add a feature allowing you to change the UI. 
  This will be done by providing an assembly containing an inherited type, which will need to be registered in the MFA 
  configuration.
  We will not allow the possibility of putting html, js and others directly into the solution. I repeat, it is a choice related to security.

Regards

**Comment by ImenTurki** [comment]
Hi @redhook62 

Thank you very much for your answer ,
what i meant by AD info is to show more user details in the mail text, like departementl or manager and other things.
I  like also to add signature with picture in the mail .

I see that  using the "Customizing email templates" i would be able to update text add some css , but i need also to add the user email , wich is not offered in the "Secure Key Mail" because it has only those one: 

    {0} Company (string)

    {1} User Name (string)

    {2} Security Key (string)

    {3} QR Code (graphic) // Something like that in your HTML file

so to recompile the project is the best solution for me to customise the email text ,  when i try to build the solution unfortunally i always get this error : 

`Error		Unable to get MD5 checksum for the key file "Neos.IdentityServer.pfx". Could not find file 'E:\Tasks\DEV\OTP\adfsmfa-3.0\adfsmfa-3.0\Neos.IdentityServer 3.0\Neos.IdentityServer.MutltiFactor.Data\Neos.IdentityServer.pfx'.	Neos.IdentityServer.MultiFactor.Data	
`		
and it's for all pfx file , any idea to do that ?
regards ,
imen

**Comment by redhook62** [comment]
Hi @ImenTurki 

What it is possible to do in this mail template is simply to add a 5th parameter for the email address in next build.
For the other attributes, we are not using them and do not plan to do so. 
We only use a small set of attributes for MFA purposes.

To recompile the project, you must use your own .pfx certificate. 
We never pass on the signing key of our source codes !
This solution is deployed in a large number of companies or international organizations.
This is always linked to security issues.

Let us know if it's ok for you (5th parameters) ?
Regards

redhook

**Comment by redhook62** [comment]
Hi **@ImenTurki**

You can now, use the tag {4} for the user's mail address.
If you are building your own solution, assign a pfx certificate to each project.
Search the souce code for **[assembly: InternalsVisibleTo("xxxx)**, follow the instructions 

Regards

**Comment by ImenTurki** [comment]
Hi 

> 
> 
> Hi **@ImenTurki**
> 
> You can now, use the tag {4} for the user's mail address.
> If you are building your own solution, assign a pfx certificate to each project.
> Search the souce code for **[assembly: InternalsVisibleTo("xxxx)**, follow the instructions
> 
> Regards

Hi  @redhook62 ,

I customised the html Files for the EN and FR using the new version and tried to make the update using this code : 

`$mail = Get-MFAProvider -ProviderType Email
	
	$mail.MailOTP.RemoveTemplate(1033)
	$mail.MailOTP.AddTemplate(6, "C:\OTP-MFA\1033\MailOTPContent.html", $True)
	
	$mail.MailInscription.RemoveTemplate(1033)	
	$mail.MailInscription.AddTemplate(6, "C:\OTP-MFA\1033\MailAdminContent.html", $True)
	
	$mail.MailSecureKey.RemoveTemplate(6)
	$mail.MailSecureKey.AddTemplate(6, "C:\OTP-MFA\1033\MailKeyContent.html", $True)
	
	$mail.MailNotifications.RemoveTemplate(1033)
	$mail.MailNotifications.AddTemplate(1033, "C:\OTP-MFA\1033\MailNotifications.html", $True)
	
	$mail.MailOTP.RemoveTemplate(1036)
	$mail.MailOTP.AddTemplate(1036, "C:\OTP-MFA\1036\MailOTPContent.html", $True) 
	
	$mail.MailInscription.RemoveTemplate(1036)
	$mail.MailInscription.AddTemplate(1036, "C:\OTP-MFA\1036\MailAdminContent.html", $True)
	
	$mail.MailSecureKey.RemoveTemplate(1036)
	$mail.MailSecureKey.AddTemplate(1036, "C:\OTP-MFA\1036\MailKeyContent.html", $True)
	
	$mail.MailNotifications.RemoveTemplate(1036)
	$mail.MailNotifications.AddTemplate(1036, "C:\OTP-MFA\1036\MailNotifications.html", $True)	
	
	Set-MFAProvider -ProviderType Email $mail`

unfortunately it did not get the new updates.
Any idea please !

**Comment by redhook62** [comment]
Hi,

Why do you set the Lcid 6 ? it's for danish !

Regards

**Comment by ImenTurki** [comment]
sorry ! 
 i update the comment !

**Comment by redhook62** [comment]
Hi,

You must ensure that the Adfs Account have read access to the folders ans sub-folders of C:\OTP-MFA\

You can also use these Cmdlets
Export-MFAMailTemplates -LCID 1033
Export-MFAMailTemplates -LCID 1036

And replace all needed files in C:\ProgramFiles\MFA\MailTemplates\...\

You can also, but not needed, depending of your platform configuration restart mfanotifhub service

Regards
