### ISSUE TITLE
trusted device

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#119]
Hello

Do you planning in future varsions of adfsmfa module implement trusted device functionality?

Gaving user posibility to remember device they authenticated from and exclude this device from second factor authentication.

My company is interested with this option and we are curious if this could possible?

**Comment by redhook62** [comment]
Hi, @Tryglav 

`Do you planning in future varsions of adfsmfa module implement trusted device functionality ?`
Yes, that could be interesting. have any ideas on that ?

`Gaving user posibility to remember device they authenticated from and exclude this device from second factor authentication.`
Currently the user can manage his devices by managing his options, or by administration in the console.
Maybe more information is needed to help the user with this task. WebAuthN is "relatively" secure, but in addition to what is currently available only a description of the device (subject to the security options offered, with "None" this will not be available

`My company is interested with this option and we are curious if this could possible ?`
Do you have any enlightened proposals for me ?

Interesting discussion to come

Regards

**Comment by Tryglav** [comment]
Hi, @redhook62  

Thank you for response. Let give me a few days, i will debate with my team how we see it and how this could work. 
On monday i should give some propositions.

Best regards,
Tryglav

**Comment by Tryglav** [comment]
Hi, @redhook62 

Sorry for long response. 

Short description how we see it.

1. Definitly will be needed a data base of remembered devices. We think that could be a dedicated Active Directory attribute on user class. This will make that the device will be assigned to a specific user.
2. On MFA logon screen should be added checkbox “Remember device”, “Trust device” etc. When user select checkbox, device ID should be saved in database and assigned to user.
3. User should have possibility to revoke or delete device by himself. We think that on “Access my options after authentication” could be a new option ‘trusted device’ where remembered devices are listed.
4. Administrator should have possibility to revoke all device assigned to all users. We think that in user properties on administration user management console, could be a new tab with remembered devices by user. 
5. On administration console could be global option where administrator could define limit of remembered device by users.
6. Global policy when user identify with trusted device, skip second factor authentication and direct to application.
7. On administration console could be an option to clear device that have not been used for a long time. Administrator could define this time.

How @redhook62  do you see it? Is it technically possible?


Best regards,
Tryglav

**Comment by redhook62** [comment]
Hi **@Tryglav** 

First of all, thank you for your feedback.

I will put my remarks on the various points raised, and then give you my opinion on future developments.

However, at first glance, it is a question of certifying the devices. it is quite possible to achieve this today with an **MDM** like **Microsoft Intune in Azure**, or other solutions
This avoids entering passwords or other passwords as a primary identification.
ADFS allows devices to be filtered in its access control strategies (Authenticated, Managed, Compliant)

With Microsoft Intune, device certificates are synchronized on your ADDS via ADConnect, we use it in our company. however the management is carried out "OnLine" and not "OnPremise". it is up to you to see the trust you bring to your supplier, the MFA in this case can be a guarantee ...

Creating an MDM has been one of the projects we've had in mind for some time for GitHub.
After that, it's a question of time and funding.
Written in .Net Core ... running on multiple platforms and integrated into the management console. 
Beautiful perspectives in sight...

`Definitly will be needed a data base of remembered devices. We think that could be a dedicated Active Directory attribute on user class. This will make that the device will be assigned to a specific user.`
- Yes, it make sense ! but not in ADFSMFA (dedicated to MFA)

`On MFA logon screen should be added checkbox “Remember device”, “Trust device” etc. When user select checkbox, device ID should be saved in database and assigned to user.`
- Yes, it make sense, But this is specific to biometric authentication! the MFA component has no access to information about peripherals, only a PublicKeyDescriptor in the case of WebAuthN, and nothing for all other providers. 
Device management must be global and not specific to a particular MFA mode.

`User should have possibility to revoke or delete device by himself. We think that on “Access my options after authentication” could be a new option ‘trusted device’ where remembered devices are listed.`
- Yes, that would be cool.

`Administrator should have possibility to revoke all device assigned to all users. We think that in user properties on administration user management console, could be a new tab with remembered devices by user.`
- Yes, with a management console

`On administration console could be global option where administrator could define limit of remembered device by users.`
- Yes of course

`Global policy when user identify with trusted device, skip second factor authentication and direct to application.`
- Yes, this is already the case when you use an MDM, it is managed in the ADFS access policies. "No MFA for devices (Authenticated, Managed, Compliant)"

`On administration console could be an option to clear device that have not been used for a long time. Administrator could define this time.`
- Yes of course

It is therefore possible to implement at least a certain number of things in MFA, but this will be limited to WebAuthN authentication and its specificities.

Today, the MFA component is at a certain level of maturity, and we spend a lot of time on details (justified ! ).
Remember, on security, IT departments decide and users dispose ...

For information the degree of reliability that I evaluate for the different modes of MFA (score out of 10)
- 10 TOTP code with authenticator application
- 9 to 6 WebAuthN, depending of the security settings choosed.
- 6 to 4 Mail notifications
- 4 to 0 Phone notifications (https://www.youtube.com/watch?v=Z9kO4VmN1FM&feature)

Here are our lines of reflection at the moment

Thank you for your feedback

Regards

redhook
