### ISSUE TITLE
Generate new key with PS

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#12]
Hi,
We are testing and are using the latest 2.0.2.966.
We tried to the reset/generate new keys for users.

It works well when we do it from the MMC GUI, User Management - User - Key Tab - New Key. But it does not seem to work from PowerShell, or we do something wrong. We tried this:
set-MFAUsers -Identity user@domain.com -ResetKey

Should that be the same as running New Key from the GUI? We get no error, but nothing happens to the key, and the current key is still valid. We've tried it with both RNG and RSA.

A question on this topic too. If we run RSA, is there any other way for us to generate (with code) the encrypted string and put it directly into the attribute in Active Directory (without using the MFA PS cmdlets)?

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Hi,

Yes, the flag for reseting the UserKey is not passed when using PowerShell. It works with the MMC.
We're going to provide quickly a patch

Regards

**Comment by redhook62** [comment]
Hi,

New version 2.0.2.967

Regards
