### ISSUE TITLE
Remove or increase maximum length for PIN

### ISSUE THREAD

**Issue by gtbuchanan** [neos-sdi/adfsmfa#121]
I don't see a particular reason to limit the PIN to 4 digits. While I think the minimum/maximum PIN length should ultimately be configurable, it would be a good first step to improving security for "passwordless" setups to remove or increase the maximum length for a PIN. For example, [YubiKeys permit a PIN up to 256 bytes long](https://developers.yubico.com/WebAuthn/WebAuthn_Developer_Guide/FAQ.html).

**Comment by redhook62** [comment]
Hi, **@gtbuchanan** 

Now Pin can have between 4 and 9 digits.
You can change the default behavior with PowerShell

```powershell
$c = Get-MFASecurity
$c.Pinlength = 8
$c.DefaultPin = 12345678
Set-MFASecurity $c
```
See version 3.0.2009.3

Regards

**Comment by gtbuchanan** [comment]
Perfect. Thank you!
