### ISSUE TITLE
biometric + windows

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#123]
Hi,

Yesterday i configured an biometrics authentication. 
Everythings work fine on smartphones. But on Windows10 when i want register my biometric device,  default is called an usb security key.

Have you been through such a case? How can i force system to using an fingerprint reader as default.
Lptop on which i'm testin support the fingerprint reader and i can set fingerprint as windows hello authentication method.

<img width="342" alt="Capture" src="https://user-images.githubusercontent.com/63842532/95187766-cf250f00-07cb-11eb-8193-c2001e0b0b31.PNG">

Best regards,
Tryglav

**Comment by redhook62** [comment]
Hi **@Tryglav** 

If you are using a security key with Windows Hello, yes you must follow the process and install the security key (your screen shot)

What kind of security key are you using ?

On my personal PC, i have 1 biometric camera (Logitech Brio), 2 fingerprint sensors (Integrated an Kensington), 1 security Key (Yubikey Security Key NFC)
All are working as well. and with andoid Phone also (NFC) or integrated FingerPrint.

If you are using a Yubikey Security Key, you have only to install for windows, the minidriver and Yubikey Manager.

Lets us know !

Regards

**Comment by Tryglav** [comment]
Hi @redhook62 

Point is im not using an security key at all. That's why it's seemed strange to me. 
So i understand it's not an usual situation, you have not  seen a similar case before?
I wonder if any windows policy configuration can have an impact here?

Best regards,
Tryglav

**Comment by redhook62** [comment]
Hi **@Tryglav** 

As i said before, i have no problem to use a Security Key or a fingerprint device.

<img width="342" alt="hello1" src="https://user-images.githubusercontent.com/26826945/95198766-0996a800-07dc-11eb-9814-d529db436545.png">

So, I think, you have only to choose the best option !

Regards

redhook

**Comment by Tryglav** [comment]
Hi @redhook62 

Thank you for seponse and for screen. Now at least i know how it shoult looks like. 

In my case, it does not list the available windows hello authentication methods at all. When I click through this screen and proceed, it commands the security key. I thoughd it's somewhere in Windows configuration, but reaction on laptop with unix was simmilar. Not listing available authentication methods but immediatly comands a sekurity key.  

Regards
Tryglav

**Comment by redhook62** [comment]
Hi,

Have you a TPM activated on your laptop ?
In this case it shoulf take precedence.. try to disable it or try to find how to configure it for WebAuthN anf Windows Hello

Regards
