### ISSUE TITLE
Support for AlwaysON VPN On-prem

### ISSUE THREAD

**Issue by MDaugaardDK** [neos-sdi/adfsmfa#124]
Hello

Is it possible to use ADFSMFA with On-premises AlwaysON VPN Solution?

**Comment by redhook62** [comment]
Hi **@MDaugaardDK** 

I think you ask your administrator to activate MFA for intranet (for You or everyone). 
In the ADFS Console / Acces Control Stategies. Not in the ADFSMFA

Regards
