### ISSUE TITLE
mfa users management

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#126]
Hello,

1. Is there a way to delegate mfa users management functionality for operator without adding a new server to ADFS farm?

2. I've noticed that when we deactivate user on users management console it would disappear from list. It's not a problem, we can import user back from AD, but for that you have to enter full distinguishedname. Is it a bug? It would be better if account stay on a list with unmarked enable status.
 
Regards,
Tryglav

**Comment by redhook62** [comment]
Hi,

Yes, in the first place, there's no need to add a server ...
this is not managed in the MFA component, 
but in ADFS in the delegation part of the administration of services.

![image](https://user-images.githubusercontent.com/26826945/96137414-ea46fb80-0efc-11eb-8939-bb3e3a75a1ce.png)

2 - By default, deactivated users are filtered and do not appear in the console list. you just need to clear the filter. and it is enough to reactivate the inactive user (and to modify the few properties)

Regards
