### ISSUE TITLE
Unable to have adfsmfa AND hello for business hybrid certificate trust enrollments working at same time

### ISSUE THREAD

**Issue by SeSeKenny** [neos-sdi/adfsmfa#127]
Background,
[https://docs.microsoft.com/en-us/windows/security/identity-protection/hello-for-business/hello-hybrid-cert-trust](url)
Using a SQL backend with fully working adfsmfa deployment, new user hello for business cert enrollments fail, I suspect cert renewals will fail as well through the enrollment agent.

On the client all events look happy, except a single 324 event under Microsoft-Windows-User Device Registration/Admin
```
Unable to get a token using the Web Account Manager. Error: Unknown HResult Error code: 0xcaa7000a 
Request status code: 5 (WebTokenRequestStatus_ProviderError) 
Token provider error code: 0xCAA7000A 
Token provider error message: The Internet connection has timed out. 
CorrelationId: {8DA1F3DC-726E-43F2-A14E-8085DFB4755A}
```
On the server all events look happy, except a single 1021 under AD FS/Admin that I get even when enrollment works.
```
Encountered error during OAuth token request. 

Additional Data 

Exception details: 
Microsoft.IdentityServer.Web.Protocols.OAuth.Exceptions.OAuthJWTBearerException: MSIS9421: Received invalid OAuth JWT Bearer request. The JWT Bearer request to get Primary Refresh Token must contain 'aza' scope.
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.ValidateJWTBearer()
   at Microsoft.IdentityServer.Web.Protocols.OAuth.OAuthToken.OAuthJWTBearerRequestContext.ValidateCore()
```

If I disable adfsmfa with `Disable-MFASystem` then clear out hello on a system thats partially enrolled (save the cert from our PKI) with
```
$path = "C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\Ngc"
takeown /f $path /r /D y
Remove-Item -Force -Recurse -Path "$path\*" -erroraction 'silentlycontinue'
```
And login and enroll in hello, I get a full cert trust hfb setup. 
Any ideas? it seems there was a lot of work on Hello For Business support in the latest release, but more so on the 'as an authenticator/factor' side.

**Comment by redhook62** [comment]
Hi **@SeSeKenny **

I do not understand everything about what you indicate. however, 
It seems that everything is working fine when using the SQL configuration ?

For the ADDS configuration, it's essential not to use the 2016 template in ADDS Config in your case, 
Indeed, this configuration uses an attribute (with multiple values) which is used by Microsoft for WHFB. 
The name of the attribute is: **msDS-KeyCredentialLink**. 

In this case, find another multivalued attribute such as **otherMailbox** or deploy the specific schema extension we provide.

Look at the different options in the ADDS configuration.

Regards

redhook

**Comment by redhook62** [comment]
Let us know

Regards

**Comment by SeSeKenny** [comment]
Yeah I think this issue is being misunderstood, its not registering hello as a factor against adfsmfa, but enrolling hello on a device for windows logon that fails when adfsmfa is enabled. There are 5 different enrolment types for hello, two of which would be broken (both relating to cert trust). Basically ADFS gets used as a certificate registration authority in either of these models. Its that particular authentication that's broken.

**Comment by redhook62** [comment]
Hi @SeSeKenny 

I do not understand exactly why when you disable the MFA WHFB works !
Nothing is loaded until the second factor is requested.

In addition, the extension runs in a particular area imposed by Microsoft, unlike their own MFA extension ...

Except for touching the indicated attribute, technically there can be no impact. 

I can't help you anymore, for lack of information and especially I think it is a problem of WHFB.
Do you really need MFA with WHFB ?

regards

redhook
