### ISSUE TITLE
biometric register

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#128]
Hello

One of my user has problem with register his windows 10 with biometrics, and i cant't figure out why. Appliecation event return somthing like this.
![Capture50](https://user-images.githubusercontent.com/63842532/97715098-447dba00-1ac2-11eb-8cbe-7fc035f20404.PNG)

User has configure windows hello (fingerprint, pin) it's work when he login to the system, but when he try register fingerprint with mfa, application return 'your account is not validated!' 
Do you know what this event could mean?

Regards
Tryglav

**Comment by redhook62** [comment]
Hi @Tryglav 

please download and install the latest version 3.2010.1 https://github.com/neos-sdi/adfsmfa/releases
the problem is fxed since one month.

Regards
