### ISSUE TITLE
biometrics and iphone

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#129]
Hello,

I have a question. How mfa biometric provider hangs out with iPhones and Android smartphones which using only faceapp as a biometric?
Because last week i was doing some test on these deviaces and i couldn't register, mfa doesn't recognize biometric modules on it.

Regards
Tryglav

**Comment by redhook62** [comment]
Hi @Tryglav 

For Iphones, the support is in preview, you link it in the releases, Apple did not hurry, and requested an update of CTAP in 2.1 ...

For biometrics and facial recognition, you need a special camera with infrared. The rest can't work, so facial recognition on Android, you can forget, and for apple you will probably need FaceID.
For example, the logitech Brio webcam on PC works wonderfully.

Regards
