### ISSUE TITLE
Feature Suggestion - Managed Enrollment of Authenticator App

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#13]
Hi,
We are testing and are using the latest 2.0.2.967.
We have a desired scenario that kind of works now, but it would have been nice to extend this feature a little bit.

### Desired scenario - Configuration
MFA Status: Must be in the mode “Mandatory – MFA cannot be disabled”
User Registration: Should be in the mode “Administrative - Registration made by the support” 
Options Management: Would be nice with a new option here, **Enroll Authenticator App**. This option would add a link on the OTP page. Clicking the link take you to a page where you are first prompted to enter OTP code (gets it from email or SMS), and then guides you through the Authenticator App Enrollment with the QR code. Something like this:

![neosconf](https://user-images.githubusercontent.com/23246525/36549121-4824e118-17f2-11e8-856d-84ddaad45bc9.PNG)

![neosforms](https://user-images.githubusercontent.com/23246525/36549137-4dbfaaea-17f2-11e8-8152-eab46cdfc28c.PNG)

### Desired scenario - Process
- The support registers the MFA User and adds telephone number or email address. 
- The user arrives at the OTP page, click the “Enroll Authenticator App” link.
- The user is prompted for OTP code and chooses where to send the OTP (email or SMS, or only the one that is enabled). After entering the OTP, clicking Next.
- Next page is the QR code with an explanation on how to configure your Authenticator App. User scans, click OK and are then taken back to the first OTP page where he types an OTP code from the Authenticator App and click Sign In.

We’re doing kind of this now in our testing by enabling, under Options Management, “User Management Options”, and then in the ADFS onload.js hide/change certain things on the pages. But it does not look so nice since that gives you some extra pages that are not necessary. And the process is a bit confusing for the user.

What do you think, would it be something you would like to add?

Thank you for your nice work on this!

Andreas

**Comment by redhook62** [comment]
Hi

Thank you for this return.

We will not be able to make this type of change quickly, we are very busy. on the other hand, version 2.2 will be available soon.

We will not make any more changes on version 2.0, except for blocking bugs.

We will take inspiration from your proposall, for the management of QRcode (especially in administrative mode) in version 2.2, 

Normally as soon as the QRcode is displayed, the key must be changed for privacy reasons. We will implement this, as we have been asked before.

It will also have to be suitable for biometric recording (fingerprint or face) that we plan for next 2.5 version.

Regards

**Comment by anorstrom** [comment]
Thank you for your response.
Looking forward to that.

**Comment by Ikke** [comment]
Thanks for your work on this!

Any update on when the beta will be released?

Kevin.

**Comment by redhook62** [comment]
Hi All,

Sorry, i was in holidays.

**Version 2.2**
The UI is now fixed. 
But we are in late with MMC and PowerShell modules. 
Without this, it should be difficult to use new features.

Update on some planned features

- The model for MFA providers completely redesigned to support more scenarios as well as better customization possibilities in the extensions that you have / will develop

- Additional verification support with PIN codes

- Wizards for registration and validation on each MFA provider, activatable at each MFA provider

- Data encryption in SQL mode, if you use the SQL Server 2016 "Always Encrypted" feature (more compliance with RGPD)

- More features to register / register users to the MFA, especially when using an administrative configuration

- Multi domain and multi forest support when using Active Directory mode

- The support for the new model for Azure MFA (well, if you use this component, it's probably that you do not trust Microsoft, I'll talk about this new model in detail and that will surely comfort you your choices ...)

- Perhaps, German translation ressources

- And more...

**Linked to the workload we have in talking about it, the beta is postponed until the end of June**

**Comment by anorstrom** [comment]
Eager to test the new version ;)
Do you have any update on when you can make the beta available? 

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Hi

I think that the new version 2.2 early beta will be available at the beginning of the next week (Monday or Tuesday with basic documentation)

Regards

**Comment by kalsure** [comment]
Hi,

I have installed adfsmfa.3.1.2112.0.msi package and configured MFA. It is working for users who are activated with Email and Google app.
We are enabling MFA on email office 365? At first time login office365 it asking code and code already into the email.
Due to this option, the user is unable to log in. even we are sending a Security key for Google App on the same email. How users can activate apps.
Is there any option user can register self its own? After login ADFS password and one time default/generate code for only one session The next page is the QR code with an explanation on how to configure your Authenticator App. User scans, click OK and is then taken back to the first OTP page where he types an OTP code from the Authenticator App and clicks Sign In and logged into office365.

Thank you in advance.

**Comment by redhook62** [comment]
Hi,

In this case, you should not use an email subject to the MFA ... Let your users use a personal address.
You can also manage which domains are authorized or blaklisted.

If you want users to register a TOTP code and an Email. Check at provider level that the "required" option is active

**Comment by kalsure** [comment]
Hi,
Thank you for your comment.
We can not use any personal email address here.

Can we generate a one-time standard code for one session only for all MFA users ?

Not sure why I can not see "Enroll Authenticator App" in Options Management. Even I am using the latest one package.

One more, Can we get a report or some audit on which users registered MFA using QR code/Secretkey on google apps on their mobile devices?

Thank you again.
