### ISSUE TITLE
Cannot send mail using Powershell command

### ISSUE THREAD

**Issue by xymsayly** [neos-sdi/adfsmfa#132]
OS：Windows  server 2019
adfsmfa version: 2.4.0
Used Command: Import-MFAUsersADDS -LDAPPath $distinguished_name -Method Code -NewKey -SendEmail -Confirm:$false

I was able to use this command to successfully import AD users and generate new keys, but the mail was not successfully sent, and when I clicked the Send Mail button in the adfsmfa console, it worked fine.
Do you have any good suggestions? Thank you.

The results returned by the powershell command：
Import Users Starting 2020/11/20 3:57:47
Import Users Finished 2020/11/20 3:57:47 Users Imported : 1 Errors 0

**Comment by redhook62** [comment]
Hi **@xymsayly** 

Yes, it was a bug. It seems that never be implemented before...
You can download the latest build 3.0.2011.3.

As you are in version 2.4 you will have to follow the different migration steps, in particular https://github.com/neos-sdi/adfsmfa/wiki/03-UpgradeFromPrevious.

If you have any concerns, do not hesitate to contact me

regards
