### ISSUE TITLE
mail code sending

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#133]
Hi
I've noticed two things at a newest version: 
1. There is a much deley of sending email with code. On previous version i think it was ok, so i'm curious is something change, or is it my mail server? Do you noticed something simillar on your lab enviroment?
2. When you chose biometric there is no timeout after some time of inactivity. Something change with that?

On Android mfa used earlier pattern or pin cod (unlock system) as a biometric? 

Regards,
Tryglav

**Comment by redhook62** [comment]
Hi @Tryglav 

No, nothing has changed for the email provider
For biometric privider the timeout works as well, and nothing has changed. If you are using FireFox there's some issues with this.
https://bugzilla.mozilla.org/show_bug.cgi?id=1605817 and more
Please test with online applications like www.passwordles.com

Regards
