### ISSUE TITLE
UI breaks and CSS emptied  when you do set-AdfsRelyingPartyWebTheme -Logo

### ISSUE THREAD

**Issue by hareeqi** [neos-sdi/adfsmfa#135]
Hello 

We noticed whenever we run the command "set-AdfsRelyingPartyWebTheme" and only give it RP name and logo, it removes the CSS in the following function in when i inspected the page source 

```

function RemoveADFSHtmlHeader()
{
   var title = document.getElementById('mfaGreetingDescription');
   if (title)
   {
      title.style.display = "none";
   }
   SetIllustrationImage("");
   document.getElementById('companyLogo').src = "/adfs/portal/logo/logo.png?id=2159E08337BE5B92300FF0AECEFEDFDB1AACBE69B51591141E5C71B010444594&rp=b51544ff-0e49-eb11-a086-005056b3b676";
   document.getElementsByTagName('link')[0].href = "";
   return true;
}
```

primarily the issue in 

```
document.getElementsByTagName('link')[0].href = "";
```

which can be traced in the file

```
Neos.IdentityServer.MultiFactor.BasePresentation.cs
```

The command we excuted in ADFS is 

```
set-AdfsRelyingPartyWebTheme -TargetRelyingPartyName "bill" -Logo @{path="C:\themes\logo.png"}
```

**Comment by redhook62** [comment]
**@hareeqi** 

Thank you !

New Release 3.0.2101.0 

Don't forget if necessary to launch ** Reset-MFAThemesList**

**Comment by hareeqi** [comment]
wow that was amazingly fast, thank you so much, tremendous effort and happy new year :)
