### ISSUE TITLE
Add or remove biometric devices error

### ISSUE THREAD

**Issue by kouh123** [neos-sdi/adfsmfa#137]
Hi  @redhook62 

I'm testing biometrics.
But it doesn't work with version adfsmfa.3.0.2012.0.msi or later.
Confirmed to work with version adfsmfa.3.0.2010.1.msi.

detail
Biometric device cannot be added or changed.
Registered biometric devices can be used for authentication.

If you continue to add or change biometrics, the browser will display the following error:
 The specified key did not exist in the directory.
 (Google Translate of Japanese into English)

What should I check?
![add-biometrics-error](https://user-images.githubusercontent.com/73370933/103611488-bf9d9980-4f65-11eb-84b4-67c0e8025ca1.png)

**Comment by redhook62** [comment]
Hi **@kouh123**

Yes, it's probably a bug linked to some parameters of yout WebAuthN configuration.
Does the problem occurs at Login ou at Registration ? 

Can you post a screen of WebAuthN config like this one.

![image](https://user-images.githubusercontent.com/26826945/103628360-2c516d80-4f3f-11eb-8d15-ee597e2dfed9.png)

Regards

**Comment by kouh123** [comment]
Hi @redhook62 
Thanks for the response.
problem occurs at  Registration.

`
PS C:\Users\administrator.DOMAIN> Get-MFASecurity -Kind BIOMETRIC


AuthenticatorAttachment         : Empty
AttestationConveyancePreference : Direct
UserVerificationRequirement     : Preferred
Extensions                      : True
UserVerificationIndex           : True
Location                        : False
UserVerificationMethod          : True
RequireResidentKey              : False
HmacSecret                      :
CredProtect                     :
EnforceCredProtect              :
`

Authenticator device
Fingerprint authentication built into notebook PC.

Regards

**Comment by redhook62** [comment]
Hi **@kouh123** 

So I tested with your parameters, which are indeed standard, I've not be able to reproduce your problem.
This may be related to the language (jp) in the username encoding.

Can you give me the name of the user concerned (in Japanese) in order to perform tests
send this information to adfsmfa@gmail.com

Regards

**Comment by kouh123** [comment]
Hi @redhook62 

I'm not use 2byte charactor in user attribute.
Should I send the following command result?
`Get-ADUser -Filter { SamAccountName -eq "testuser" } -Properties *`

**Comment by redhook62** [comment]
Hi @kouh123 

Yes, it could be usefull

Regards

**Comment by kouh123** [comment]
Hi @redhook62 

I sent an email with some information.
please confirm.

Regards

**Comment by redhook62** [comment]
Hier @kouh123 

Yes, mail recieved !

Ok, i will test as son as.

Regards

**Comment by redhook62** [comment]
Hi **@kouh123** 

New release available 3.0.2101.1

Thank you very much for the informations you have provided.

Regards

**Comment by kouh123** [comment]
Hi @redhook62 

Thank you for the quick fix.
It works!
