### ISSUE TITLE
How to use gMSA in Security Configuration in access account field ?

### ISSUE THREAD

**Issue by rike18** [neos-sdi/adfsmfa#140]
When i write in field "Access account" gMSA (domain\FSgMSA) and press "Test" it shows an error.

**Comment by redhook62** [comment]
Hi **@rike18** 

You must enter the gMSA account name with a "$" at the end (domain\FSgMSA$)
But you cannot know the password, unless using tools like Michael Grafnetter's **DSInternals**(https://github.com/MichaelGrafnetter/DSInternals).
So let the password blank, i don't know if it works.

regards

**Comment by redhook62** [comment]
Hi

these kind of account are reserved for Windows Services, you cannot use it for interactive logon.
On the otherside you assign rights for it.

Regards
