### ISSUE TITLE
cmdlet permission on new version

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#141]
Hi

Today i've tested new version 3.1.2102.0, but i think there is a bug with powershell cmdlets permissions. As an ADFS administrator i can't execute any scripts.

Regards
Tryglav

**Comment by redhook62** [comment]
Hi **@Tryglav** 

Yes, there's lot of change concerning security in this version, we are going to update the documentation.
As we said breifly in the release part, running cmdlets and console is gouverned by ADFS Configuration.

In Short, Your account must : 
- Be in the Local Administrators group on the server AND you must have configured management by Members of the Local Administrators Group in the ADFS snapin (Federation Service/Properties)
- Be in the "Delegated Administration Goup " for ADFS Administration

Let the option "Allow System Account for administration" enabled (we have to detail this in the documentation)

See screen below (in french ! sorry)

![image](https://user-images.githubusercontent.com/26826945/106738186-ea881580-6617-11eb-9891-76a499e1939f.png)

Or for the Delegated Administration Group
In this case your account do not need to be in the "Local Administrators" goroup of the system (server).
Keep in mind, that the account you are using can query as well your active directory, or your SQL backend 

![image](https://user-images.githubusercontent.com/26826945/106738400-26bb7600-6618-11eb-8e22-8aa8f694dd23.png)

Let us know

Regards

redhook

**Comment by Tryglav** [comment]
Hi @redhook62 

I had set allow local system account and allow local administrators gorup. I've eneble delegation for service administration and set it on domain security group. Accont is a member of local administrator group and member of delegated adfs admins group, but still don't have permission to execute powershell cmdlets.

Regards
Tryglav

**Comment by redhook62** [comment]
Hi **@Tryglav** 

Well we are on the right track, obviously these rights would have deserved to be positioned previously.
The cache values appear to be invalid.

On each server, go to the "c:\Program Files\MFA\Config" directory
Delete the config.db and system.db files.
Then restart the "MFA Notification Hub" service or restart the server.

Regards

redhook

**Comment by Tryglav** [comment]
Hi @redhook62 

Unfortunately didn't help, still inform that cmdlet must be executed with adfs administration rights granted.

Regards
Tryglav

**Comment by redhook62** [comment]
Hi @Tryglav 

Can you tell me witch cmdlets you are using ?

Does your interactive account is member of the local administrators group and/or member of the Delagated Adfs administration group ?

Remember, the interactive account must have read/write on ADDS for all the users, and all the needed properties, or with SQL, must have access read/write to the MFA Database. 

When you change on ADFS the security parameters for administration, you delete the two files (config.db and system.db) on each server, then restart the MFA service (MFA Notification Hub). 

Regards

redhook

**Comment by Tryglav** [comment]
Hi @redhook62 

Any get, set cmdlets. For example get-mfacomputer, get-mfaconfig, get-mfafarminformation.
Yes i've deleted config files on each adfs nodes, but still have no permission. When i come back to previous version every cmdlets works ok.

Regards
Tryglav

**Comment by redhook62** [comment]
Hi

OK like you want.

Be aware that we do not have this type of problem (tested ADFS 19/16 / 12r2 with WID and SQL, farm multiple servers)

The information transmitted is too small (error message, event logs, operation of the console (same system of rights), assignment of users to groups, etc.

We will see if we have other feedback from other startgazers.

regards

redhook

**Comment by Tryglav** [comment]
Hi

My configuration ADFS 19, WID, standalone. 

Regards
Tryglav

**Comment by redhook62** [comment]
Hi All

The system.db file contains security information (SID) for AD FS administrators.
This file is created by the MFA service **if this file does not exist.**
Obviously, this informations are "cached", because its recovery takes a little time, and is used very often.
So deleting the system.db file, forces the SIDs to be reloaded.

I think we'll force recreate this file every time the MFA service restarts.

regards
