### ISSUE TITLE
cmdlet permission continue subject

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#142]
Hi

I want to come back to cmdlet permissions on new version MFA.
In my case the file system.db doesn't be creating. 

![Capture20](https://user-images.githubusercontent.com/63842532/107504811-1ff2ad00-6b9c-11eb-9b50-d8b75cb056d3.PNG)

Under what circumstances application creates this file? Restart services not help.

Regards
Tryglav

**Comment by redhook62** [comment]
Hi,

As it indicated in the Wiki, you must enable Local System Administration in ADFS MMC.
See 01 installation

Regards
