### ISSUE TITLE
installer logs

### ISSUE THREAD

**Issue by Tryglav** [neos-sdi/adfsmfa#144]
Hi

I have question. Where to find installer logs, when the installation fails?

Regards
Tryglav

**Comment by redhook62** [comment]
Hi **@Tryglav**

You can follow these inputs

msiexec.exe [/i][/x] <path_to_package> [/L{i|w|e|a|r|u|c|m|o|p|v|x+|!|*}][/log]
<path_to_log>

https://www.advancedinstaller.com/user-guide/msiexec.html

regards

redhook
