### ISSUE TITLE
Response time.

### ISSUE THREAD

**Issue by JustITPL** [neos-sdi/adfsmfa#145]
Hi, 

I don't know what is wrong but I have problem with long response time in MMC and in PowerShell with users management . 
In MMC when i go to "Users management" I must wait about 30-40 second to load users. When i scroll down about 22 rows, again I must wait about 20-30 seconds to load users.

For now we have 300 users of MFA.

Sample: I measured the commands and Get-ADUser command take about 3 seconds and Get-MFAUsers take about 20 seconds. 

Witch kind of configuration are you using for MFA ? ADDS
Witch kind of configuration are you using for ADFS ? WID
How many ADFS servers do you have ? Two
What is your ADFS Version ? 4 (2019)
ADFS MFA Version : 3.1

![image](https://user-images.githubusercontent.com/78961810/108055144-db5d8a80-704f-11eb-80c4-5ae39601d5e3.png)
![image](https://user-images.githubusercontent.com/78961810/108055201-f29c7800-704f-11eb-9b08-1717a6dce441.png)

**Comment by redhook62** [comment]
Hi, 

We have no problem, please check your configuration
![image](https://user-images.githubusercontent.com/26826945/108081385-3358b900-7071-11eb-89f2-4d02eac81c5d.png)

Now, if you have many domains or huge numbers of users, we recommend to switch to SQL Server configuration, for MFA and ADFS...
For SQL configuration, we have tested with 450 000 accounts, without any problems. But for 300 users ADDS configuration can do the job.

regards
