### ISSUE TITLE
Connect to Exchange/Azure AD with MFA from powershell.

### ISSUE THREAD

**Issue by JustITPL** [neos-sdi/adfsmfa#146]
Hi,

Is it possible to connect to Exchange from PowerShell with user who has MFA?

In AAD MFA it's look like that:
https://docs.microsoft.com/en-us/powershell/partnercenter/multi-factor-auth?view=partnercenterps-3.0

I'm using PSSession to connect to Exchange:
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Authentication Basic -Credential $cred
Import-PSSession $Session

**Comment by redhook62** [comment]
Hi

Can it work ?!
In all cases, you need a redirect to your ADFS.
I can't tell you more

regards
