### ISSUE TITLE
Importing users from ADDS through MMC/Powershell

### ISSUE THREAD

**Issue by zjorz** [neos-sdi/adfsmfa#147]
Using a DN as the LDAP path to import users from, using either MMC or Powershell, nothing happens/is imported

**Comment by zjorz** [comment]
I do not get the access denied issue.
Importing from AD is still not working
I see the log file "C:\Program Files\MFA\adimport-132584106242329657.log_132584106242329657.log" saying


Importing for AD : OU=Users,OU=EMPLOYEES,OU=Org-Users,DC=XXXXXX,DC=NET
    Querying users from AD
    Querying return 51 users from AD
    
    Importing ADDS Mode
        mmc.exe Information: 0 : Importing user XXXXX@XXXXX from AD
            DateTime=2021-02-21T19:50:24.9988147Z
        mmc.exe Information: 0 : Importing user XXXXX@XXXXX from AD
            DateTime=2021-02-21T19:50:25.0300686Z


however in the MMC I do not see the imported users. Why is that?
As mentioned earller, from a perms perspective I can do anything.

Why are the users not displayed in the MMC after import?

**Comment by zjorz** [comment]
manually adding a user through the MMC, in the end that user is not dipsplayed as a new user in the MMC or through the Powershell cmdlets

**Comment by redhook62** [comment]
Hi, @zjorz 

Importing users with the MMC, lest the users disabled by default.
To view all users, select "Clear Filter"

regards

**Comment by zjorz** [comment]
when I imported it, the unselected the option DISABLE USERS

Clearing the filter does not help

If you want to see it with your own eyes, I'm happy to have a short call and share screen

**Comment by redhook62** [comment]
So, Users have not been imported, 
see the import log file in MFA directory
