### ISSUE TITLE
Error with OTP email template placeholder {4}

### ISSUE THREAD

**Issue by abe57330** [neos-sdi/adfsmfa#157]
Hi everyone,

I'm setting up version 3.0.2101.3
When trying to customize the email template for Email OTP, I get an error if I try to use the {4} (should be user's mail address according to documentation).

I want the users to connect using their own email address, so it would be convenient to use it in the email sent OTP.

Thank you for any help/suggestion on this.

**Comment by redhook62** [comment]
Hi **@abe57330** 

The TOTP mail only supports {0}, {1}, {2}, {3} placeholders.
The documentation is wrong, we have to update it.

Thanks

redhook

**Comment by redhook62** [comment]
Hi everyone

Documentation updated !

regards

**Comment by abe57330** [comment]
Thanks for your quick answer, appreciated.

Is there any plan to implement additional placeholders in this template ?

BR

**Comment by redhook62** [comment]
Hi, 

You can make suggestions, but for a one-time code, the user name and code are more than sufficient, especially for privacy issues.
Mail or sms are not reliable vectors.
watch this video ... 
https://youtu.be/Z9kO4VmN1FM 
https://www.martinvigo.com/voicemailcracker/

regards

**Comment by abe57330** [comment]
Thanks again for sharing these interesting technics and videos... good to know.

I agree with the fact it is better to keep the email content as minimal as possible, for privacy issues as. I also know and agree that sms and mail are not reliable vectors for transporting secure informations.

In our scenario, we just want to allow the user to connect using its email address instead of his domain upn. And the default MFA provider will be set to TOTP.
So email will only be used for 1st connection, to enroll TOTP app, or as a fallback, using the "signin another way" link, if for example a user forgets or looses his mobile phone.
In that specific case, I'd have liked user to receive an email with OTP code indicating their own email address (the email field in AD) rather than their upn.

I don't know if my scenario is a common one, and then is worth to be implemented, but then you have the full story about it.

Best regards

**Comment by redhook62** [comment]
Yes, you are right.

If you want to have a new placeholder ({3} email address) 
it's of course possible.
It will be in the next version.

best regards

regards

**Comment by abe57330** [comment]
Hello,

Thanks a lot, greatly appreciated.

I didn't even mention it, but for the same reason, it would be then nice to have the user's email address placeholder available in MailNotifications template too, in order to have something consistent.

Best regards.

**Comment by redhook62** [comment]
Yes, of course !

regards

**Comment by redhook62** [comment]
Done in version 3.1.2103.3

regards

**Comment by abe57330** [comment]
Hi,

Thanks a lot for your great reactivity !

Unfortunately, I am getting this error with version 3.1.2103.3:

![image](https://user-images.githubusercontent.com/79278323/110760812-6563d200-824f-11eb-983e-247ce9d5d2a8.png)

Then I get an empty MMC:

![image](https://user-images.githubusercontent.com/79278323/110760921-7ca2bf80-824f-11eb-9234-5a2973cba020.png)



BR
