### ISSUE TITLE
Allow customization of WebAuthn key/device descriptors

### ISSUE THREAD

**Issue by gtbuchanan** [neos-sdi/adfsmfa#158]
I've been using ADFSMFA for a while now and it's been working great for my needs. One of the minor nits I have is not being able to provide a custom name for a device. Here's an example of WioKey (none), YubiKey (packed), and Android (android-safetynet) registrations together:

<img src="https://user-images.githubusercontent.com/715687/110578577-c1810600-812a-11eb-9928-31c5ec4fb781.png" width="500">

It's currently impossible to differentiate between my two Yubikeys other than by knowing which one I use the most. The other names are not descriptive enough either so I'd love to be able to specify a custom name as you can do with other platforms. GitHub for example:

<img src="https://user-images.githubusercontent.com/715687/110579198-e4f88080-812b-11eb-8db1-8237784de5de.png" width="500">

I understand this would complicate the management interface somewhat (particularly for self-registration) but I think it would be worthwhile since it's always recommended to have more than one device as a backup.

**Comment by redhook62** [comment]
Hi **@gtbuchanan**

 Good idea !

In the security descriptors, there is no descriptive information on the authenticator used, but simply the verification "method" (we will recheck this point ...).
We will implement it by asking for a descriptive name provided by the user during registration.

We will keep you posted.

regards

**Comment by redhook62** [comment]
Hi **@gtbuchanan** 

Done in version 3.1.2103.4.
You must re-register your keys, to be able to give them a Nick Name.

regards

redhook
