### ISSUE TITLE
Validate user-entered data during initial registration

### ISSUE THREAD

**Issue by k-korn** [neos-sdi/adfsmfa#16]
Currently, if 
a) Users are required to have MFA configured
b) On the first registration user mistypes his phone number and does not enter e-mail as an alternative contact 
as a result the user will be locked out of the system, and can only log in if site administrator resets his MFA data to allow re-registration.

It would be great if some future version of ADFS MFA would perform validation of user input by actually sending SMS to user-entered number and confirming that the user actually received it before completing the registration and requiring SMS on the next log in.
Same can be true for e-mail based access - if user enters e-mail which he can not access, he will be locked out.

**Comment by redhook62** [comment]
Hi,

Yes, it's true.
But admins can unlock the account in the case you describe. 
That's what, we want for security reasons. 

If the UI prevent users to make mistakes when registering, of sure it would be better.
So, as said in previous request [#13](https://github.com/neos-sdi/adfsmfa/issues/13), next version have many new features. for example we have implemented **registration validation** for QRCode. 
The providers model has changed to fully supports Biometric registration in the future. and the new MFA azure model now.
So, registration verification on each Provider  (OTP, SMS/External/Custom, Mail, Azure, etc..) is planned for version 2.2
We planned to ship a beta early in may 2018, definitive version early in june.

Regards

Some screen shots of 2.2 Registration validation for QRCode

## Manage my Options
![p1](https://user-images.githubusercontent.com/26826945/37958435-d33d334a-31b0-11e8-8b89-aadec8bc249c.png)

## Registration Process Start
![p2](https://user-images.githubusercontent.com/26826945/37958449-dda6d598-31b0-11e8-9a03-4b1aeea8d560.png)

## QRCode Scanning
![p3](https://user-images.githubusercontent.com/26826945/37959215-e23f15f0-31b2-11e8-85a3-04af6054a9e9.png)

## Code verification
![p4](https://user-images.githubusercontent.com/26826945/37958648-56dba34e-31b1-11e8-9ecf-8862897dfc49.png)

## Success or error
![p5](https://user-images.githubusercontent.com/26826945/37958689-693f0008-31b1-11e8-9ac2-1410e01eec03.png)

**Comment by k-korn** [comment]
Thanks! Missed issue #13 somehow.

**Comment by redhook62** [comment]
https://github.com/neos-sdi/adfsmfa/issues/13
