### ISSUE TITLE
Remotely execute powershell commands (Invoke-Command) part 2

### ISSUE THREAD

**Issue by JustITPL** [neos-sdi/adfsmfa#160]
Hi

I can't work with user accounts, when I execute Get-MFAUsers in response i have null. 
Version of ADFSMFA: 3.1.2103.5

![image](https://user-images.githubusercontent.com/78961810/111313332-8453d100-8660-11eb-8f56-709046fb03d2.png)

**Comment by redhook62** [comment]
Hi, @JustITPL 

**Please look at the eventlog on your servers.**

For us, evrything is working as well. and nothing has changed with the last version.
Please fllow the Wiki (not like zjorz... :) )
https://github.com/neos-sdi/adfsmfa/wiki/01-Installation#recommended-sql-server-configurations
https://github.com/neos-sdi/adfsmfa/wiki/01-Installation#recommended-adds-configurations

The main difference between Get-MFAConfig and Get-MFAUsers, is when you use *-MFAusers you are querying your backend (ADDS or SQL-Server depending of you configuration. 
So, perhaps your user don't have the rights to query your backend.
If Get-MFAConfig run as well, remoting seen running as expected.

![image](https://user-images.githubusercontent.com/26826945/111319098-f24ec700-8665-11eb-8c97-2682242bb88e.png)

regrads

**Comment by JustITPL** [comment]
I don't tested previous version with remote PowerShell management. My account have Domain Admins and is in Delegated Administrators group and local admin, so It's should work. We have configure MFA with ADDS. On MFA server i can execute commands without issue. 
![image](https://user-images.githubusercontent.com/78961810/111327023-52953700-866d-11eb-913e-b5a9e5e9d309.png)

**Comment by redhook62** [comment]
Ok,

but, like as said before, what are the logs (in eventlogs) ?
Have you tested with enter-pssession ? have you executed this command multiple times ?

Please, post here, all the eventlogs relating to your problem, or send me them on the email precised in code source.

regards

**Comment by JustITPL** [comment]
what are the logs (in eventlogs) ? In attachment.
Have you tested with enter-pssession ? Yes, the same result.
have you executed this command multiple times ? Yes, many times.

Every time, I execute a command remotely, I have the same result in Event Log (only in MFA. Nothing in ADFS).

It's xml file, I'm changed extension to txt.
[mfa.txt](https://github.com/neos-sdi/adfsmfa/files/6154290/mfa.txt)

**Comment by redhook62** [comment]
Hi, **@JustITPL** 

Thank you.

As you can see in the logs "ADFS MFA DataServices" -> **Access Denied**

Your account, cannot access your active directory. 

Of sure ! the identity provided by PS Remoting is not allowed  to cross the boundaries of multiple machines. 
For this it would be necessary to have a valid Kerberos token. It depends on your infrastructure, if this were effective, it would also potentially be opportunities for hackers ...
We think Microsoft was careful about this ...

We have chosen not to rely on a wobbly or complex configuration, and **as indicated in the documentation [ADDS Configuration](https://github.com/neos-sdi/adfsmfa/wiki/01-Installation#recommended-adds-configurations) it is imperative to use a "data access account"** (ADDS or SQL). 
This allows every users with the correct rights to use all features (for example a Local Administrator account will be able to use PowerShell, PS Remoting or the MMC console), this also limits the rights given on your Active Directory forests.

Technically, in powershell remoting, the identity passed for requests on Active Directory is **NT AUTORITY\ANONYMOUSLOGON**

**You must therefore specify a data access account for ADDS in the configuration of the MFA / Security** (take a good look at what is written and what is underlined and in bold in [ADDS Configuration](https://github.com/neos-sdi/adfsmfa/wiki/01-Installation#recommended-adds-configurations)
For an SQL configuration, it is preferable to specify both an ADDS access account and an SQL account

In the administration console it's here [MFA/Security](https://github.com/neos-sdi/adfsmfa/wiki/07-Security#managing-mfa-security-with-mmc)

regards

**Comment by redhook62** [comment]
Hi,

Does it solve your problem ?

regards

**Comment by JustITPL** [comment]
I added a AD account to the MFA configuration. Now working fine.
![image](https://user-images.githubusercontent.com/78961810/111778550-1b18cb80-88b5-11eb-85b2-2a39f901e515.png)

**Comment by redhook62** [comment]
Hi,

Yes, you have to read the documentation, especially for the advanced functions.
However, as a good practice ... you should enter the domain name, even if you only have one forest, because moreover you have enabled LDAPS mode, and the requests must match the names of the certificates ... on ADDS. Is this done correctly?

regards

**Comment by JustITPL** [comment]
I changed it. Thank You.
