### ISSUE TITLE
Cannot change the default method to "Choose" from PowerShell

### ISSUE THREAD

**Issue by JustITPL** [neos-sdi/adfsmfa#162]
Hi,

I can't change the default method to "Choose" in PowerShell. When I execute the command, it stays in the previous method.

![image](https://user-images.githubusercontent.com/78961810/111966871-b600e800-8af7-11eb-9a24-4bd69b5795d8.png)

**Comment by redhook62** [comment]
Hi,

Yes that's true, it's explictelly made in the code since many years... 
However this is possible in the console, it does not make a lot of sense. 
After some checks, we will authorize the switch to choose mode.

please wait for a future version

regards

**Comment by redhook62** [comment]
Done in version 3.1.2103.7
