### ISSUE TITLE
Clustered ADFS with MFA problem.

### ISSUE THREAD

**Issue by BartHermans007** [neos-sdi/adfsmfa#166]
I use the application for a year now (on a single ADFS) and it is working fine.
But now I installed it on a clustered ADFS (test environment) and I have a problem (version 3.1.2104.0).
ADFS Primary cluster node  = Node 1
ADFS secondary cluster node = Node 2

Problem 1: When I change settings on Node 2, it reflects on Node 1 (after a refresh).
But when I change settings on Node 1, it never reflects on Node 2 (not even after refresh...).
So I could end up with two different MFA settings, depended which server the request is taken...

Problem 2: This problem is a consequence of Problem 1
When I save on Node 2 some settings, they are reflected on Node 1. 
But when the last action is a saved setting on Node 1, the secret keys become all different on Node 1.
So depending on which server I arrive, the TOTP works or not.
When I save some settings on Node 2, the different secret key problem is gone on Node 1.

PS.: When I save a new configuration the 'status color' changes to orange, but it does not get the 'green' status. Only if I click on 'Refresh', it returns green again. (I don't have that behavior on my single node ADFS implementation version 2.0.2101.3)

PS.: When I save a new configuration,  in the event log I always get an error: EventID 9999 ADFS MFA Service : Mailslot Client Write Error (BDC): The system can not find the file specified. 
But I also get that error on the single node ADFS implementation.  On the single implementation another EventID 9999 is written with the message "Configuration loaded ! invoqued by : <ADFS servername>  after the first error.

**Comment by redhook62** [comment]
Hi **@BartHermans007** 

First, it seems that the servers cannot communicate with each other. like indicated in the documentation you must imperatively open the ports of the firewall as indicated in the [installation part](https://github.com/neos-sdi/adfsmfa/wiki/01-Installation#configure-windows-firewall-rules).
Be sure that your servers are well referenced with Get-MFAComputers. Also check that your servers use their own IP address between them, and not the VIP of the NLB part. when you open the ports

Example : 
- ADFS1=172.16.100.1
- ADFS2=172.16.100.2, 
- NLB VIP = 172.16.0.10 

**Set-MFAFirewallRules** -ComputersAllowed '172.16.100.1, 172.16.100.2' on each ADFS server
The NLB address must not appear in the firewall rules.

From each server you must trace the second server by its fqdn.
- from ADFS1 at command prompt >tracert **adfs2.domain.local**   -> 172.16.100.2
- from ADFS2 at command prompt >tracert **adfs1.domain.local**   -> 172.16.100.1
If not, you have a name resolution problem (DNS)

For message 9999, the services can be restarted. PS>**restart-service mfanotifhub**.

If you are in ADFS WID (Windows Internal Database) configuration, synchronization of the ADFS database is done every 5 minutes. but when the MFA service works correctly, it is instantaneous, it is still necessary that the exchanges between the servers is operational

let us know

redhook

**Comment by BartHermans007** [comment]
I will try your solutions and give you feedback tomorrow. Thanks a lot!

**Comment by BartHermans007** [comment]
Hello Redhook,

Both servers are on the same subnet.
I tried on both machine the tracert command and it replies with the correct IP.
Currently I don't use a firewall in my labo (No antivirus firewall, no MS firewall)
I tried a MS portquery tool (portqry.exe -n FQDNADFSNode -e 5987) and it shows a listening port on both nodes using the correct FQDN.

Tomorrow I'll check that the servers are well referenced with Get-MFAComputers

Thanks.

**Comment by BartHermans007** [comment]
It's resolved. I misunderstood the explanation how to add an extra ADFS MFA server in the cluster.
Your hint about 'Get-MFAComputers' was the key to success. Now I can start playing. 
Thank you very much for your (very fast) support.

**Comment by redhook62** [comment]
Hi,

Great !

I must admit that your problem has put us in doubt. Indeed, we had not done tests with the Microsoft NLB for several years. ARP (Layer level 2) often poses problems with routers, and then the multi NIC could have been a problem.

Remember that it is necessary to upgrade the MFA database (required for WebAuthN and RSA keys) or to create a new one. tables structures have evolved since version 2.0.
look at the side of Upgrade-MFADatabase or New-MFADatabase.

regards
