### ISSUE TITLE
MFA Error

### ISSUE THREAD

**Issue by AmeerErg** [neos-sdi/adfsmfa#168]
Hello, 

I am having an issue when i open MFA using MMC, an error occurred "must be executed with ADFS administration rights granted for current user", any suggestion? 

Note: Administrator account used to access ADFS, still having the same issue.

Best Regards

**Comment by AmeerErg** [comment]
This issue occurred when I upgrade from 3.0.2012.0 to the latest.

**Comment by redhook62** [comment]
HI @AmeerErg 

I think you can refer to this issue to solve your problem, as well as to the Wiki
[must be executed with ADFS administration rights granted for current user](https://github.com/neos-sdi/adfsmfa/issues/167)

regards

**Comment by AmeerErg** [comment]
Hi @redhook62,

Thank you, i will try this solution.

Appreciate your support.

BRs
