### ISSUE TITLE
Azure SQL Instance not connecting after upgrade

### ISSUE THREAD

**Issue by palanjam** [neos-sdi/adfsmfa#175]
Upgraded MFA from 3.0.2007.2 to 3.1.2105.0

Previously I was using an Azure SQL database but now it is not able to connect to it. Was there some change with the permissions with 3.1 that require the ADFS service account?

Connection string was using a username and password so I don't believe there is any way to link the service account to it.

**Comment by palanjam** [comment]
Reverted back to the old version and it's working fine.

A better solution is that I want to convert over to ADDS. Is there a way to migrate all the user keys so they don't have to re-register them?

**Comment by redhook62** [comment]
Hi,

SQL Azure mode is not tested ...
However, security developments have been made. so for example not to leave a password accessible in the console or PoweShell.
So I recommend one thing to you. you must remove the username and password from the connection string. Then assign the Data Accces Account for SQL (Security tab)

regards

**Comment by redhook62** [comment]
hi, @palanjam 

Have you made progress on the subject ?

You can export the configuration with Export-MFASystemConfiguration and change the passwords (in plain text) then re-import the file generated with Import-MFASystemConfiguration.

In any case, the component must work with a SQL Azure database, although not tested by us.

regards

**Comment by palanjam** [comment]
Hey @redhook62,

No I haven't. I've been really busy and haven't been doing testing lately. I reverted back to the old version and am currently testing out an upgrade to the latest version and transferring everything over from SQL to ADDS.
