### ISSUE TITLE
Download link for ADFSMFA latest release broken

### ISSUE THREAD

**Issue by ns3c** [neos-sdi/adfsmfa#181]
While attempting to download the latest-release binary for adfsmfa, I discovered it is not actually available.

https://github.com/neos-sdi/adfsmfa/releases/download/3.1/adfsmfa.3.1.2106.0.msi

I figured I would make the team aware, as I will need to build from source now.

**Comment by redhook62** [comment]
Thank You !

Now, it works fine

regards
