### ISSUE TITLE
Beta version 2.2.0.18 and later

### ISSUE THREAD

**Issue by redhook62** [neos-sdi/adfsmfa#19]
Hi All,

Feel free to post you remarks and bug found.
We are working with you !

Regards

**Comment by k-korn** [comment]
Thanks a lot!
Opened #20.

**Comment by anorstrom** [comment]
Thank you for this nice update!
We re-installed it and tested with new user accounts, and it works nicely! 

We like the new Enrollment Wizard feature, and have one request on that for the end user experiance.
Do you think it would be possible to change/add the following?

When "User Management Options" is unchecked (MMC under Global parameters settings), could that then also remove the checkbox "access my options after authentication", on the Verification Code page, but still have the Enrollment Wizard working? For example: 
1. User click "I do not have code"
2. User is prompted for his email/phone
3. On next page user types the verification code that was received on email or phone (again without the checkbox "access my options after authentication").
4. Now enrollment wizard can start.

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Thanks,

We will look at your idea, It should be possible, but with a specific flag, because some others prefer to have "access my options after authentication"

Regards

**Comment by redhook62** [comment]
New version 2.2.0.20

Some bug correction.
Implementation for your scenario. 
feedback appreciated

Regards
