### ISSUE TITLE
MFA only working on single server in ADFS Farm

### ISSUE THREAD

**Issue by chris4702** [neos-sdi/adfsmfa#192]
Hello -

I have a Windows 2019 ADFS Farm, consisting of two Windows 2019 servers in front of a load balancer, using the internal database, and AD for the storage of the MFA attributes.

MFA works fine on the first server, but does not function on the second.

Looking at (Get-MFAFarmInformation).Servers, I only see the primary server in the ADFS server farm.

I've tried using Register-MFAComputer, and it fails as well.

I've tried several different ways of installing ADFS MFA.  I've done it with the farm created, I've also tried installing it before adding the second server to the farm, both failing.

`PS C:\Windows\system32> Register-MFAComputer -ServerName "XXXX02" -norsakeyreset

Confirm
Are you sure you want to perform this action?
Performing the operation "Register-MFAComputer" on target "Register ADFS Computer for MFA : XXXX02".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
Computer XXXX02 NOT Added/Updated to MFA configuration

FQDN                      : XXXX01.domain.lab
BehaviorLevel             : 4
HeartbeatTmeStamp         : 9/7/2021 9:26:00 PM
NodeType                  : PrimaryComputer
CurrentVersion            : 6.3
ProductName               : Windows Server 2019 Standard
InstallationType          : Server
CurrentBuild              : 17763
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
MachineName               : XXXX01

PS C:\Windows\system32> (Get-MFAFarmInformation).Servers

FQDN                      : XXXX01.domain.lab
BehaviorLevel             : 4
HeartbeatTmeStamp         : 9/7/2021 9:26:00 PM
NodeType                  : PrimaryComputer
CurrentVersion            : 6.3
ProductName               : Windows Server 2019 Standard
InstallationType          : Server
CurrentBuild              : 17763
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
MachineName               : XXXX01

PS C:\Windows\system32> (Get-MFAFarmInformation)

IsInitialized CurrentFarmBehavior FarmIdentifier                              Servers
------------- ------------------- --------------                              -------
         True                   4 http://fs.domain.com/adfs/services/trust {Windows Server 2019 Standard}

`

**Comment by redhook62** [comment]
Hi,

If you are using ADFS 2019, and if you have a farm of 2 servers (farm well initialized with 2 servers)
After registering ADFSMFA, there's no need to add a new server with Register-MFAComputer.

If you really need to add a new server after the initial registration of the component. yes you must run the cmdlet Register-MFAComputer, for the servername parameter, you must specify the ip adress or the FQDN of the server to be added.

regards

**Comment by chris4702** [comment]
Hi, 

The Set-MFAFilewallRules was not functioning properly on the second server.  I had manually set the ports in the firewall, and that fixed the issue.

Thanks for the quick reply!
Chris
