### ISSUE TITLE
Biometrics on Safari on IOS 15

### ISSUE THREAD

**Issue by rtemelcea** [neos-sdi/adfsmfa#195]
Trying to enroll for biometrics from Safari fails with the error "The request has been cancelled by the user". I can login with my enrolled yubikey, but i have to always press the "Sign In" button again. So always the first Webauthn request is cancelled by IOS.

Phone: iPhone 11, FaceID
ADFS: 2019
AdfsMFA: 3.1.2109.0

![image](https://user-images.githubusercontent.com/34248314/135483457-9fc7ca56-e876-4df3-bea9-8be7d6048b02.png)
 
WebAuthN settings. Tried with Platform only too.

**Comment by redhook62** [comment]
Hi @rtemelcea 

Yes, we are aware of it.
Apple came to WebAuthN very late ...
Now they are coming with new devices :) Hey, yes, with FaceID that would be very cool (it has been working with Windows for 3 years ...)
We plan to update the FIDO2-NET library during the month of October, the time to integrate and check for potential side effects.
So, see you in a few weeks for a new version.
Thanks, for testing adfsmfa

**Comment by rtemelcea** [comment]
One thing to mention, FaceID is working on FIDO2-NET demo site https://fido2-net-lib.passwordless.dev/ (on all the scenarios, MFA, Passwordless, Usernameless) so for sure there is something with your implementation. I am waiting for the update

Razvan Temelcea

On 30 Sep 2021, at 19:14, redhook ***@***.***> wrote:

﻿

Hi @rtemelcea<https://github.com/rtemelcea>

Yes, we are aware of it.
Apple came to WebAuthN very late ...
Now they are coming with new devices :) Hey, yes, with FaceID that would be very cool (it has been working with Windows for 3 years ...)
We plan to update the FIDO2-NET library during the month of October, the time to integrate and check for potential side effects.
So, see you in a few weeks for a new version.
Thanks, for testing adfsmfa

**Comment by redhook62** [comment]
Yes, we Know that ! But this is quite recent.

We do not take the FIDO-NET library as it is. 
ADFS is not a web app in IIS. 
We are adapting the code a bit, so that it runs on large production platforms (there are a lot of infrastructures with particular restrictions such as the fact that the servers have no access to the internet).

regards

**Comment by rtemelcea** [comment]
Using the following settings:
Authenticator Attachment: Platform
Attestation: None (tried with all options)
User Attestation: Preferred
Extensions: Yes
User verification method: Yes
Require resident key: No
Use constrained metadata: No

FaceID Still doesn’t work with IOS 15 (Request cancelled by user)

Razvan Temelcea

On 14 Oct 2021, at 01:12, redhook ***@***.***> wrote:

﻿

Hi @rtemelcea<https://github.com/rtemelcea>

Can you test this version ?

Tell us if it works in Face ID. Remember, this is only a preview, the final build will be early next week. We still have tests to perform, as well as an automation of the metadata update (MDS3 blob)

Please save your configuration before uninstalling your current version (Export-MFASystemConfiguration cmdlet).

The current fidoalliance blob currently contains more than 90 descriptions of devices (Phone, Security Keys, etc ...) necessary for the IPhone are present.

Also make sure to enable user verification method in the settings.
If you want to go back, please use the Import-MFASystemConfiguration cmdlet with the previously saved backup.

Last point, please let us know about any malfunctions if you find any.

regards

redhook

adfsmfa.zip<https://github.com/neos-sdi/adfsmfa/files/7341645/adfsmfa.zip>

**Comment by rtemelcea** [comment]
Unfortunately those settings don’t work, tried them on a fresh install. My problem isn’t with the sign in, because the first sign in attempt is “cancelled by user”, but if i press Sign In again I get the prompt to tap my security key. My problem is with registration, because there is no way to manually trigger the system pop-up again. I suggest that you can try to add a “Register Button” that lets you trigger again the system pop-ul. Similar to the ”Sign In” button.
Razvan Temelcea

**Comment by rtemelcea** [comment]
﻿
Tried to register my Yubikey on IOS. I still get “Cancelled by user”.
I am gonna describe how sign in currently works with biometrics:
1. I do the first factor authentication
2. The page with second factor shows up with the message “Action cancelled by user”
3. I press the Sign In button. And I am prompted to tap my yubikey to my phone.
4. Login is successful.

I tried to register my YubiKey by enabling Cross-Platform, I still get the message that the action has been cancelled. My guess is that you need to make the user initiate the biometric registration. I am available to test any beta or alpha version you come up with. It’s a homelab, so i don’t need it to be working perfectly.

**Comment by redhook62** [comment]
Hi,

please can you try with this pre-version.
We put a button in the registration process to avoid IOS/Safari security problems (Registration ceremony is launched now by a user click).
If you can register, after try to login. if it don't work, try to disable "Fast Login" in the Biometric provider properties.

An, of sure, give your feedback.

regards
[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7359899/adfsmfa.zip)

**Comment by rtemelcea** [comment]
I have wonderful news. I managed to register my IOS Face ID. At this time pressing the Sign In button in safari the page freezes, but in chrome it works. I did my first successful sign in on my iPhone and i’m so happy. Please guide me on how to get you logs so you can see why the page crashes on safari. 

Razvan Temelcea

**Comment by redhook62** [comment]
So for chrome it's good.

By identifying yourself (not in registration) have you deactivated the "Fast Login"?

For Safari, I understand that Apple considered it safer not to provide the verification method ... really weird ideas.

There is a usage counter which is incremented at each login to avoid the "replay" of assertions. I understand that Apple still wanted to leave it at Zero.
You can see the counter in the user's biometric options.

Try again for Safari, deleting the device first, and verify that it only works for the first time ?

It will also seem that the JS method on a "preventDefault" form does not work with Safari.
I am joining you a build on which I deactivated this call.
it may be that one of the errors

regards
[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7360024/adfsmfa.zip)

**Comment by rtemelcea** [comment]
The error message changed and now it says: "Value can't be null" (deleted my device and registered it again).

**Comment by redhook62** [comment]
Great !

**Comment by rtemelcea** [comment]
Tried that version, registering no longer works.

**Comment by redhook62** [comment]
Ok, thanks

**Comment by rtemelcea** [comment]
I have exciting news. I was able to register my iPhone. Fast Login correctly disables on IOS(Safari and Chrome) and stays on on Edge Chromium on Windows 10. One thing to mention the “Sign In” button still needs to be used on Windows. (Didn’t quite get if you only want it to be enabled on IOS).

I think you can name the button: “Register Biometrics” or “Register Device”.

Thank you for your amazing work. Is there anywhere I could donate, because your engagement is amazing.

Razvan Temelcea

Hi, @rtemelcea<https://github.com/rtemelcea>

I attach you here, the last build, if you can test this evening or tomorrow, it will be the final version of October.
Pealse, check that there are no errors in JS.
For information, when an apple device is detected (IPhone, IPad, IPod, Macintoch), we baculate by deactivating the 'Fast Login' and try to initiate a connection made by the user.
Keep in mind, that we don't have an Apple device on hand. So your help is very important.
thanks again

regards

adfsmfa.zip<https://github.com/neos-sdi/adfsmfa/files/7375239/adfsmfa.zip>

redhook

PS: moreover, if you have a better solution for the button label added during recording; we are obviously interested in your suggestions
