### ISSUE TITLE
Missing files in solution 2110.1

### ISSUE THREAD

**Issue by apr-un** [neos-sdi/adfsmfa#200]
Hi @redhook62 

I merged changes from current version 2110.1 to my project, and found that there are few files missing:
Neos.IdentityServer.Console -> Resources\Neos.IdentityServer.Console.Ctrls.en-US.resx
Neos.IdentityServer.MultiFactor.WebAuthN.Provider -> app.config
Neos.IdentityServer.Deployment -> CustomAction.config

Config files were already fixed in June 2021 (version 2106.x)), now they're missing again :( 
CustomAction is needed, but app.config is not and should be removed from solution.

EN-US resource was never used before, so I think its not needed too and should be removed.
Regards
apr-un

**Comment by redhook62** [comment]
Hi @apr-un 

Yes, for CustomAction.config.
For others, they must be removed (Neos.IdentityServer.Console.Ctrls.en-US.resx, and app.config)

regards
redhook
