### ISSUE TITLE
Can't complete user registration if using TouchID and Safari

### ISSUE THREAD

**Issue by PsySuck** [neos-sdi/adfsmfa#201]
Hi.
My setup:

- I am using the latest version. AD as storage.
- OS MacOS Monterey 12.0.1
- I am using touchID for logon.

I found I cannot complete registration if using TouchID and Safari. If the user has already registered using another browser, then you can make an enroll touchID using safari.
Steps to reproduce:

1. A new user enroll app using Safari.
2. Further attempt to enroll the biometric device TouchID error appears:
  _Your account is not validated !_
  _You can try the operation again by selecting "Previous"._
  
  _This request has been cancelled by the user._

If you make the user first using the powershell command or use another browser, the problem is not reproducible. There is nothing in event logs.

**Comment by redhook62** [comment]
HI @PsySuck 

The registration process is per device and not for each browser, 
So if you have already registered your MacOS, you don't need to do it again.

I think it is preferable to make the first registration with safari, the FIDO attestation will certainly be more in line with Apple standards.

It is important to request verification of the user's presence in the security settings (Preferred)

regards

redhook

**Comment by PsySuck** [comment]
Hello, @redhook62.
It is not about use one  enrolled device in different browsers. 
My configuration:
TOTP and Biometric - required. Other providers are disabled.

New users try perform first registration in Safari  - can't complete registration.
New users try perform first registration in Chrome - can complete registration and after that can enroll touchID in safari.

BTW enrolled Yubikey with NFC on macos - works on iphone too.

**Comment by redhook62** [comment]
Hi, @PsySuck 

As indicated in the October release.
Apple became interested very late in WebAuthN, and also immediately wanted to change things, by justifying itself on their Blog despite a lack of credibility ...: https://webkit.org/blog/11312/meet -face-id-and-touch-id-for-the-web /

It emerges that any connection / registration must be initiated from a button or any other effective action of the user that it was with FaceID or TouchID and that the usage counter must always remain at Zero, this which is not logical since this function prevents the replay of assertions. (MacOs, Iphone, Ipad, ...) by using WebKit.

When registering your device, a certificate will be created, its type depends on the type of device above all but also on the browser used. once stored to allow future authentication, this certificate will always be reused, and only its usage counter will be regularly incremented.
This is the reason why I am asking you to delete your keys registered for a user and re-register your iPhone through the options.

This is what I ask you to achieve.

1) Make sure that the connection is initiated by the user (Click Button). So turn off "FastLogin" in the security options.

![image](https://user-images.githubusercontent.com/26826945/141116798-f827d146-42d6-46fd-859f-5ec03ff798c8.png)

2) Make sure that user presence verification is enabled

![image](https://user-images.githubusercontent.com/26826945/141116973-70964788-60ee-441b-af9d-a3081a883057.png)

3) Validate a registration (Attestation) with your Apple device and Safari !

4) Make sure that the recording went well

5) Try to reconnect using TouchID

You do not need to register your device again with Chrome or any other browser
Please confirm the completion of the steps described.

6) Try to sign in with Chrome

7) Try to log in with Safari again

Please confirm the completion of the steps described.

I think Chrome doesn't create an Apple Type Attestation or it increments the usage count. whether it is one or / and the other it does not comply with the specifications indicated by Apple.

Confirm the test results to me, so that I can understand and move forward on your problem.

regards

redhook

**Comment by PsySuck** [comment]
Hello.
I missed point about User attestation.
Thanks I will check it.

**Comment by PsySuck** [comment]
I disabled fast login, but is still try to auth/register without ask me click to button.

**Comment by redhook62** [comment]
Hi,

If, you do not have the form with a button, a configuration problem surely, because this option is available since the integration of WebAuthN 2 years ago.

Next week, I'll send you a debug build.

regards

**Comment by PsySuck** [comment]
How i can check fast login parameters in config or via powershell?

**Comment by PsySuck** [comment]
I think i have config problem:
I found it in eventlog - Error decrypting value for Pass Phrase Encryption : The parameter is incorrect.

**Comment by redhook62** [comment]
@PsySuck 

Yes, there is a concern.
Here is the procedure to follow.

On your Primary ADFS server as Local administrator.

Launch PowerShell in Administrator mode
Export-MFASystemConfiguration -ExportFilePath c:\temp\myconfig.xml

1) Search for "XORSecret" and replace the value with: "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"

2) Search for "password" under the ActiveDirectory tag, replace the value with your clear password.

3) Search for "SQLPassword" under the SQLServer tag (if applicable), replace the value with your clear password.

4) Search for "password" under the SendMail tag (if applicable), replace the value with your clear password.

5) Save the xml file.

Launch PowerShell in Administrator mode
Import-MFASystemConfiguration -ImportFilePath c:\temp\myconfig.xml

Launch the MMC Console
Select the Security Node.
Test your conncetions.

If success the click "SAVE"

regards

redhook

**Comment by PsySuck** [comment]
Hi.
It works. Thank you!
But i still can't use safari for full registration. There are no additional logs?

**Comment by redhook62** [comment]
Hi,

I still don't have a clear idea of what error you have. I would like to add logs to help you, but I still need to know where to do it. in all the code this is not possible.

First, please confirm to me that you have performed the tests I requested.
Then, are your system and your browser up to date ?
Do not rely on chrome, even if the system does not support WebAuthN, Chrome, Edge, Brave implement it.

Delete all the registered WebAuthN keys on your test user (in the console for example).
Then reactivate the Fast Login.

With Safari, try a registration, you must have a form offering a connection with a button.
If this is not the case, in the browser activate the debugger (F12), and in the console type "navigator.userAgentData.platform" and note the result.
Please make a detailed report of these operations.

regards

**Comment by PsySuck** [comment]
I deleted user via MMC. I checked AD attributes. Fast Login disabled.

https://user-images.githubusercontent.com/87027160/142001721-a738b4b0-5350-445b-bc8e-caec34cc7a97.mov
In Develover Tools
<img width="1324" alt="Screenshot 2021-11-16 at 17 18 05" src="https://user-images.githubusercontent.com/87027160/142001979-ee00a777-c829-4d76-b34d-a8b2e8c6347f.png">

**Comment by redhook62** [comment]
What is the value of "navigator.userAgentData.platform"

**Comment by PsySuck** [comment]
Error exist only in Safari.

**Comment by redhook62** [comment]
In developers tools / console 
at prompt -> navigator.userAgentData.platform

**Comment by PsySuck** [comment]
<img width="1345" alt="Screenshot 2021-11-16 at 18 25 45" src="https://user-images.githubusercontent.com/87027160/142014248-fc2f7bef-6717-47b0-82c0-56847bcec73b.png">

**Comment by redhook62** [comment]
Ok, your platform is "MacIntel".

I will send you a custom build soon.

regards

**Comment by PsySuck** [comment]
Funny. I don't have this problem on test env.

**Comment by redhook62** [comment]
Please try this one

You MUST have a form with a button for registering or for logon. let Fast Login enabled for other platforms

Uninstall prior version
Install this one

that's all

regards
[adfsmfa 3.1.2111.1.zip](https://github.com/neos-sdi/adfsmfa/files/7547841/adfsmfa.3.1.2111.1.zip)

**Comment by PsySuck** [comment]
Should i export or import config?

**Comment by redhook62** [comment]
> Funny. I don't have this problem on test env.

With the same version ? with same parameters on WebAuthN security ?
Before WebAuthN update Apple attestaion was set to None (no check at all)

**Comment by redhook62** [comment]
> Should i export or import config?

No, just unintall the prior msi and install the new one

**Comment by PsySuck** [comment]
With the same version ?  3.1.2110.0 on Test. 3.1.2110.1 on Prod.
with same parameters on WebAuthN security ? **Yes.**
Before WebAuthN update Apple attestation was set to None (no check at all). I think yes

**Comment by PsySuck** [comment]
Same problem.
I found erro during installation on both node:
`Error Initializing WebAuthN Metdata Repository : There was no endpoint listening at net.tcp://localhost:5987/WebAdminService that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details. /// 
Server stack trace: 
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.DecodeFramingFault(ClientFramingDecoder decoder, IConnection connection, Uri via, String contentType, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Neos.IdentityServer.MultiFactor.IWebAdminServices.HasBLOBPayloadCache()
   at Neos.IdentityServer.MultiFactor.Data.WebAdminManagerClient.HasBLOBPayloadCache()
   at Neos.IdentityServer.MultiFactor.WebAuthN.Metadata.BaseSystemMetadataRepository.HasBLOBPayloadCache()
   at Neos.IdentityServer.MultiFactor.WebAuthN.Metadata.MDSMetadataRepository.<GetBLOB>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
`

**Comment by redhook62** [comment]
Hi,

Ok, I will therefore put explicit logs.
For the indicated error, yes this happens during the installation, when the services are not yet available.
You can ignore this error, just check that the Windows Service "MFA Notification Hub" is started on each server.

**Comment by PsySuck** [comment]
I tested new build on test env. Same problem now present on test env too.

**Comment by redhook62** [comment]
Hi,

Can you test this build.
We put some logs to trace why you have problems in registration (watching to UserAgentData or UserAgent)

Please after, look at the eventlog of your ADFS Servers, for Warning entries events 100, 101, 102, 103.
Then send us your results

regards
[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7555078/adfsmfa.zip)

**Comment by PsySuck** [comment]
I can't find these events.

**Comment by PsySuck** [comment]
I checked Applications, System, ADFS admin and ADFS trace - nothing.

**Comment by redhook62** [comment]
Hi, @PsySuck 

Added more logs (warnings in Application EventLog) and alerts when detecting your device.
You can also check javascript errors

Please send me back your test results.

regards
[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7570540/adfsmfa.zip)

**Comment by PsySuck** [comment]
<img width="960" alt="Screenshot 2021-11-19 at 16 44 42" src="https://user-images.githubusercontent.com/87027160/142632797-4303f4d4-f20f-42c4-a5b4-a4eadc85fe25.png">
<img width="939" alt="Screenshot 2021-11-19 at 16 44 33" src="https://user-images.githubusercontent.com/87027160/142632801-498a2b0b-9f4c-4c09-898a-ccb1cf2539de.png">

Empty even if registration was successful complete in Brave
<img width="429" alt="Screenshot 2021-11-19 at 16 47 37" src="https://user-images.githubusercontent.com/87027160/142632949-d90b4c77-e18b-404c-9846-bd5935162223.png">

**Comment by redhook62** [comment]
@PsySuck 

Just one Question. 

Did you get javascript alerts (messageBox)?
Yes, if no, I think you need to check your browser settings.

Either way, when the useragent is null, you must have a form to click on. moreover at the start of your session at least one entry in the eventlog must be written.
Then, in the registration process, we must have inputs, the just going to make sure that with a null value, all the registration process proceeds normally for any device.

regards

**Comment by PsySuck** [comment]
Hello.
You are right - here is problem. 
<img width="785" alt="Screenshot 2021-11-19 at 17 39 48" src="https://user-images.githubusercontent.com/87027160/142640768-288cabba-f227-4a5a-b3fe-5b2e69166536.png">

I uncheck this option and now i am able to enroll device via safari.

**Comment by redhook62** [comment]
Hi @PsySuck 

Great !

Can you confirm me that it works now ?

regards

**Comment by PsySuck** [comment]
I can confirm - it .
Look like this setting was enabled by default in last mouth by Apple.
Can i close this ticket or you need additional info from me?

**Comment by redhook62** [comment]
Hi @PsySuck 

I am very satisfied that you can register.
Yes you can close the issue if you want.
If, you have any other questions, I would be very happy to answer them.
In the meantime, I wish you a good WE.

regards

redhook

**Comment by PsySuck** [comment]
Thank you!

**Comment by redhook62** [comment]
Hi @rtemelcea, @PsySuck 

We will be rolling out a version for the month of December.
With modifications concerning Apple devices among others.
We added properties in the WebAuthN (PowerShell) configuration.
- ForbiddenBrowsers: IE, Samsung (redirected to choose another option)
- InitiatedBrowsers: Safari (the user must click on a button to initiate registration or login ceremony)
- NoCounterBrowsers: Safari (Usage count is always 0)

You must let "Fast Login" active.
With Safari (IPhone, IPad, Desktop, ....) you must click to use FaceID or TouchID
With Chrome or others "Fast Login" must be used.

Can you give me a feedback before publication?

[adfsmfa 3.1.2112.0.zip](https://github.com/neos-sdi/adfsmfa/files/7607929/adfsmfa.3.1.2112.0.zip)

regards

redhook

**Comment by PsySuck** [comment]
Hi.
I am checking.

пт, 26 нояб. 2021 г. в 12:58, redhook ***@***.***>:

**Comment by rtemelcea** [comment]
I will check and come back with an answer by this night

**Comment by PsySuck** [comment]
I can't enroll device anymore.


пт, 26 нояб. 2021 г. в 13:15, rtemelcea ***@***.***>:

**Comment by PsySuck** [comment]
[](url)

**Comment by PsySuck** [comment]
<img width="2038" alt="Screenshot 2021-11-26 at 14 50 21" src="https://user-images.githubusercontent.com/87027160/143576864-66186667-bfac-4e8e-a39a-e3ae9e647c7f.png">

**Comment by redhook62** [comment]
have you used "Allow privacy-preserving measurement of ad effectiveness" ?
If yes try to disable it

**Comment by PsySuck** [comment]
It was disabled.

**Comment by redhook62** [comment]
Hi @PsySuck 

I just tested with your userAgent, for me everything works correctly (Registration and Logon)
The Fast Login is deactivated and offers a form with a button (your browser is Safari).
The usage counter remains at 0.

It is possible that your browser is preventing its detection. So to understand check your settings.
However, the changes we made allow you to change the behavior. so try the following after installing the latest build.

```powershell
$c = get-mfaProvider -ProviderType Biometrics
$c.InitiatedBrowsers = "safari; unknown"
$c.NoCounterBrowsers = "safari; unknown"
Set-mfaProvider -ProviderType Biometrics $c
`
regards

redhook

[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7609495/adfsmfa.zip)

**Comment by PsySuck** [comment]
`PS C:\Windows\system32> $c.NoCounterBrowsers = "safari; unknown"
'NoCounterBrowsers' is a ReadOnly property.
At line:1 char:1
+ $c.NoCounterBrowsers = "safari; unknown"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyAssignmentException`

I think fast login works even if it is disabled in GUI. I disabled it but all browser still try enroll device automatically.

**Comment by redhook62** [comment]
@PsySuck 

Yes, but you must install the latest build provided for this

[latest build](https://github.com/neos-sdi/adfsmfa/files/7609495/adfsmfa.zip)

regards

**Comment by PsySuck** [comment]
Hm.
Could you describe update procedure?

**Comment by redhook62** [comment]
Download
Uninstall your current beta version
Install this one : [adfsmfa](https://github.com/neos-sdi/adfsmfa/files/7609495/adfsmfa.zip

regards)

**Comment by PsySuck** [comment]
I checked  latest release.
I am able to change options via powershell but i can't enroll touch id in safari. This is a very strange situation - the last time I could do it. There are no such problems in other browsers.
I will resetup my test env from scratch.

**Comment by PsySuck** [comment]
Hm. I cannot enroll touchID in safari.
Did you test it on real hardware? I test 4 different macbook - same result.

**Comment by PsySuck** [comment]
I want debug it. But is it possible to enable debug log in adfsmfa?

**Comment by redhook62** [comment]
@PsySuck 

You have to deploy the solution on your development machine,
Then Attach the debugger to the ADFS process : Microsoft.IdentiyService.ServiceHost.exe.
If you are not one the same machine, you have to deploy on your adfs server the Visual Studio Remote Debugger.
Then you can put breakpoints and catch execptions

regards

**Comment by PsySuck** [comment]
@redhook62 I tried - but no success.
https://github.com/neos-sdi/adfsmfa/blob/master/Neos.IdentityServer%203.1/Neos.IdentityServer.Common/Neos.IdentityServer.MultiFactor.Utilities.cs
Could you build debug build?
and write result of usercontent  and BrowserDetection to eventlog?
<img width="1206" alt="Screenshot 2021-12-02 at 17 28 05" src="https://user-images.githubusercontent.com/87027160/144441340-12ac547c-13d3-4c4b-935f-8e8a45293646.png">

**Comment by redhook62** [comment]
Hi @PsySuck 

These tests have obviously already been carried out, by forcing in particular the useragent corresponding to Safari under Mac Os X. and everything was perfectly operational.

This is a concern related to Safari and not Mac Os X

So I will add you logs once again.
Wait for this build

regards

**Comment by redhook62** [comment]
Hi @PsySuck 

Be aware that this is functional and has been tested on IPhone and IPad

Attached is the build with debug information (EventLog)
Please refer to me any entries below 100 that you can find.

[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7643367/adfsmfa.zip)

regards

**Comment by PsySuck** [comment]
Hello.
Thank you. I did't find these event. it seems the only way is to find the problem to build and debug.

**Comment by redhook62** [comment]
Hi @PsySuck 

**You must have logs from the start of the user's session**. even before attempting a logon or registration.
The browser is detected at startup.

Have you tested with other browsers? the logs are also valid for Chrome, Edge and others.

If you don't have any logs in any case, your user may not have the right to create one. to be sure, for tests give yourself Local administrator rights.

The logs are located in EventLog / Application.

You must have logs at the start of the session.

In the JavaScript console, the Navigator properties UserAgent and Userlanguage must be accessible (no JS errors). 
there is nothing out of the ordinary required, 
so I repeat,  you must have some logs that can help us to understand.

regards

**Comment by PsySuck** [comment]
Oh. I see events if i try enroll touchID via chrome and don't see it if try safari.

**Comment by redhook62** [comment]
[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7648607/adfsmfa.zip)

Hi @PsySuck 

Ok, 

I added additional logs and a specific test for your context.
Please test this version, and send me the detailed results whether it works or not

regards

**Comment by PsySuck** [comment]
@redhook62 
I am sorry.  
I was sick.
I will test it today.

**Comment by PsySuck** [comment]
Oh.
I installed new version.
I try to login and i forgot delete my user. I used OTP and I successfully enrolled touch id in safari.
  
<img width="632" alt="Screenshot 2021-12-13 at 10 26 30" src="https://user-images.githubusercontent.com/87027160/145769983-a6af045a-7c59-444c-94a6-0b7500844604.png">

I deleted my user. Now i can't perform registration of user. Nothing in logs.

<img width="427" alt="Screenshot 2021-12-13 at 10 29 11" src="https://user-images.githubusercontent.com/87027160/145770149-77ec4fac-1bf1-43a7-93c3-da9a52589f49.png">

**Comment by redhook62** [comment]
Hi @PsySuck 

Ok, some informations.

Can you execute these steps and report all logs you can find.

Lauch Safari

- Delete your user in the adfsmfa console
- Try to Log 
- Try to register with safari
- if error Try to Regsiter with Chrome.
- After registration (with Chrome ???)
- Logon, and try to register via options with Safari.

Please all the logs.

regards

**Comment by redhook62** [comment]
Hi @PsySuck 

I have made a new build with new logs.
Please test this one quickly and report me any logs

regards
[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7703929/adfsmfa.zip)

**Comment by PsySuck** [comment]
**Delete your user in the adfsmfa console** - ok.
**Try to Log** - ok.
**Try to register with safari.** I can enroll TOTP only. In logs:

<img width="466" alt="Screenshot 2021-12-13 at 16 50 16" src="https://user-images.githubusercontent.com/87027160/145824397-77cd5fd0-98d9-42b9-ad98-fc65cdaa0dce.png">
This was last message. 

**if error Try to Regsiter with Chrome** - i am using brave and i can enroll device. In log:
<img width="427" alt="Screenshot 2021-12-13 at 16 52 41" src="https://user-images.githubusercontent.com/87027160/145824800-0eaa3fe6-14c3-4720-a7d5-9239a926758e.png">


**After registration (with Chrome ???)
Logon, and try to register via options with Safari.**
I did't logout and i can't enroll:
<img width="485" alt="Screenshot 2021-12-13 at 16 55 18" src="https://user-images.githubusercontent.com/87027160/145825187-c97a103a-12bf-4551-acb4-69356b4eef89.png">

I click logout and clear history. I am able to enroll touch id:
<img width="386" alt="Screenshot 2021-12-13 at 16 59 12" src="https://user-images.githubusercontent.com/87027160/145825898-0342bc75-c8f4-4dd9-81ca-eefd432e6dc2.png">

<img width="337" alt="Screenshot 2021-12-13 at 16 59 20" src="https://user-images.githubusercontent.com/87027160/145825864-229d3eff-66e7-496a-a462-1627698b88a2.png">

<img width="388" alt="Screenshot 2021-12-13 at 16 59 26" src="https://user-images.githubusercontent.com/87027160/145826313-d7b689cc-f055-4f63-b5ce-996ace7470e6.png">


<img width="883" alt="Screenshot 2021-12-13 at 16 59 33" src="https://user-images.githubusercontent.com/87027160/145826202-394d5ab0-9388-4963-9cef-94d354d300b2.png">

My config:
get-MFAProvider -ProviderType Biometrics


DirectLogin                 : True
Timeout                     : 60000
TimestampDriftTolerance     : **300000**
ChallengeSize               : 16
PinRequirements             : Null
UseNickNames                : True
ForbiddenBrowsers           : ie;samsung;nokia
InitiatedBrowsers           : safari;unknown
NoCounterBrowsers           : safari;unknown
Enabled                     : True
EnrollWizard                : True
ForceWizard                 : Disabled
PinRequired                 : False
IsRequired                  : True
FullQualifiedImplementation :
Parameters                  :
I tried change options - add Safari. But i got WARNING: Administration Pin Required :

**Comment by redhook62** [comment]
Hi @PsySuck 

Does the pin is required from PowerShell ? If Yes the default pin is 1230
But, it's a preview version, these behavior will be disabled by default in the next release. 
To change that with PowerShell.

```powershell
$C = Get-MFASecurity
$C.AdministrationPinEnabled = $false
Set-MFASecurity $C
```

Otherwise, very stange behavior, tell me if i'am right ? 
If another browser is registered prior, registering with safari is working ?
But Safari is well detected. we have no problems with IPads and IPhones.

Can you verify, that you have no javascript error for safari at the first registration try ?

regards

**Comment by redhook62** [comment]
Hi @PsySuck 

Here is the last iteration, I admit that if this does not solve your problem, things will remain as they are ...
There are always the logs present.
For the final release, wait a little longer. We still have some details to finalize.

Tell us if the registration works immediately with Safari, while leaving the "Fast Login" active

PS: the request for the default administration code has been disabled.

regards

[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/7707053/adfsmfa.zip)

**Comment by PsySuck** [comment]
Hi.
Thank you.
I will test it as soon as possible.

**Comment by PsySuck** [comment]
Working! I have deleted the user.
And now I can register both TOTP and TouchID in Safari in one session.
<img width="516" alt="Screenshot 2021-12-14 at 16 17 50" src="https://user-images.githubusercontent.com/87027160/146005714-70c54d17-81d5-4b15-b105-172983afd2d2.png">
<img width="872" alt="Screenshot 2021-12-14 at 16 17 41" src="https://user-images.githubusercontent.com/87027160/146005736-e11ae4c4-adf5-4a07-9ea8-2aa2ec919ec2.png">

**Comment by redhook62** [comment]
@PsySuck 

Ok, great !

Please wait for the end of the week for the release

regards

**Comment by PsySuck** [comment]
I also checked 3 different macbook - working.
Do you understand reason of this issue?

**Comment by redhook62** [comment]
Client browser was not correctly detected at startup. or was null.
So the user ceremony for Safari won't work according to the Apple's choices.
Have changed some options in Safari ? 
And, we have no macbook, so, very difficult to make tests.

Regards

**Comment by PsySuck** [comment]
Thank you very much!

**Comment by redhook62** [comment]
Version 3.1.2201.0

regards
