### ISSUE TITLE
Issue with MFA Enrollment user

### ISSUE THREAD

**Issue by kalsure** [neos-sdi/adfsmfa#205]
[Hi Support,

We installed adfsmfa.3.1.2112.0.msi package and configured MFA. It is working for users who are activated with Email and Google app.
We can not see “Enroll Authenticator App” in Options Management.

Desired scenario - Process:

The support registers or enables the MFA User and email address.

The user arrives at the OTP page, on the same page shows the options button the “Enroll Authenticator App” link. or " Enroll my authentication application"

The next page is the QR code with an explanation on how to configure your Authenticator App. User scans, click OK, and then taken back to the first OTP page where he types an OTP code from the Authenticator App and clicks Sign In.

Thank you in advance.
](![MFA-Policy](https://user-images.githubusercontent.com/7804886/146140085-6678fb4f-ff9f-4118-99ac-3d373dd930ea.PNG))

**Comment by redhook62** [comment]
Hi @kalsure 

Not very clear.

If administratively you have activated the user by assigning just an email, this is indeed the only possibility that the user will have (in effect you have registered and activated him). 
However, your users have the right to manage their options and can therefore add a TOTP code or a biometric device by choosing "Access my options after Authentication".

Now, if you want to activate the MFA of each user yourself by the support, indicate that the registration is administrative.

Also check that at the level of each provider (TOTP, MAIL, BIOMETRICS) the "Enrollement Wizard" option is active.

You can for example, not put a Wizard for the email and deactivate "the user can manage his options", while leaving active "Registration Wizard". In this case the user will not be able to modify his email.

In your configuration, the user can choose what to use by default (TOTP or Email).

regards

redhook

**Comment by redhook62** [comment]
Si issue : #13
