### ISSUE TITLE
MFA TOTP code

### ISSUE THREAD

**Issue by kalsure** [neos-sdi/adfsmfa#206]
Hi @redhook62,

I am configured MFA and Enabled Options TOTP only. It works fine for a week but now users have to enter the two times same codes.

Users are getting MFA code and entering code for signing and it is not signed a site it shows "The operation completed successfully". Again entered the same code and it get signed in successfully.

![MFA-Code-Error](https://user-images.githubusercontent.com/7804886/148020210-2bcf6e94-908f-4700-9258-bf3e79b4701c.PNG)

Verified time sync on a mobile device as well as AD FS server time. Is it required to restart any services?

Thank you in advance.

Regards

**Comment by redhook62** [comment]
Hi @kalsure 

Frankly, this TOTP module has been working fine for over 5 years.
I don't have too many ideas.

First, I will check that your servers are well synchronized with an atomic clock, as well as your devices. a time difference produces authentication errors.

If it appears after a week, this may be where it is necessary to look.

regards

**Comment by redhook62** [comment]
@kalsure 

Some news ?

**Comment by kalsure** [comment]
Hi @redhook62 

Restarted MFA services. It works. We are not getting any more errors as I said above.
But I do MFA service restart every weekend for as of now.

**Comment by redhook62** [comment]
@kalsure 

Ok, I think you don't need to restart the servers every week. To see in time.

regards

**Comment by kalsure** [comment]
Hi @redhook62

Can we get any details to stack trace into event viewer regarding this above one error "The operation completed successfully"?

If any modification to the code?
Still, we are restarting the MFA service for this issue.

Thank you.
Regards

**Comment by redhook62** [comment]
Hi @kalsure 

This type of error... "The operation completed successfully" is a Win32 error. We are going to check if we set "SetLastError = true" on the DLL imports in order to get the real exception message.

From there we can check where the error comes from.

Can you tell us how many servers in your ADFS farm?
For totp, what type of key are you using (RSA, AES, ...)?

regards

**Comment by redhook62** [comment]
Hi, @kalsure 

We completed a win32 function call to get the actual error message.
We also added the release of a mors global handle for retrieving the ADFS service SID 'adfssrv" Marshal.FreeHGlobal.

However, these functions are only used when creating processes and the system.db file (cache of security information)

You can test this build, it's the latest version.
If you want to be able to go back, you must save your configuration with Export-MFASystemConfiguration
Then please tell us the new error messages if there are any, and check if after a week the problem still occurs.

regards
[adfsmfa.zip](https://github.com/neos-sdi/adfsmfa/files/8022350/adfsmfa.zip)

**Comment by kalsure** [comment]
Thank you @redhook62 

Will check internally and get back to you.

**Comment by kalsure** [comment]
Hi @redhook62,

On this version, MFA Neos-Sdi Version: 3.1.2202.1   We are getting the same error "The operation completed successfully". 

![image](https://user-images.githubusercontent.com/7804886/173752836-49e8b6ad-bc73-4851-beaa-8ac80a32abde.png)

Kindly advise,

Thank you in advance.

**Comment by kalsure** [comment]
Hi @redhook62,

Please see the below - TOTP config.

![image](https://user-images.githubusercontent.com/7804886/173755617-232523cb-fb71-40ca-9d48-29aa24dfc8ae.png)

![image](https://user-images.githubusercontent.com/7804886/173755939-7c704fbd-8b86-4f17-8d89-3c34ffdce428.png)


We have only one ADFS farm.

**Comment by redhook62** [comment]
Hi, @kalsure 

This problem has been solved in version 3.1.2202.2 (2/14/2022)
You can try with the latest 3.1.2206.0

regards

**Comment by kalsure** [comment]
Okay. Thank you @redhook62. will try with newer version.

**Comment by kalsure** [comment]
Hi @redhook62 ,

Still, we are facing issues.  We are on MFA version latest 3.1.2206.0

![image](https://user-images.githubusercontent.com/7804886/175015384-09a04636-6e00-4f0a-9d9a-b8c74cc1855d.png)

Could you please advise if any other MFA settings or configuration-related issues?

Thank you in advance.

Regards

**Comment by kalsure** [comment]
@redhook62 ,

Sorry to ping you on this again. One more point double confirming.
While we changing on this 'Key Display Size'  is there any effect on existing MFA registered users? 
We don't want to re-register again :

Thank you.

**Comment by redhook62** [comment]
No, there will be no effects, so no need to re-register.
And if that didn't solve your problem, you can go back to 2048 bits

**Comment by derSchweiger** [comment]
@kalsure sorry to ping you here but did you solve this problem? We experience the same behaviour from time to time and haven't found a solution, nor can reproduce this issue on a constant basis.
