### ISSUE TITLE
TryEndAuthenticationError

### ISSUE THREAD

**Issue by Aniket-MFA2022** [neos-sdi/adfsmfa#207]
Hi,

Could you please have a look on the attached screenshots with errors.
We are wondering why it is giving such errors to the user.

Regards,
Aniket
![MFA Error 1](https://user-images.githubusercontent.com/97471352/148822024-20dd2aaa-05a3-42db-8a14-b171a99dc0fc.png)
![MFA Error 2](https://user-images.githubusercontent.com/97471352/148821443-357b1d71-8c1f-4ef0-bc9b-8fc26a957cc6.png)

**Comment by redhook62** [comment]
Hi @Aniket-MFA2022 

Your error is not very explicit.
Finally, your user gets kicked out immediately! ?

The MFA module needs to know the identity of the user who presents himself, to do this there must be a specific claim presented. the default claim is the UPN (userPrincipalName): **http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn**
all of this is shown here:
[identity claim](https://github.com/neos-sdi/adfsmfa/wiki/01-Installation#identity-claim)
and here
[activating product](https://github.com/neos-sdi/adfsmfa/wiki/01-Installation#activating-product)

You must therefore make sure that your user has a userPrincipalName property of entered in your active directory and that this claim is produced by the RL of your ADFS.

The adfsmfa product can as indicated in the documentation use the WindowsAccountName. the use of email (although in all 3-ball demos) is not good practice and is proscitized in ADFSMFA.

Please check all these points.

regards

**Comment by redhook62** [comment]
Some News ?
