### ISSUE TITLE
Mail sending issue on clustered node 2/2

### ISSUE THREAD

**Issue by klpo-mt** [neos-sdi/adfsmfa#210]
Hi again @redhook62,

we are currently facing an issue when it comes to sending emails from our secondary ADFS node. I wonder whether you have an idea on this.

Here's the gist from the eventlog:
```
Error Sending Email (TOTP) for user email.user@xy.com with status code GeneralFailure : Fehler beim Senden von Mail.  (translated: "sending mail failed")
 
PostAuthenticationRequest Error email.user@xy.com 
 Fehler beim Senden von Mail. 
    bei Neos.IdentityServer.MultiFactor.MailUtilities.SendOTPByEmail(String to, String upn, String code, MailProvider mail, CultureInfo culture)
   bei Neos.IdentityServer.MultiFactor.Utilities.GetEmailOTP(AuthenticationContext ctx, MailProvider mail, CultureInfo culture)
   bei Neos.IdentityServer.MultiFactor.Common.NeosMailProvider.PostAuthenticationRequest(AuthenticationContext ctx)
   bei Neos.IdentityServer.MultiFactor.AuthenticationProvider.PostAuthenticationRequest(AuthenticationContext usercontext, PreferredMethod method)

MailSlot Client Write Error (MGT) :Das System kann die angegebene Datei nicht finden (translated: "file not found")
Xml Serialization error : Unknow Node : RequireValidAttestationRoot Position (47, 204)
MailSlot Client Write Error (MGT) :Das System kann die angegebene Datei nicht finden
```

We observed it during self-registration of a new user. Sending the mail with the confirmation code fails and registration aborts. That happens when routed over cluster node 2 but succeeds when forcibly routed over node 1.

The ADFS MFA version in use is 3.1.2110.0. We updated from 3.0.2008.0 mid October and suspect that the issue was introduced there. We have many registered users, it surely was working at some point before.

So far we tried reinstalling the same version over again, to no avail.
Perhaps some sort of config sync went bad in our setup, between the two nodes?

Btw.: We are happily using your solution since quite a while now (TOTP and email as fallback). Thanks a lot for that, hope you are doing fine.

Best,
Klaus

**Comment by redhook62** [comment]
hi @klpo-mt 

I think you have 2/3 separate issues.

For the MGT mailslot, in principle, it suffices to restart the "mfanotifhub" service to fully reset the services on the server concerned. (to be done last).

For the xml serailization error part, even if a message is displayed in principle it is managed, with a default value. the MFA configuration of your second server is not up to date. 
When saving the configuration (PS or MMC), it is updated automatically, the caches are also updated on all the servers of the farm.
What type of ADFS configuration are you in? : WID or SQL Server? Have you added a server to your ADFS farm?

For emails, do you use a "Custom" template made by you ? and normally deployed on each server in the C:\ProgramFiles\MFA\MailTemplates\LCID directory. 
Please ensure in this case that the same files are deployed on each server. The initial creation of email templates is done with the cmdLet **Export-MFAMailTemplates**.

To make sure your servers are communicating properly.
On each Server:
- delete the **blob.db**, **config.db**, **system.db** files located in the C:\ProgramFiles\MFA\Config directory.
- on the main server restart the "mfanotifhub" service (with PS : restart-service mfanotifhub) 
- Check that the deleted files are correctly recreated.
Perform the same operations on the secondary server

Please give me feedback on these operations.

regards

**Comment by klpo-mt** [comment]
We schedule these experiments for a low-activity day, I will get back to you.
Regarding the configuration questions:
- WID
- two nodes in the farm, from day one. no nodes added since
- No custom template

Thanks a lot so far

**Comment by klpo-mt** [comment]
We tried your suggestion to delete the configs and have them recreated. That went well.
There were differences in filesize before which are gone after triggering the resync. Not sure what caused this, we still suspect a glitch somehow related to updating, but now its all green again.

Thanks a lot!
