### ISSUE TITLE
Email Multi-Factor Provider - display name of the e-mail address

### ISSUE THREAD

**Issue by JustITPL** [neos-sdi/adfsmfa#214]
Hi,

I have little problem with the display name of the e-mail address. I can change it via powershell (and it’s work fine), but after that I can't change other settings in mmc console.
![image](https://user-images.githubusercontent.com/78961810/153598860-e763d895-1af1-47a3-be94-5372b608b2af.png)

![image](https://user-images.githubusercontent.com/78961810/153599284-f535e700-03c4-4139-a047-91b66c901361.png)

**Comment by redhook62** [comment]
Hi, @JustITPL 

To be sure ?
Administrative contact (**from**) must be a valid email address. this value is the sender of the email.
It should be : **mfatest@example.com** and not   **"MFA <mfatest@example.com>"**

regards

**Comment by JustITPL** [comment]
Yes I'm sure. Take a look at your email headers (From). This is how e-mail systems work.
In my Outlook:
![image](https://user-images.githubusercontent.com/78961810/153603431-6f0847e3-862e-4b8c-9889-61e4dd2860c6.png)
![image](https://user-images.githubusercontent.com/78961810/153603450-da99c88b-5534-4865-9a75-0688bf47d54b.png)

**Comment by redhook62** [comment]
Yes, but the smtp client is not Outlook, it must be an email in the format I told you. not a display format of any mail client.
In PowerShell, the check is not done, it will be added soon.

When receiving the mail in outlook, it may be presented as in your example. but in reality it requires a properly formatted email.

regards

**Comment by JustITPL** [comment]
Ok, then how to change sender display name in MFA?

**Comment by redhook62** [comment]
@JustITPL 

I will look at this for the next version (March). Time to do the necessary tests.

regards

**Comment by redhook62** [comment]
@JustITPL 

Done in last version (3.1.2202.2).
Yes, DisplayName is a property of SMTP address (MailAddress class), but no parsing exists. So it an enhancement...
You can apply this on administrative mail addresses and on users's mail addresses.

regards

redhook

**Comment by JustITPL** [comment]
Thank You :)
