### ISSUE TITLE
Error: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by xymsayly** [neos-sdi/adfsmfa#215]
hello ,team
    I upgraded adfsmfa from version 2.4 to the latest 3.1.2202.2.I can not authticate with authentication application,and I get  the following error: Object reference not set to an instance of an object.
![image](https://user-images.githubusercontent.com/34665997/154217634-fd51d6ee-9add-446d-8296-1dc544a10467.png)

It works well,when i use  email to receive code.How should I troubleshoot the error, thanks

**Comment by redhook62** [comment]
Hi @xymsayly 

Oh, version 2.4 is not recent...
Did you follow the Wiki to upgrade from an older version?

There is definitely a problem with your user(s) key.
First, using the console, renew the user's TOTP key and scan it. then test a connection again.
Next, export your configuration using Export-MFASystemConfiguration. edit the file and remove sensitive info. then mail me this file.

regards

**Comment by xymsayly** [comment]
I get the following error message in windows events：
[-](https://github.com/neos-sdi/adfsmfa/issues/215#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/neos-sdi/adfsmfa/issues/215#) <System>
  <Provider Name="ADFS MFA Service" /> 
  <EventID Qualifiers="0">900</EventID> 
  <Level>2</Level> 
  <Task>0</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2022-05-27T02:19:01.304985300Z" /> 
  <EventRecordID>446792</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer><computer_name></Computer> 
  <Security /> 
  </System>
[-](https://github.com/neos-sdi/adfsmfa/issues/215#) <EventData>
  <Data>AuthenticationProvider:TryEndAuthentication Error : Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: <user_name> : at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryLocking(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims) at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)</Data> 
  </EventData>
  </Event>
