### ISSUE TITLE
Error:- The security ID structure is invalid

### ISSUE THREAD

**Issue by AniketMeshram** [neos-sdi/adfsmfa#216]
Hi Team,

When i am login to the server with Administrator account it is not loading the MMC Console and throwing the subjected error.
But when i am login through my domain credentials then the MMC console is working fine.
Please let me know what needs to be done here.
![MFA Error16-02-2022](https://user-images.githubusercontent.com/99792318/154220150-8fab4377-f873-4838-b2a7-8ad8cd85052e.JPG)

**Comment by redhook62** [comment]
Hi @AniketMeshram 

It is a Windows Server system problem.
There are several possibilities.
- Check that the local administrator account is not a member of too many windows groups
- that the name of the administrator has been renamed: type whoami.

It's really very broad, but it has to happen when retrieving ACL. Check anyway that in the ADFS console, you have authorized management by Local Administrators, moreover with this local account can you perform operations in the ADFS console?

Don't forget, to always check in the eventlog of the machines to obtain the detailed error messages.

regards
