### ISSUE TITLE
Getting an error 

### ISSUE THREAD

**Issue by ukandy** [neos-sdi/adfsmfa#22]
Hi, i am trying to get this working in my lab environment but am getting an error when attempting to log on to a web site through the ADFS

the event log says the following 

Error on authentication process ! 
The type initializer for 'Neos.IdentityServer.MultiFactor.Data.DataLog' threw an exception.

ADFS Web page gives the following error

For security reasons, we require additional information to verify your account (test1@xxx.co.uk)
An error occurred
An error occurred. Contact your administrator for more information.

ADFS is runing on Server 2016 (all updates applied)
the config for the MFA is:

RefreshScan          : 3000
DeliveryWindow       : 300
TOTPShadows          : 2
MailEnabled          : False
SMSEnabled           : False
AppsEnabled          : True
Algorithm            : SHA1
Issuer               : xxxxx Corp
UseActiveDirectory   : True
CustomUpdatePassword : True
DefaultCountryCode   : gb
AdminContact         : adminmfa@contoso.com
UserFeatures         : AllowUnRegistered, AllowDisabled, AllowChangePassword, AllowManageOptions
AdvertisingDays      : Neos.IdentityServer.MultiFactor.ConfigAdvertising

i have a user registered in the system 

ID              : 4befb94e-4da6-4772-8826-9900cf4aaa
UPN             : test1@xxx.co.uk
MailAddress     : test1@xxx.co.uk
PhoneNumber     : 1234
Enabled         : True
CreationDate    : 13/07/2018 12:00:40
PreferredMethod : Code

Are you able to give me some pointers on where to look to find out whats wrong

thanks in advance 

Andy

**Comment by redhook62** [comment]
Hi, Andy

Your error seems to be related to an access denied for writing to the system eventlog.
The eventlog has not been correctly registered.
We are going to change this behavior in version 2.2

You can see this issue : https://github.com/neos-sdi/adfsmfa/issues/17

Give local admin rights to your ADFS account and restart all the services.
You can remove your ADFS account after if everything is Ok.

Remember that some features require that the interactive account (MMC and PS) as local admin rights, for example when creating Certificates, ... 

Regards

**Comment by ukandy** [comment]
Thanks loads for the response, adding the service account to the local admin didnt work however adding the service account to domain admins did and i was able to get it to work

i am now going to try the  beta

thanks again

Andy
