### ISSUE TITLE
Error after MFA code "cannot find object or property adfs"

### ISSUE THREAD

**Issue by AmeerErg** [neos-sdi/adfsmfa#221]
Dears,

Could you please help me or if you have any ideas regarding this issue.

After entering the code this error appear "cannot find object or property adfs".

Thank you

**Comment by redhook62** [comment]
Hi @AmeerErg 

This is not an error in adfsmfa a priori. but rather during the production of the token.
Are your claims or NameID if SAML correct?
Without more information difficult to move forward.
Look at the ADFS and Application EventLogs

regards

**Comment by AmeerErg** [comment]
Dear @redhook62,

Thank you for replying, the issue has been fixed by updating the server.
It seems that Microsoft update for Feb had a bug and was fixed in this month update.

Really appreciate your usual support.

Best Regards
