### ISSUE TITLE
Questions about UX

### ISSUE THREAD

**Issue by PsySuck** [neos-sdi/adfsmfa#222]
Hi @redhook62.
I have a few questions about UX.
1. Is it possible activate MFA provider, but not show enrolment wizard when the user enroll 2fa for the first time.?

I have configured settings for "biometric":
`Get-MFAProvider -ProviderType biometric`
`DirectLogin                 : True`
`Timeout                     : 60000`
`TimestampDriftTolerance     : 300000`
`ChallengeSize               : 16`
`ServerDomain                : *****`
`ServerName                  : *****`
`ServerIcon                  :`
`Origin                      : *****`
`PinRequirements             : Null`
`UseNickNames                : True`
`ForbiddenBrowsers           : ie;samsung;nokia`
`InitiatedBrowsers           : safari;unknown`
`NoCounterBrowsers           : safari;unknown`
`Enabled                     : True`
`EnrollWizard                : False`
`ForceWizard                 : Disabled`
`PinRequired                 : False`
`IsRequired                  : False`
`FullQualifiedImplementation :
`Parameters           :`
i can only ignore wizard:
<img width="366" alt="Screenshot 2022-03-21 at 09 17 04" src="https://user-images.githubusercontent.com/87027160/159213298-37ecce4f-fd68-4853-822b-c5e9a9ad5a8d.png">

2. I know that changing this screen is not allowed - for security reasons, but for MacOS users it is not obvious that you need to click the 
button. Is it possible to change the text on the button or remove text `Touch or Scan with your biometric device`?
<img width="417" alt="Screenshot 2022-03-21 at 09 26 15" src="https://user-images.githubusercontent.com/87027160/159213935-f1657c70-bed7-42e5-b9c9-8615307dd0a3.png">

**Comment by redhook62** [comment]
Hi, @PsySuck 

Yes, it is possible to add a property on each supplier allowing the exclusion of this one during the registration or registration phase.

Change the text below the button, OK.
"To register your biometric device, click below"

regards

**Comment by PsySuck** [comment]
Thank you!

**Comment by redhook62** [comment]
Done in 3.1.2204.0

regards
