### ISSUE TITLE
A Valid digital key is required to generate TOTP codes to calidate your identity!

### ISSUE THREAD

**Issue by fMaen** [neos-sdi/adfsmfa#227]
Hi, 

i´m wihtin the setup of ADFSMFA for MFA with TOTP app (Microsoft Authenticator).
I have imported users vom AD and set "Code" as method with PowerShell: 
`Import-MFAUsersADDS -LDAPPath "OU=Users,OU=TestCORP,DC=test,DC=lab" -Method Code`

Users get added successfully with method Code.
But at first logon, the user gets prompted for an authentication app code, even though the app was never registered.

![image](https://user-images.githubusercontent.com/104152353/164486694-5bb995d8-bb60-4e44-a120-f94979d0ad7c.png)

The user has no TOTP key set:
![image](https://user-images.githubusercontent.com/104152353/164486841-bae3c58c-99d6-4a21-944e-838d23a6de7e.png)

Settings:
![image](https://user-images.githubusercontent.com/104152353/164487289-aa32941a-ca18-4a60-b3f2-5777f7908dbc.png)

![image](https://user-images.githubusercontent.com/104152353/164486971-bc8824a3-690a-420a-b4fa-726c57604e4c.png)

![image](https://user-images.githubusercontent.com/104152353/164487048-e0be6576-233c-48ad-85e0-17706f1c201d.png)

![image](https://user-images.githubusercontent.com/104152353/164487103-b1ac7a29-e9d3-419e-80d4-4f0b9aeafb99.png)

Installed version is adfsmfa.3.1.2204.1
Any ideas why the user is not promted to register the authenticator app?

**Comment by redhook62** [comment]
Take a good look at the different parameters of these commands, you can indicate that you do not want to generate a key.

delete your user, and re-import.

If you do not specify not to generate a key, a random one will be created, and the user will be considered registered.

Last thing, why are you importing users when it says in your settings that they have to register themselves....
