### ISSUE TITLE
Input string was not in a correct format

### ISSUE THREAD

**Issue by TerrierX** [neos-sdi/adfsmfa#230]
Hi guys,

We tried the new Build : 3.1.2205.0 - New Installation and we faced the following issue:
![2022-05-03 09_35_33-](https://user-images.githubusercontent.com/62567463/167782783-ad590948-b738-4465-b9d1-e3ed14d60c85.png)

After that the console crashed:
![2022-05-03 09_35_53-](https://user-images.githubusercontent.com/62567463/167782853-9c455c60-d0e1-4877-9aaf-e6f968d0e185.png)

Not sure if it was only an issue on our site, afterwards we installed the Build: 3.1.2204.1 and everything worked fine.

Regards,
Dominik

**Comment by redhook62** [comment]
Hi, @TerrierX 

I just tested, I have no problem. warning or error messages are displayed correctly.
Tried several languages, no problems either.

Are you using the same configuration as for version 3.1.2204.1 ?
Did the uninstall and then the install go well ?
Have you saved the config (save in mmc) to take into account the changes ?

Can you put a screenshot for "Global Parameters", "MFA Providers" ?

regards

**Comment by TerrierX** [comment]
Hello redhook,

Thank you for your quick reply.

No issues during the uninstall and the install.
I uninstalled version 3.1.2204.1 now and updated/installed the new version 3.1.2205.0 again.

Now everything works as expected, I guess it was an configuration issue (but not sure what we had configured, will save it next time) or something else in our environment. 

regards,
Dominik
