### ISSUE TITLE
Error in exporting MFA configuration

### ISSUE THREAD

**Issue by Aniket-MFA2022** [neos-sdi/adfsmfa#232]
Hi Redhook,

Thanks for your lovely product, I have been using since January.
I wanted to get a back of my current configuration but facing some issues in it as the command is not working.
Please see the screenshot attached and the commands used to get the backup.
Please have a look and let me know what could be the reason.
![MFA Configuration Export Error](https://user-images.githubusercontent.com/97471352/172143918-5249f5a3-760a-47bb-aaa9-62ad6b69b397.png)

get-help Export-MFAConfiguration –detailed
get-help Import-MFAConfiguration –detailed
Export-MFAConfiguration -ExportFilePath 'c\temp\config.xml'
Import-MFAConfiguration -ImportFilePath 'c\temp\config.xml'

**Comment by redhook62** [comment]
Hi, @Aniket-MFA2022 

get-help **Import-MFASystemConfiguration** -detailed
get-help **Export-MFASystemConfiguration** -detailed

**Export-MFASystemConfiguration** -ExportFilePath 'c\temp\config.xml'
**Import-MFASystemConfiguration** -ImportFilePath 'c\temp\config.xml'

Regards

**Comment by redhook62** [comment]
Hi, @Aniket-MFA2022 

Yes, the bu is confirmed.
While waiting for the next release at the end of June, you can use this command to extract your configuration

**export-AdfsAuthenticationProviderConfigurationData -Name "MultifactorAuthenticationProvider" -FilePath c:\temp\mfa\3.1.xml**

For the import procedure there is no problem

regards

**Comment by redhook62** [comment]
Hi @Aniket-MFA2022 

Done in version 3.1.2206.0

regards
