### ISSUE TITLE
neos-sdi adfsmfa is opensource product? have a limit for users?

### ISSUE THREAD

**Issue by arpsyapathy** [neos-sdi/adfsmfa#236]
Hi!

I'm looking for a mfa solution for adfs. Found this solution.
neos-sdi adfsmfa is opensource product? have a limit for users?
If it's not open source, what's the price?

Thank you advanced

**Comment by redhook62** [comment]
Hi,
Yes, it's an opensource project.
No, limit for number of users

Regards
