### ISSUE TITLE
2.2.0.20 - Adjustment on "Disallow manage my options"

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#24]
Hi,
Thank you for the feature "Disallow manage my options". We like that!
One more small thing on that. Would it be possible to also remove the option "Remember my selection" (on the "How do you want to receive you code?" page) when you select "Disallow manage my options" (or an additional check box)? Users could by mistake click that one, and will then be prompted for a code from email instead of TOTP.

Thank you for your nice work!

Andreas

**Comment by redhook62** [comment]
Hi,

Yes, with additionnal checkbox.

Regards

**Comment by redhook62** [comment]
Implemented in version 2.2.0.22
