### ISSUE TITLE
Email Provider "Culture is not supported"

### ISSUE THREAD

**Issue by patschi** [neos-sdi/adfsmfa#241]
Just a quick report on an error I've seen through my tests today. When logging into ADFS and selecting email provider, the following error appears (the option `Use browser languages` is enabled):
```
Culture is not supported. Parameter name: culture 4096 (0x1000) is an invalid culture identifier.
```

After this error no login is possible and Email provider can not be used successfully.

When disabling above setting:
![image](https://user-images.githubusercontent.com/2029878/180629850-221ef631-44c5-4d0f-9011-5031e03d29b7.png)

The error disappears and login does work without any other changes.

Env: Using ADFS 2019 and adfsmfa 3.1.2207.0.

**Comment by redhook62** [comment]
Hi,

As you can see here : [Localization](https://github.com/neos-sdi/adfsmfa/wiki/11-Localization), the culture 4096 is not supported by ADFS, and not supported by MFA.
You can switch to pt (2070)

regards

**Comment by patschi** [comment]
I don't know why ADFSMFA picked this language, as my device and browser language is set to English and I don't speak PT at all. But beside the language not being supported, it should not cause the authentication completely to fail and maybe lock out users. I think there should be some kind of fallback to e.g. English?
