### ISSUE TITLE
Not able to Install MFA on new AD FS Server.

### ISSUE THREAD

**Issue by Aniket-MFA2022** [neos-sdi/adfsmfa#243]
Hello Redhook,

I am trying to install MFA on a new AD FS Server but MFA is not registering on it.
I followed below Steps.
1) Took Backup of current AD FS Configuration via "ADFSRapidRecreationTool" from Production Server.
2) Launch a new Server and restored this Backup in this Server via "ADFSRapidRecreationTool"
3) It gave me warning when the backup was restored successfully.
4) When i try to register MFA it says "Register-MFASystem : An authentication provider with identifier 'MultiFactorAuthenticationProvider' is already present in the policy store.  Identifiers must be unique."
5) It gets successfully unregister but throws error at the time of registration.

Attaching screenshots for your reference.

PS:- I have done the same setup earlier on other servers or created Replica server by this procedure.

MFA Version:- adfsmfa.3.1.2206.0
![MFA Registration Error](https://user-images.githubusercontent.com/97471352/182291439-6d97f6d1-0600-41d0-b5d1-6adcd95c244b.png)
![MFA Warning after Restoration](https://user-images.githubusercontent.com/97471352/182291446-2920e700-e338-4c91-85fd-a5b6bafcff66.png)

**Comment by Aniket-MFA2022** [comment]
Any update on this?

**Comment by redhook62** [comment]
Hi @Aniket-MFA2022 

In the first place.
Have you changed servers ? 
Does the component seem registered? 
Therefore normal that you could not execute Register-MFASytem.

So you should be able to export the current configuration with **Export-MFASystemConfiguration.**

Next, modify the configuration file, and replace the name of the servers (FQDN) with those you have newly installed.

Also change all the passwords contained, they are encrypted, and for your security, these use an RSA or AES key present on each server (that Microsoft cannot recover except to physically access your machines...). To modify the passwords, replace them in clear text, they will then be encrypted.

Reapply, your modified configuration with **Import-MFASystemConfiguration**.

On the other hand, it would have been desirable to use Unregister-MFASytem, ​​then Register-MFAsystem and to fill in all the elements necessary for your configuration (especially if you have changed the ADDS Forest...)

regards

redhook

(I'm on vacation, with limited internet access)

**Comment by Aniket-MFA2022** [comment]
Hi redhook,

The servers are not changed. we have done this before many times and it was successful.
All the settings are correct but still it is not registering the MFA.
Errors shown in above screenshots are appearing.
The component is not registered. When i run Register-MFASystems command it doesn't register.
But when i unregister it, it gets successfully unregister.
we have done the same setup on Staging environment few days back and we were able to register MFA successfully.

Please let us know where else we can troubleshoot.

**Comment by redhook62** [comment]
Hi,

First, make sure the component is dereferenced.
In PowerShell use ADFS Cmdlets.
**UnRegister-AdfsAuthenticationProvider -Name "MultiFactorAuthenticationProvider"**.
Then register the component again with **Register-MFASystem** or **Register-MFASystem -Nonewkey**
If you are unable to do this, then this is a problem with restoring configuration or rights with Windows 2022.

regards

**Comment by redhook62** [comment]
Some news ???
