### ISSUE TITLE
Help in starting

### ISSUE THREAD

**Issue by EBG-DEV** [neos-sdi/adfsmfa#245]
Hello,

I have followed tutorial and installed adfsmfa in testlab.

However I'm stuck at next steps.

I want to use Google Authenticator for TOTP.

Any tips in next steps or any document where I could look up basic setup?

E.

**Comment by redhook62** [comment]
It is necessary to look at the whole wiki.
- 05 General settings
- 06 Data Storage (optional)
- 07 Security
- 08X Providers

Indicate the required elements, for the other options, it all depends on your needs.

regards
