### ISSUE TITLE
The code got by scanning the code and entering Security Key is different

### ISSUE THREAD

**Issue by xymsayly** [neos-sdi/adfsmfa#247]
hello，team
    The code obtained by entering the Security Key is different from that obtained by scanning the code.Is it a bug?
    

Version:  3.1.2207.0

**Comment by redhook62** [comment]
Can you give more background information?
Are you talking about Code for a security key (Yubico Security Key 4 for example?) or TOTP code, or additional pin code?
Your request is not understandable.

team
