### ISSUE TITLE
MFA suspension option not being shown by default

### ISSUE THREAD

**Issue by neilmcd** [neos-sdi/adfsmfa#250]
The 'Stop being asked for 7 days' option is not displayed unless 'Access my options after authentication' is selected on ADFS 2016.

### Discussed in https://github.com/neos-sdi/adfsmfa/discussions/249

**Comment by redhook62** [comment]
Hi @neilmcd 

You will find attached the version scheduled for october.

This will solve this issue.
There was a bug, the only correct function was with biometrics, so it worked badly with TOTP and emails.

Please, if you don't find another problem, close this issue. 
this build will be public this friday

regards

redhook
[adfsmfa 3.1.2210.0.zip.txt](https://github.com/neos-sdi/adfsmfa/files/9659577/adfsmfa.3.1.2210.0.zip.txt)

**Comment by neilmcd** [comment]
Thank you, this has fixed my issue.

**Comment by redhook62** [comment]
The release version 3.1.2210.0 is available.
It is better to collect it because there are some other improvements
