### ISSUE TITLE
Override=NULL on new user enrollment crashes MMC console

### ISSUE THREAD

**Issue by k-korn** [neos-sdi/adfsmfa#26]
MFA setup:
- adfsmfa ver. 2.2.0.22 beta
- Windows Server 2016, MFA user data is stored in SQL database.
- User registration is enabled, they can self-register.
- E-mail and TOTP auth methods are enabled.

When new user registers for MFA, the following happens:
- User is prompted for e-mail, verifies email.
- User is prompted for TOTP app enrollment, QR code is shown.
- User scans QR code to enroll TOTP.
- To verify TOTP, OTP is requested from user
- Once valid OTP code is provided, user receives an error page.
- In Event Log, the error text is: "Data is Null. This method or property cannot be called on Null values."
- MMC console's Users management tab now also fails to open, with similar error.

If you check SQL data at this point, it can be seen that "OVERRIDE" column is set to NULL value, which is (probably) not expected by other parts of the app:
![image](https://user-images.githubusercontent.com/20152583/43264617-5086945c-90ef-11e8-9eb0-6c4355a9795d.png)

It may be related to the following code:
https://github.com/neos-sdi/adfsmfa/blob/72cdaf05214b13361e9952e3eeecf3ce90df0cb0/Neos.IdentityServer%202.2/Neos.IdentityServer.MutltiFactor.Data/Neos.IdentityServer.MultiFactor.SQLServer.cs#L861

**Comment by redhook62** [comment]
Hi

Thank you, But i can't reproduce your problem. Can you be more precise ?
- OTP enrollment by "Manage my options" or "Enroll my device" ?
- User is new User or Not.
- What are Security Options (RNG, RSA, CUSTOM)

The OVERRIDE column accepts NULL values. 
Perhaps the SECRETKEY is NULL ?

It seems, that the SQL table REGISTRATIONS have  an older version, CREATIONDATE column have been removed. See MFA-DB.sql.

Regards

**Comment by k-korn** [comment]
- OTP enrollment by "Manage my options"
- User is a new user
- Security options: default for new install, 
![image](https://user-images.githubusercontent.com/20152583/43342558-bef1b88e-91eb-11e8-85f0-753efae5b7c2.png)
- As for DB schema, there is a "Create MFA database" button on SQLServer configuration, database has been populated with it. 


Also, version 2.0.22.1 fixes the issue.
Many thanks!
