### ISSUE TITLE
Cannot add code MFA for user

### ISSUE THREAD

**Issue by marcdieters** [neos-sdi/adfsmfa#267]
Hello,

I'm trying to setup ADFSMFA. I installed the msi (adfsmfa.3.1.2211.0), registered the system and server.
Then I opened the MFA MMC and enabled only the TOTP option and selected the mixed security policy.

For my relying party trust, I selected everyone with MFA.

When I sign in, I get the option to register an authenticator application. I scan the QR code and click continue. 
On this screen I enter the code shown in google authenticator.

Then I get this:
![image](https://user-images.githubusercontent.com/24914093/203925875-b4dfe6a4-3f74-4d00-b0ad-65e1a16b9d31.png)

Can you please assist with this ? I have no clue where to look for next.

Thanks !

**Comment by redhook62** [comment]
Hello,

Make sure that your servers are well synchronized on an NTP pool, indeed TOTP is partly based on time.

On the other hand, do not change the number of digits required, as well as the duration for the generation of the code. Google Authenticator, Microsoft Authenticator do not fully implement the RFC.
Only Authy and Aegis authenticator apps handle this without issue. 
So stay on 6 digits and 30 seconds.

regards

**Comment by marcdieters** [comment]
Hi,

Thanks for the quick reply. I didn't realize that my LAB DC's were running one hour behind. I fixed that and now it's working perfectly.

Awesome thing you've build here !
