### ISSUE TITLE
Web enroll MFA does not validate phone number

### ISSUE THREAD

**Issue by rahmanny** [neos-sdi/adfsmfa#268]
I am using a custom external provider to send sms. The problem is that users can enter a phone number with an error (an extra digit or not enough) or in the wrong format (our SMS provider requires a format with +) and MFA does not check for this.
For example, I enter 1234 
![image](https://user-images.githubusercontent.com/33230449/204489211-72de0277-c4c2-43db-b265-55a7292c4b91.png)
MFA is trying to send SMS to this number
![image](https://user-images.githubusercontent.com/33230449/204489412-fcc2a242-478a-4be6-a847-53157da6c394.png)
I tried checking the phone number in the PostAuthenticationRequest method, I created a method that checks if the number satisfies our requirements:
```
public override int PostAuthenticationRequest(AuthenticationContext ctx)
        {         
            if (ctx.UIMode == ProviderPageMode.EnrollPhone &&
                PhoneNumberValidator.ValidatePhoneNumber(ctx.PhoneNumber) == false)
            {
                throw new Exception("Phone number format is invalid");
            }
...
```
But in this case, MFA gives a default error:
![image](https://user-images.githubusercontent.com/33230449/204490411-48b9cc09-8e66-4169-9826-657ece4cbcb7.png)
Is it possible to send an error message from the External Provider so that the user can see that he has entered incorrectly?

**Comment by redhook62** [comment]
Hi,

the validation is done : Your account is not validated !. 
it's up to the user to enter your phone correctly, 
Why ? because it's too complex and too messy to do it with javascript (Hoo! the international phone...)

It's the library LibPhoneNumber which does the verification, refer to its documentation.

We will not make any changes in this direction, 

moreover we do not recommend to rely on the phone, too insecure.

regards

**Comment by rahmanny** [comment]
Hi,
I really understand why you didn't implement it. I have a question in another, when throwing an exception in my custom external provider
`throw new Exception("Phone number format is invalid")`
Can this message be displayed in the MFA web form instead of the default "Your account is not validated"? Within my process, I can throw exceptions with a more informative message for each type of error.

**Comment by redhook62** [comment]
Hi,

Yes, I understand that you want to do something "user friendly", 
however, for confidentiality reasons and to avoid giving information, we never display the details of errors.

So, to take into account the requests of your users... (also not sure that they understand the message displayed by you...)
In a future version, we will add events on validation and errors dispatch. 
Don't expect this development until next year.

regards
