### ISSUE TITLE
2.2 TOTP enrollment wizard 

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#27]
Thanks for new versions, I will test after my vacation.
One more thing came to my mind. Would it be possible to have options on which TOTP Apps that are displayed in the TOTP enrollment wizard? (Maybe you want to direct your users to only use the Microsoft App for example.)

Andreas

**Comment by redhook62** [comment]
Yes, but just showing/hiding existing links, 
because, these links are part of the solution. we cannot rely on external ressouces for security reasons

**Comment by redhook62** [comment]
Done in version 2.2.0.25
