### ISSUE TITLE
Problem with turning on MFA

### ISSUE THREAD

**Issue by jendru** [neos-sdi/adfsmfa#270]
Hi guys,
I have an issue with your plugin. Seems the installation went fast and without issues but when i enable access policy for a test system to require MFA i get the below page. Any idea what I have configured wrong? Not sure what logs or details to provide with this.
![image](https://user-images.githubusercontent.com/19305194/206037948-e8730bb6-9b42-47be-aae5-a027e89f9573.png)

**Comment by redhook62** [comment]
Everything is OK ?
