### ISSUE TITLE
Unable to get ADFS MFA to initialize

### ISSUE THREAD

**Issue by nick-bogle** [neos-sdi/adfsmfa#272]
Fresh install of ADFS MFA, followed the installation guide to a tee. 

Using Windows Server 2022, Active Directory storage with ADDS Schema 2012 settings, Data Access Account that is a Domain Administrator, and TOTP and Email as the only enabled provider. Tried on two different fresh ADFS installs with the same result. Running Version 3.1.2212.0

MFA Configuration Status showing Initialized: True and Active: True, however, I am getting this in the ADFS Event Logs every time you restart the ADFS services. 

`An error occurred loading an authentication provider. Fix configuration errors using PowerShell cmdlets and restart the Federation Service. 
Identifier: MultiFactorAuthenticationProvider 
Context: Passive protocol pipeline 

Additional Data 
Exception details: 
An error occurred initializing the 'MultiFactorAuthenticationProvider' authentication provider.`

Any ideas/anywhere I can look for more detailed debugging logs?

**Comment by redhook62** [comment]
Hi @nick-bogle 

The adfsmfa logs are in the Eventlog Application.
Can you take a look and send them to us.

regards
