### ISSUE TITLE
Your account is not validated !

### ISSUE THREAD

**Issue by pdaccache** [neos-sdi/adfsmfa#275]
Dears,
I am receiving the below error after i try to register a device, once i add the OTP i receive the below.
Your account is not validated !
You can try the operation again by selecting "Previous".

What should i do? even if i import the user manually, when i add the OTP it fails please help.

**Comment by redhook62** [comment]
Hi @pdaccache 

Yes, the code entered is invalid.
Check 2 things
- That the mouse cursor is not on the QRCode
- That your ADFS servers are well synchronized with an atomic ntp, for example pool.ntp.org

regards

**Comment by pdaccache** [comment]
i was able to bypass the OTP part, once i click to continue it asks to enroll your email address and once i add my email address it give an error your account is not validated.

**Comment by redhook62** [comment]
Apparently you also want to use the MFA by email, if this is not the case deactivate the Provider concerned.

Look for any messages in the eventlog. have you configured the SMTP part.

Please check all these settings.

**Comment by pdaccache** [comment]
I didn't find where i can configure SMTP in the snap in, but once i disabled the email option it worked with OTP only.
thanks man and appreciate if u can help me configure the SMTP part.

**Comment by redhook62** [comment]
very well,

Have you looked at the wiki?

For the email settings, this is on the email provider as indicated here: [Email setting](https://github.com/neos-sdi/adfsmfa/wiki/08C-MFA%20Email%20Provider)
