### ISSUE TITLE
Error:The authentication method MultiFactorAuthenticationProvider could not be loaded

### ISSUE THREAD

**Issue by jasemohammadi** [neos-sdi/adfsmfa#282]
hi there
I solved the project's errors and created all files of .pfx by the RSA1 key  in all class libraries then set "publickey" in all assembly classes.
I got this error after run command "register-MFAsystem" in powershell :
--------------------------------
Register-MFASystem : The authentication method MultiFactorAuthenticationProvider could not be loaded. Could not load
file or assembly 'Neos.IdentityServer.MultiFactor, Version=3.0.0.0, Culture=neutral, PublicKeyToken=dd16e486d84ba54f'
or one of its dependencies. The system cannot find the file specified
At line:1 char:1
    Register-MFASystem
        CategoryInfo : OperationStopped: (MFA.RegisterMFASystem:RegisterMFASystem) [Register-MFASystem], Cmdlet InvocationException
        FullyQualifiedErrorId : 3012,MFA.RegisterMFASystem
--------------------------------
after debugging code in this method b is null and this this.MyInvocation.BoundParameters["Verbose"] dectionary is null and count=0
why?
------------------------------------------
public PSHost GetHostForVerbose()
        {
            try
            {
                var b = this.MyInvocation.BoundParameters["Verbose"];
                SwitchParameter verb = (SwitchParameter)b;
                if (verb.IsPresent)
                    return this.Host;
                else
                    return null;
            }
            catch
            {
                return null;
            }
        }
-----------------------------------------------------------------

would you help me?

**Comment by redhook62** [comment]
Binary signatures must be made with a **.pfx** file in **SHA256**, as Visual Studio automatically generates.
