### ISSUE TITLE
Error: The referenced component 'Microsoft.IdentityServer.Aad.Sas' could not be found

### ISSUE THREAD

**Issue by alaamh** [neos-sdi/adfsmfa#283]
I'm getting the below error, Kindly advise what is missing to install it, thanks.

```
Severity	Code Description Project File Line	Suppression State
Error CS0234	The type or namespace name 'Aad' does not exist in the namespace 'Microsoft.IdentityServer' 
(are you missing an assembly reference?) Neos.IdentityServer.MultiFactor.SAS.Azure
\Neos.IdentityServer3.1\Neos.IdentityServer.MultiFactor.SAS.Azure\Neos.IdentityServer.MultiFactor.SAS.Aad.cs
```

**Comment by redhook62** [comment]
All this is normal, these features are only supported by ADFS 2019 and 2022.
It looks like you are in ADFS 2012r2.
The interface having been changed by Microsoft since ADFS 2019, these APIs are only compatible with these versions.
Build a lab with ADFS 2019 or higher
