### ISSUE TITLE
Missing servers in GUI

### ISSUE THREAD

**Issue by Drakeii** [neos-sdi/adfsmfa#289]
Hi,

We have an issue with the GUI - Service Status

We have created two new ADFS servers and added them to the existing ADFS farm. 
They are running ADFS 2019, according to the handbook this would not require a manual registration of the new computers. However, the devices did not show up automatically in the MFA Configuration, hence we run the command manually on the primary server:
`Register-MFAComputer -ServerName "servername_to_add" -NoRSAKeyReset`

As for the FW rules, these are also covered, according to Wiki. 

If we run `(Get-MFAFarmInformation).Servers` all servers from the farm show up - so far so good. 

However, on the primary server, the GUI does not show the two new servers.

We have the same issue on an old farm we decommissioned, where one of the servers would not show up in the GUI at all.

Is there a way to make the GUI register these servers? 

Thanks

**Comment by redhook62** [comment]
Hi, @Drakeii 

Yes, there is certainly a display problem in the MMC console.
However you must be able to view your servers with the cmdlet **Get-MFAComputers**.

You will have a corrective in the next version

regards

**Comment by Drakeii** [comment]
Hi @redhook62 

Thanks for the quick response.
Yes, the servers are in the returned list from Get-MFAComputers
Will wait for the next version for the GUI fix

Thanks!
