### ISSUE TITLE
Improve user experience when providing incorrect token

### ISSUE THREAD

**Issue by Ikke** [neos-sdi/adfsmfa#29]
When a user provides an incorrect token, currently the user is required to close their browser session and go to the whole process again, which is not user friendly.

Would it be possible to allow the user to retry providing the code by either letting them go back (with a button) or even show the token field again with a message that the code was incorrect?

If the concern is that it allows someone to brute force the token, you could limit it the amount of tries after which they do have to go through process again.

Thanks, Kevin

**Comment by redhook62** [comment]
Yes, but based on the external lockout parameters of your ADFS farm

**Comment by redhook62** [comment]
Done in version 2.2.0.25
