### ISSUE TITLE
MFA Registration Error

### ISSUE THREAD

**Issue by suhasjadhav29** [neos-sdi/adfsmfa#296]
We are getting below error while MFA Registration.
We have prod and staging mfa, which is working fine, now we are testing for beta adfs server, where new mfa registration gives error.
Error Details : 
For security reasons, we require additional information to verify your account (testameshram@shipco.com)
An error occurred
An error occurred. Contact your administrator for more information.
[Error details](https://beta.adfs.shipco.com/adfs/ls/IdpInitiatedSignOn.aspx#)
Activity ID: 5933b2bf-8a55-4caa-8b00-0080000000ef
Relying party: Localhost Test
Error time: Wed, 10 May 2023 21:03:27 GMT
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36

**Comment by redhook62** [comment]
Hi, @suhasjadhav29 

First of all,

Please look at the Application logs and the ADFS logs (in which your error will be traced)

Please clarify, if this is just for this user or for everyone. 
Also indicate the details of your configuration
With the "it doesn't work", it is diificile to answer you.

regards

**Comment by suhasjadhav29** [comment]
The issue is for everyone. We have checked application and ADFS logs, but not found anything.

**Comment by redhook62** [comment]
Without logs, we cannot help you !

**Comment by suhasjadhav29** [comment]
![ADFS registration error1](https://github.com/neos-sdi/adfsmfa/assets/133166994/f6b7bf14-83d8-41ac-99d6-36669fb8072e)

**Comment by suhasjadhav29** [comment]
We have not found SQL Server Service Broker service in SQL server.

**Comment by redhook62** [comment]
https://github.com/neos-sdi/adfsmfa/issues/266
https://github.com/neos-sdi/adfsmfa/issues/230
https://github.com/neos-sdi/adfsmfa/issues/89

regards

**Comment by suhasjadhav29** [comment]
Hello Redhook,

Thank you for your help.

We need additional support in below ADFS Infra with MFA Configuration.
1) 2 App Servers
2) 1 SQL Database Server
3) 2 Proxy Servers

Please find below snap, what we are trying to achieve.
We have configured the setup as below.
Can you guide us / share documents for MFA configuration.

***@***.***


Thanks & Regards,
Suhas Jadhav
Information Technology - Infrastructure
Shipco Transport
Pune, India
Mobile     : +91 9702008943
E-mail     : ***@***.******@***.***>
Skype      : live:suhasgjadhav
Web site   : www.shipco.com<http://www.shipco.com/>
For IT support related issues, please open a service record from https://helpdesk.shipco.com
Shipco is a member of the WorldWide Alliance (www.wwalliance.com<http://www.wwalliance.com>)

**Comment by redhook62** [comment]
Hi @suhasjadhav29 

Can you confirm that the "Input string was not in correct format" error is resolved? by forcing a pin code?

Then, where are you, what have you configured ?

For your configuration, the different steps are as follows.
- Properly register the plugin
- enter all the basic properties, the type of temples for users, the different providers etc.
- switch to SQL configuration and not ADDS
- Create an MFA database on your SQL server (with the console or in powershell).

Thank you in advance for your return

regards

@redhook62

**Comment by suhasjadhav29** [comment]
Hi Redhook,
My name is Kamlesh and we are seeking your assistance with the below configuration of MFA in our environment. We can also discuss over the financial aspect if you are interested in working with us.


Regards,
Kamlesh Ade

Information Technology - Infrastructure
Shipco Transport
Pune, India
Cell    : +919028406425
E-mail  : ***@***.***
Skype ID: live:adekamlesh
Web site: www.shipco.com

For IT support related issues, please open a service record from https://helpdesk.shipco.com<https://helpdesk.shipco.com/>
Shipco is a member of the World Wide Alliance (www.wwalliance.com)

From: Suhas Jadhav, Shipco Transport, Pune ***@***.***>
Sent: Saturday, June 10, 2023 1:26 AM
To: neos-sdi/adfsmfa ***@***.***>; neos-sdi/adfsmfa ***@***.***>; Mention ***@***.***>
Cc: Mallikarjun Kalsure, Shipco Transport, Pune ***@***.***>; Advait Raut, Shipco Transport, Pune ***@***.***>; Vijay Kumar, Shipco Transport, Pune ***@***.***>; Kamlesh Ade, Shipco Transport, Pune ***@***.***>; Sandeep Chavan, Shipco Transport, Pune ***@***.***>
Subject: RE: [neos-sdi/adfsmfa] MFA Registration Error (Issue #296)

Hello Redhook,

Thank you for your help.

We need additional support in below ADFS Infra with MFA Configuration.
1) 2 App Servers
2) 1 SQL Database Server
3) 2 Proxy Servers

Please find below snap, what we are trying to achieve.
We have configured the setup as below.
Can you guide us / share documents for MFA configuration.

***@***.***


Thanks & Regards,
Suhas Jadhav
Information Technology - Infrastructure
Shipco Transport
Pune, India
Mobile     : +91 9702008943
E-mail     : ***@***.******@***.***>
Skype      : live:suhasgjadhav
Web site   : www.shipco.com<http://www.shipco.com/>
For IT support related issues, please open a service record from https://helpdesk.shipco.com
Shipco is a member of the WorldWide Alliance (www.wwalliance.com<http://www.wwalliance.com>)
