### ISSUE TITLE
MFA registration error

### ISSUE THREAD

**Issue by suhasjadhav29** [neos-sdi/adfsmfa#297]
We are getting below error while new registration in MFA.
For security reasons, we require additional information to verify your account (sujadhav@shipco-it.com)
An error occurred
An error occurred. Contact your administrator for more information.
[Error details](https://adfs.shipco-it.com/adfs/ls/IdpInitiatedSignOn.aspx?client-request-id=9ae6038e-ff9b-41b0-ffcb-0180000000c1#)
Activity ID: 9ae6038e-ff9b-41b0-ffcb-0180000000c1
Relying party: Demo Trust-1
Error time: Fri, 26 May 2023 19:14:05 GMT
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36

**Comment by suhasjadhav29** [comment]
![ADFS registration error1](https://github.com/neos-sdi/adfsmfa/assets/133166994/21f28efd-f44c-4bc5-a2b7-48a316896f40)
Application logs error

**Comment by redhook62** [comment]
Hi @suhasjadhav29 

This is not a component error.
But, it comes from your ADFS configuration only, or your SQL server.
You have still transmitted the context in which this occurs, and especially the adequate logs.
Solve your problem, reinstall a new ADFS, with a correct SQL server or in ADDS mode.
And come back to us when you've done all that.
I remind you that GitHub is a source repository.
If you don't like the packaged solution, modify the sources or build your own.

regards

**Comment by suhasjadhav29** [comment]
Log Name:      Application
Source:        ADFS MFA Service
Date:          5/26/2023 7:23:21 PM
Event ID:      900
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      carbon.shipco-it.com
Description:
AuthenticationProvider:TryEndAuthentication Error : Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: sujadhav@shipco-it.com : Input string was not in a correct format.
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryRegistration(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims) 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="ADFS MFA Service" />
    <EventID Qualifiers="0">900</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-05-26T19:23:21.050216700Z" />
    <EventRecordID>21308</EventRecordID>
    <Channel>Application</Channel>
    <Computer>carbon.shipco-it.com</Computer>
    <Security />
  </System>
  <EventData>
    <Data>AuthenticationProvider:TryEndAuthentication Error : Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: sujadhav@shipco-it.com : Input string was not in a correct format.
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryRegistration(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]&amp; claims)
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]&amp; claims) </Data>
  </EventData>
</Event>

**Comment by redhook62** [comment]
Error with TOTP, TOTP + PIN, EMAIL, BIOMETRICS ???

https://github.com/neos-sdi/adfsmfa/issues/266
https://github.com/neos-sdi/adfsmfa/issues/230
https://github.com/neos-sdi/adfsmfa/issues/89

perhaps, it can help you

regards
