### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by xymsayly** [neos-sdi/adfsmfa#299]
adfsmfa versioin: Build : 3.1.2306.0
Windows Server Version: Windows Server 2019 DataCenter

I have installed and configured adfsmfa 3.1 according to the documentation.
![image](https://github.com/neos-sdi/adfsmfa/assets/34665997/e70a3626-3284-4bf2-a491-873344bbd123)
I have used the MFA TOTP Provider, and all the settings have been configured with the default parameters.
But when I entered the code, it returned the following error：
![image](https://github.com/neos-sdi/adfsmfa/assets/34665997/f8e9bad4-56a1-431b-a521-721affbeec5d)
There are the following error events on the ADFS server：
![image](https://github.com/neos-sdi/adfsmfa/assets/34665997/e8dd9ca4-3d6c-456d-8c5c-f9b4f8164bc6)

Could you please help me with how to resolve this error? Thank you.

**Comment by redhook62** [comment]
Hi @xymsayly 

it looks like you ran a working setup.
however, there is an error while loading the configuration of the plugin, this occurs when it is ADFS which provides this configuration at the start of the plugin.

The error is that the ADFS service account cannot write a cache file to the plugin's config directory. the config.db file is a cached copy of the config used for performance purposes.

Normally, this file must already be present when starting the pluggin, it is first created by the MFA service (mfanotifhub) each time this service is started. ACLs (directory rights) are also set at this time.

you have to :
- Check the presence of the 2 configuration files (cache) config.db and system.db in the directory c:\Program Files\MFA\Config.
- by restarting the mfanotifhub service, you should see the presence of these 2 files. in PowerShell > Restart-Service mfanotihub

- check the ACLs on the C:\Program Files\MFA directory
You should find rights there for:

1. the ADFS service account

2. the ADFS Service

3. local administrators

4. the ADFS management delegate group (if enabled in the ADFS plugin)

- Can you launch the MMC (in administrator mode) ?
- Do you have other entries in the eventlog ?

regards

@redhook62

**Comment by xymsayly** [comment]
Thank you for your assistance. Here are some other error events：

Failed to poll for the Device Registration Service object at CN=Device Registration Services,CN=Device Registration Configuration,CN=Services,CN=Configuration,DC=MyDomainName,DC=com. 

Additional information 
Error Message: The object does not exist.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Device Registration Service" Guid="{0745ecc7-87dd-4e6e-be80-58821fd6bc18}" />
    <EventID>161</EventID>
    <Version>0</Version>
    <Level>3</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8000000000000002</Keywords>
    <TimeCreated SystemTime="2023-06-10T16:48:51.757398300Z" />
    <EventRecordID>189</EventRecordID>
    <Correlation ActivityID="{6ec3e6d0-9d03-4126-bbc4-63a40b338a16}" />
    <Execution ProcessID="10224" ThreadID="8140" />
    <Channel>DRS/Admin</Channel>
    <Computer>MyComputerName</Computer>
    <Security UserID="S-1-5-21-4256139717-2006762568-1258426647-1219" />
  </System>
  <EventData>
    <Data Name="Data1">CN=Device Registration Services,CN=Device Registration Configuration,CN=Services,CN=Configuration,DC=MyDomainName,DC=com</Data>
    <Data Name="Data2">The object does not exist.</Data>
  </EventData>
</Event>

**Comment by xymsayly** [comment]
Thank you for your assistance. Here are some other error events.
![image](https://github.com/neos-sdi/adfsmfa/assets/34665997/99da46c7-5862-4f3c-8c37-49fe3d78b55f)

**Comment by redhook62** [comment]
This event comes from the system, it is up to you to see if you have activated DRS authentication.
There are thousands of Windows errors. 
I'm talking about component errors.

**Comment by xymsayly** [comment]
I didn't see any other error messages. Can I still download previous versions, like 2.4? I didn't seem to encounter this issue with version 2.4 before. Thank you.

**Comment by redhook62** [comment]
The only version available is 3.1.2306.0

regards

**Comment by xymsayly** [comment]
I tried installing version 2.4, but encountered the following error when accessing it:
"ADFS Error details: A stylesheet is not configured in the active theme for the default locale [zh-CN/2052]."

After following the upgrade documentation to upgrade from version 2.4 to version 3.1, I encountered the following error:
![image](https://github.com/neos-sdi/adfsmfa/assets/34665997/e4fddea1-9acc-4773-bab8-0ae25551c829)

I found the following error message in the Windows event：
![image](https://github.com/neos-sdi/adfsmfa/assets/34665997/7a7cdb72-2d45-44f3-b360-4c932b066af0)

Please help me see if there is a solution to this error.Thank you very much.

**Comment by redhook62** [comment]
Hi,

Well, it doesn't matter, you never answer the questions I ask you.
You can see that the concern is on your infrastructure. it's still not an error that comes from the component, make filters in the event viewer. 
as for the error accessing the config folder, what do you want me to tell you? give rights, search in the Wiki, in the history of the issues. You are far from being the only one to use this component (hundreds, and several tens of thousands for 5 years).
I cannot help you.

regards
