### ISSUE TITLE
email regular expression is not suitable.

### ISSUE THREAD

**Issue by unchannam** [neos-sdi/adfsmfa#3]
like the following figure, if I input xxxxx@adfsuat.local, it will say "Email not correctly formatted" and not allow me to save. 
You can reference the suitable email regular expression format in here: http://emailregex.com/

thanks. 

![image](https://user-images.githubusercontent.com/14857241/34377394-ceb54536-eb2b-11e7-99a1-ed2733576d94.png)

**Comment by redhook62** [comment]
Yes,

Extension is limited in javascript to 3 characters, we will ship an update quickly to remove this limitation.
Remember that the email address must a personal email (aka : gmail.com, live.com, etc...), this email must not be suitable with MFA access.  
Regex has to be changed 
From : **^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$**
To : **^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,})+$**

Thanks

**Comment by redhook62** [comment]
Release 2.0.2.963
