### ISSUE TITLE
Self-registration for MFA was denied.

### ISSUE THREAD

**Issue by xymsayly** [neos-sdi/adfsmfa#300]
When attempting to register MFA using the self-service method, a denial prompt was received. 
The following are the relevant events found in the Windows Event log:
![image](https://github.com/neos-sdi/adfsmfa/assets/34665997/c0760200-8a71-4906-8380-dc735e167c6b)
How should I adjust the configuration to resolve this error? Thank you.

**Comment by redhook62** [comment]
Hi,

We are not going to play like this and open issues every time you have the slightest problem.

- It is required that you send us the Logs of the component and not those of ADFS. The requested logs are in the "Application" eventlog with the following event sources:

- ADFS MFA Administration
- ADFS MFA DataServices
- ADFS MFA MMC
- ADFS MFA Notification Hub
- ADFS MFA Service

And Incidentally the ADFS Logs related to these entries.

On the other hand you have denied access, previously on the directories and now on access to your ADDS.
In this ADFS error: "access denied" it is found that your ADFS service account does not have write rights on the attributes of users in your domain.

Please refer to the Wiki: [Wiki](https://github.com/neos-sdi/adfsmfa/wiki)
And especially to the installation part: [Installation](https://github.com/neos-sdi/adfsmfa/wiki/01-Installation) to validate all the prerequisites without exception.

If your service account does not have the required rights, you must use the "Super Account": ADDS Data Access User" who must have these prerogatives, this is indicated in the installation section.
You can manage cla in PowerShell or with MMC: [Security](https://github.com/neos-sdi/adfsmfa/wiki/07-Security#managing-mfa-security-with-mmc).

I am not one of your service providers ! 
if the component does not please then do not use it, find another solution. 
Read carefully the clauses of the MIT license...

You must comply with the Wiki and be able to perform these tasks.
I hope that this time, that this issue will go to the end and that you will comply with the prerequisites.

regards

**Comment by xymsayly** [comment]
thank you
