### ISSUE TITLE
Adfs wap issue

### ISSUE THREAD

**Issue by pdaccache** [neos-sdi/adfsmfa#303]
Dears, please if someone can help me publishing my internal application integrated with adfs saml and mfa using a WAP without exposing the internal application, external url and internal url are different and once published in the wap adfs login page appears and with successful login it redirecfs to the application url which is internal url and fails what should i do to allow access from external using a WAP??

**Comment by redhook62** [comment]
The easiest way, if you do not have DNS in your DMZ, is to indicate the internal sites in the host file of your WAP servers

redhook

**Comment by pdaccache** [comment]
Yes i am doing that from the WAP server, but how to do it from external public users i have a record to point to the WAP but after that internal url's how it will be reached by internet users i mean adfs url and app url.

**Comment by redhook62** [comment]
Just publish your internal application in Wap
A public URL to an internal URL (Remote Acces or PowerShell).
Watch this: https://learn.microsoft.com/en-us/windows-server/remote/remote-access/web-application-proxy/publishing-applications-using-ad-fs-preauthentication.

regards

**Comment by pdaccache** [comment]
Yes but based on the identifier the public url gets redirected to adfs internal url then after successful login it redirects to the app page, the url in the address bar changes to internal urls where these url are not publicaly available the WAP only can reach these urls, this is my issue.

**Comment by redhook62** [comment]
No, regardless of the user the post url must always be the Public url, in this case you must also publish in your internal DNS in a specific zone.
Read this calmly: https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn383650(v=ws.11)

This has nothing to do with MFA, rather look on a dedicated ADFS forum

**Comment by pdaccache** [comment]
I know it has nothing to do in mfa, but i really need help and no clue what to do i need to publish my internal app to the internet, should i change the post url in the relying party trust configured?

**Comment by redhook62** [comment]
**Yes, what will an internal url do in a federation context (published on the internet)???**

Your internal users must have exactly the same url as the external users. and all still in HTTPS

SO
Public Url: https://saml_app.contoso.com in your public DNS contoso.com
Internal Url: https://saml_app.comtoso.com in your local DNS in a main zone contoso.com

Your post URL or redirect https://saml_app.contoso.com and not http

I don't think you had time to read the links I sent you. so start with that

**Comment by redhook62** [comment]
Moreover, you must test from another machine than the WAP server, because in this case you do not go through the reverse-proxy.
Put in your machine's host file the public URL of your application pointing to the WAP server.

**Comment by pdaccache** [comment]
I will try and let you know, honestly the docs are not clear sure i read them, anyway i will test it out thanks a lot really

**Comment by pdaccache** [comment]
The only thing not clear is the relay trust created using an xml file generated from the application, if i change the post url it will continue to work? What abt adfs service name should i change it also to the public url? Or only in the dns zone created?

**Comment by redhook62** [comment]
Yes, apparently nothing is clear to you.
You will first tell us:
the Public URL of your application, the one through which your users coming from the Internet will access it.
Your app's internal URL, probably the one you're currently accessing through
The POST or redirect URL you entered in the ADFS URL.

**Comment by pdaccache** [comment]
The app internal url is currently found as identifier in the relay trust, i should change the post url in this relay trust created and change names in dns zone created?

**Comment by redhook62** [comment]
I'm talking about POST or Redirect URLs and not about identifying it, which has nothing to do with the feeds, it's just an application identifier, it could have been anything like "urn:saml :app:contoso:com", so don't touch the identifier, but as I asked you to send me the URLs (anonymized if you want).
Without it, you're on your own, okay?

**Comment by pdaccache** [comment]
Sure find below:
External url(WAP): analytics.taba.com
Adfs internal: adfs.prodtaba.com
App internal: tableau.prodtaba.com

**Comment by redhook62** [comment]
Please, give me the https or http and the possible ports used if there are any

**Comment by pdaccache** [comment]
All working on https on port 443 with valid certificates, the external url using a wikdcard public certificate and the internal urls using certificates signed by an intetnal CA

**Comment by redhook62** [comment]
So, from what you indicate.
You have 2 public domain names
- taba.com
- prodtaba.com

Or do you only have a public domain name.
- taba.com
and a private/internal domain name
- prodtaba.com

**Comment by pdaccache** [comment]
To note that i am testing from WAP using hosts file and even from my pc using the hosts file to point to the WAP

**Comment by pdaccache** [comment]
1 public domain taba.com and prodtaba is only internal

**Comment by redhook62** [comment]
Ok, you can test with host files.
However, you made a big mistake.
Your ADFS server is intended to be published on the net, yes, it will authenticate external and internal users.

ADFS server urls MUST be https://adfs.taba.com
This DNS name must be in your Public DNS and in a primary zone of your internal DNS.

So in Public DNS (taba.com). or in the host file of your machine.
adfs.taba.com (points to external WAP URL)
analytics.taba.com (points to WAP external URL)

In the Internal DNS in the taba.com Primary Zone
adfs.taba.com (points to the ADFS server directly)
analytics.taba.com (points to WAP external URL)

The WAP proxy server has as DNS (host file of the WAP machine)
adfs.taba.com (points to the ADFS server directly Internal IP)
tableau.prodtaba.com (points directly to the Application server)
 
The WAP Server takes as input
- analytics.taba.com
and rewrite the url
- tableau.prodtaba.com (ip value found in its host file)

An internal user will solve:
- ADFS Server - adfs.taba.com (Internal DNS / Primary Zone)
- Application Server URL - analytic.taba.com / WAP Server (Internal DNS / Primary Zone)

An External user will solve
- ADFS server - adfs.taba.com (DNS Public IP pointing to the WAP server directly or behind a firewall)
- Application Server - analytics.taba.com (DNS Public IP pointing to the WAP server directly or behind a firewall)

Regardless of a user's location the urls will and should be https://adfs.taba.com and https://analytics.taba.com

In your RL, the URLs of POST or redirect must match

If you are testing with host.
You must have 2 of them.

to simulate an internal user
  - ADFS.taba.com -> ADFS Server IP
  - Analytics.taba.com -> WAP server IP

to simulate an external user
  - ADFS.taba.com -> WAP Server IP
  - Analytics.taba.com -> WAP server IP

regards

**Comment by pdaccache** [comment]
I will do exactly what you said and let you know, i really appreciate your help man thanks a lot.

**Comment by pdaccache** [comment]
i have done all the configuration but i still cannot figure out where i need to change the POST url, currently i am able to be presented with ADFS url on adfs.taba.com, once successful login i got redirected to the tableau.prodtaba.com page which is not published

**Comment by pdaccache** [comment]
the application internal url is: tableau.prodtaba.com, and SAML integration is generated using XML files so in ADFS identifier i can see https://tableau.prodtaba.com, once i connect from external i login to ADFS and after successful authentication i got redirected to https://tableau.prodtaba.com. internall it is working properly but from external this url is internal and not resolvable i am still stuck here :(

**Comment by redhook62** [comment]
Hi,

Go to the ADFS console, then select your Relying Party.
Then modify what is needed in the endpoints tab. and it is indeed a public url that is needed.
https://analytics.taba.com/....

On your WAP Proxy, enter a new Application and enter your public and backend URLs
Url = https://analytics.taba.com
Backend Url = https://tableau.prodtaba.com

If you don't know, ask your administrator

**Comment by pdaccache** [comment]
I have already  done that but it is not working

**Comment by redhook62** [comment]
Definitely!

Please send screenshots

**Comment by pdaccache** [comment]
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/f79fcfad-905e-476d-b6a8-916bee0b1def)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/cf48b464-e3a0-4d20-8a22-b824717477e4)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/e60b91b3-b675-4000-850d-9b4d1cf06e61)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/2c1fb0e9-5f9e-42ae-8361-9cc0ee22b01b)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/279524c5-700e-4ad8-85a9-4ecd4935cf06)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/6840a5a7-5096-4009-abe3-8c341b7225b8)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/5123b5ac-d2a7-4f27-aaee-a28927b9e783)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/9c3f5929-fdc1-4c26-b065-fcff39d067c9)
![image](https://github.com/neos-sdi/adfsmfa/assets/58232170/32307454-228a-4a51-81ce-075c64349e2d)

**Comment by pdaccache** [comment]
even internally if i go to analytics.dc.com which points to the internal IP of WAP it wont work but if i go directly to the https://tableau.insighict.net url it works normally only internally from external find above screenshots done from my PC after i added needed IPs and names in hosts file.

**Comment by pdaccache** [comment]
WAP: analytics.dc.com
adfs: adfs.dc.com
tableau: tableau.insighict.net

**Comment by redhook62** [comment]
my answers under the pictures

**Comment by pdaccache** [comment]
Exactly this is what i have done, i guess now the issue is because my certificate is signed by an internal CA it is still failing i should try with a public certificate, but mainly the main point was to change the return url from apllication side, thanks a lot man

**Comment by pdaccache** [comment]
regarding hosts file setup on WAP, u told me why u need 2 IP addresses, isn't 1 IP to reach ADFS server and the other 1 to reach the internal application server?

The WAP hosts file
10.1.204.106 adfs.dc.com
10.1.204.107 analytics.dc.com --> why this one is pointing to itself? it shouldn't point to the internal application server?

The Host file of your PC (external access)
10.1.204.142 adfs.dc.com  --> why from external access the IP of the application server is used? i guess here i need to app the WAP server external IP
10.1.204.142 analytics.dc.com --> why from external access the IP of the application server is used? i guess here i need to app the WAP server external IP

**Comment by redhook62** [comment]
Good, whose act. I don't know anything about your platform...
I gave you enough explanations, especially since this has nothing to do with MFA. Now get on with it! I am not your service provider. that's enough !! take care of yourself
