### ISSUE TITLE
MFA Login is denied - Password expired

### ISSUE THREAD

**Issue by derSchweiger** [neos-sdi/adfsmfa#304]
Hi,

I've a very strange issue and I don't find the root cause for it. Maybe you have a clue how to fix it.

Currently, some users are not able to login to any ADFS party trust protected by MFA, if their password is "too old". For new users, which are accessing the ADFS site the very first time, the Self Service Registration workflow should be initiated. After providing the first factor, they get the following error message:
![image](https://github.com/neos-sdi/adfsmfa/assets/79589007/bfbd3183-735f-491a-b266-cf005a99c590)

The eventlog provides following error:
`AuthenticationProvider:TryEndAuthentication Error : Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: email@contoso.com : 
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryLocking(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims) `
Strangely, after changing their Active Directory passwords the Self Service Registration works without any problems. It's even possible to check the option "Password never expires" for the corresponding user and the login will work.

The problem seems pretty straight forward: there is a domain password group policy in place which expires passwords after a given time. But there is no policy like that enabled. Login to any domain device works without any problems. Even the login to an ADFS party trust (if MFA is not enforced) works seamless. This error occurs only, if the MFA provider is enforced.

**Additional information:**
- The "msDS-UserPasswordExpiryTimeComputed" attribute is set to "9223372036854775807".
- There is a password GPO in place with the following parameters:
![image](https://github.com/neos-sdi/adfsmfa/assets/79589007/a0ccdc80-ba37-4d67-ba2f-d212670a4ed0)
- MFAConfig:
```powershell
PS C:\Users\adm.kschweiger> Get-MFAConfig

AdminContact                      : notify@contoso.com
Issuer                            : Organization
DefaultCountryCode                : de
DefaultProviderMethod             : Code
LimitEnrollmentToDefaultProvider  : False
UserFeatures                      : AllowChangePassword, AllowManageOptions, AllowEnrollment
CustomUpdatePassword              : True
KeepMySelectedOptionOn            : True
ChangeNotificationsOn             : False
AllowPasswordsReset               : False
UseOfUserLanguages                : True
AllowPauseForDays                 : 7
AdvertisingDays                   : {FirstDay : 1; LastDay : 31; OnFire : True}
UiKind                            : Default
UseUIPaginated                    : False
PrimaryAuhenticationOptions       : None
AdapterPresentationImplementation :
ForcedLanguage                    :
``` 

Is there any mechanism in place which scans "old" passwords? I haven't found anything regarding this issue in your documentation.

**Comment by redhook62** [comment]
Hi @derSchweiger 

Refer to security management: https://github.com/neos-sdi/adfsmfa/wiki/07-Security
And look at the "Password Policy" section
Get-MFASecurity and Set-MFASecurity.
You can disable this feature if you wish.

regards

**Comment by derSchweiger** [comment]
Great, thank you very much!
