### ISSUE TITLE
MFA Not working on clustered ADFS with MDA

### ISSUE THREAD

**Issue by tomerpinto** [neos-sdi/adfsmfa#310]
Hi!

Node 1 = Primary ADFS / MFA Server
Node 2 = Secondary ADFS / MFA Server

I have an issue that I can't seem to resolve. I have two ADFS servers in a cluster, synchronized, with MFA set up.

The solution works on Node 1, the user is prompted to enter MFA. When I set my connection to Node 2, I am able to login to ADFS, but when the user should be prompted for MFA, we get:

```
An error occurred. Contact your administrator for more inforation
Error details: The user name or password is incorrect.
```

In Node 2 Event Viewer, I can see the following (Events 801, 5000, 5001):
```
Error loading User Registration ! 
System.Exception: The user name or password is incorrect.

   at Neos.IdentityServer.MultiFactor.Data.ADDSDataRepositoryService.GetMFAUser(String upn)
   at Neos.IdentityServer.MultiFactor.RuntimeRepository.GetMFAUser(MFAConfig cfg, String upn)
   at Neos.IdentityServer.MultiFactor.AuthenticationProvider.IsAvailableForUser(Claim identityClaim, IAuthenticationContext context)
```

<img width="814" alt="image" src="https://github.com/neos-sdi/adfsmfa/assets/12476608/a2fb13bb-f9c5-470e-a041-08cc06da8b21">

Firewall is allowing all communication between the nodes, the output of (Get-MFAFarmInformation).Servers:

```
FQDN                      : XXXX-dc1.XXXX.local
BehaviorLevel             : 4
HeartbeatTmeStamp         : 8/27/2023 1:11:00 PM
NodeType                  : PrimaryComputer
CurrentVersion            : 6.3
ProductName               : Windows Server 2022 Datacenter
InstallationType          : Server
CurrentBuild              : 20348
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
MachineName               : XXXX-dc1

FQDN                      : XXXX-dc2.XXXX.local
BehaviorLevel             : 4
HeartbeatTmeStamp         : 9/6/2023 11:58:00 AM
NodeType                  : SecondaryComputer
CurrentVersion            : 6.3
ProductName               : Windows Server 2022 Datacenter
InstallationType          : Server
CurrentBuild              : 20348
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
MachineName               : XXXX-dc2
```

Thank you!

**Comment by redhook62** [comment]
hi @tomerpinto 

Obviously, this component works very well with several ADFS servers, in load-balancing, I don't really understand what you call "clustered".

We have plenty of customers who have your configuration, whether in ADDS mode and especially in SQL mode, very often in "Always On".

On your second server: The user name or password is incorrect. please check the different service accounts you are using, 
Check that your 2 adfs servers are pointing to the same ADDS DC.
Or that these domain controllers are in sync.

It is very clear that errors occur on the second server during requests to ADDS (LDAP).

regards

**Comment by tomerpinto** [comment]
Hi @redhook62 

Thank you for your response

This error ("System.Exception: The user name or password is incorrect") is happening only when the user is required to have MFA. When I set the Access Control Policy in ADFS to "Permit everyone", after authenticating with a username & password - it works perfectly.

The issue seem to only happen with the MFA extension

Can you guide me through what I need to check? Are there any configuration in the MFA extension that related to LDAP?

Thanks!
Tomer.

**Comment by tomerpinto** [comment]
Hi @redhook62 

I'm sure that this set up works, this is why we chose it :) However, I'm having some difficulties that I can't understand so I'm seeking for assistance.

Testing our domain FQDN for port 389 works:
<img width="321" alt="image" src="https://github.com/neos-sdi/adfsmfa/assets/12476608/3b2f0619-74f9-4c11-b5bc-7b2dbccba01f">

Can it be something with the RSA keys not synced up? Encryption? 

Thanks!
Tomer.

**Comment by redhook62** [comment]
Hi @tomerpinto 

Hello, listen, I don't know anything about it.
Why did you install your servers in a "cluster", very clearly you are not in a configuration supported by Microsoft.
Positioning your ADFS servers as well as your proxies with an NLB system is more than sufficient.
Then if you want to secure your environment, I sincerely advise you to switch to SQL mode, and if you can to switch to synchronous high availability "Always On".
Re-check your ADFS configuration or open a Ticket with Microsoft. certainly MS will offer you its own MFA (in the cloud)

regards
