### ISSUE TITLE
Unable to update e-mail Templates

### ISSUE THREAD

**Issue by leonbooysen** [neos-sdi/adfsmfa#313]
Hi,

I have been trying to make a few changes to the email templates (en), but without any luck, non of the changes that I make seems to take. I am sure there might be something small that I am missing, but some assistance would be appreciated.

this is what I have tried so far.

exported the default LCID templates

- Export-MFAMailTemplates
- this exported the 1033 templates

I then proceeded to change the files in place and made sure the adfs service account has access to the directories.

I then updated 

$c = Get-MFAProvider -ProviderType Email
$c.MailOTP.RemoveTemplate(1033)
$c.MailOTP.AddTemplate(1033, "C:\Program Files\MFA\MailTemplates\1033\MailOTPContent.html", $True)

$c.MailInscription.RemoveTemplate(1033)
$c.MailInscription.AddTemplate(1033, "C:\Program Files\MFA\MailTemplates\1033\MailAdminContent.html", $True)

$c.MailSecureKey.RemoveTemplate(1033)
$c.MailSecureKey.AddTemplate(1033, "C:\Program Files\MFA\MailTemplates\1033\MailKeyContent.html", $True)

$c.MailNotifications.RemoveTemplate(1033)
$c.MailNotifications.AddTemplate(1033, "C:\Program Files\MFA\MailTemplates\1033\MailNotifications.html", $True)

$c.MailOTP.Templates
$c.MailInscription.Templates
$c.MailSecureKey.Templates
$c.MailNotifications.Templates
Set-MFAProvider -ProviderType Email $c

I restarted the mfa notification service
This unfortunately did not work, I then tried copying the file to another directory just incase there's an issue reading the program files directory for some reason, I also added the service account to the administrators group and updated again

$c = Get-MFAProvider -ProviderType Email
$c.MailOTP.RemoveTemplate(1033)
$c.MailOTP.AddTemplate(1033, "C:\ADFS_Backup\mfa\emailTemplate\MailOTPContent.html", $True)

$c.MailInscription.RemoveTemplate(1033)
$c.MailInscription.AddTemplate(1033, "C:\ADFS_Backup\mfa\emailTemplate\MailAdminContent.html", $True)

$c.MailSecureKey.RemoveTemplate(1033)
$c.MailSecureKey.AddTemplate(1033, "C:\ADFS_Backup\mfa\emailTemplate\MailKeyContent.html", $True)

$c.MailNotifications.RemoveTemplate(1033)
$c.MailNotifications.AddTemplate(1033, "C:\ADFS_Backup\mfa\emailTemplate\MailNotifications.html", $True)

$c.MailOTP.Templates
$c.MailInscription.Templates
$c.MailSecureKey.Templates
$c.MailNotifications.Templates
Set-MFAProvider -ProviderType Email $c

restarted the notification servcice, but again the changes that I make to the template does not reflect when the mail is sent.

any assistance would be appreciated

Thanks

**Comment by leonbooysen** [comment]
Hi,

Managed to find the issue, needed to change the gb templates 2057, working now.

**Comment by redhook62** [comment]
Hi,

LCID 2057 "en-gb" is not implemented by ADFS, only 1033 "en-us"
MFA pluggin support LCID 2057.


Please look at [Localization][(url](https://github.com/neos-sdi/adfsmfa/wiki/11-Localization)) in the Wiki
