### ISSUE TITLE
Issue sending email - requires tls 1.2

### ISSUE THREAD

**Issue by mightymouse2045** [neos-sdi/adfsmfa#316]
I am getting errors using AWS smtp servers with an error of AWS no longer supports tls 1.0 and 1.1, update your client to tls 1.2.

Is this configurable at all, or something you will have to update the product to support?

**Comment by redhook62** [comment]
@mightymouse2045 

I invite you to look at the Amazon SMTP servers.

We do not use SSL certificates.

At worst please uncheck Use SSL in the configuration for emails
It is on the server side that there is an SSL certificate

regards

**Comment by mightymouse2045** [comment]
AWS are pushing back saying it is the client - can I ask how email is sent from NEO? Does it use native windows libraries or libraries built into NEO?

Just thinking if this is some registry setting we could change on Windows server 2019 or something along those lines. This was working ok up until they disabled TLS 1.0/1.1. I know windows 2019 has 1.2 support out of the box, but could it be it has 1.0 and 1.1 enabled on the server for example?

**Comment by redhook62** [comment]
Libraries used to send emails have always been an integral part of the .Net Framework
System.Net.Mail SmtpClient.
Well, this is all in the code.

Read the Microsoft documentation in detail: [Framework.Net SmtpClient](https://learn.microsoft.com/fr-fr/dotnet/api/system.net.mail.smtpclient.enablessl?view=netframework-4.8.1)
We don't use anything else.

We have platforms with only TLS1.2 enabled in the server registry, and this does not pose a problem. TLS 1.2 is available on hard 212r2, 2016, 2019 and 2022.
Only TLS 1.3 and possible on Windows Server 2022.

So, yes, check what TLS is enabled on your ADFS server.

**Comment by mightymouse2045** [comment]
Perfect thanks - I'll take it up with AWS directly, I suspect it is an issue their side
