### ISSUE TITLE
MMC Crash

### ISSUE THREAD

**Issue by Dennisschu** [neos-sdi/adfsmfa#320]
hey,

My MCC crashes when I open the security tab

![image](https://github.com/neos-sdi/adfsmfa/assets/6241958/8f09ea04-ad81-4c1a-b205-f85af679bd94)

Error Message:
`  bei Neos.IdentityServer.Console.Controls.SecurityConfigurationRootControl.UpdateControlsLayouts()
   bei Neos.IdentityServer.Console.Controls.SecurityConfigurationRootControl.DoCreateControls()
   bei Neos.IdentityServer.Console.Controls.SecurityConfigurationRootControl.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.ControlCollection.Add(Control value)
   bei Microsoft.ManagementConsole.View.HandleInitializationRequest(IRequestStatus requestStatus)
   bei Microsoft.ManagementConsole.View.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.ViewMessageClient.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.Internal.IMessageClient.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.Executive.RequestStatus.BeginRequest(IMessageClient messageClient, RequestInfo requestInfo)
   bei Microsoft.ManagementConsole.Executive.SnapInRequestOperation.ProcessRequest()
   bei Microsoft.ManagementConsole.Executive.Operation.OnThreadTransfer(SimpleOperationCallback callback)`

**Comment by redhook62** [comment]
Hi @Dennisschu 

We are unable to reproduce your issue.
A little more information would be desirable.
Your ADFS, MFA, Operating System configuration.

What specific operation did you do on the general security parameters ?

The simplest option in your case is certainly to reinstall and reconfigure the plugin.

regards

**Comment by Dennisschu** [comment]
Hey,

I was setting one of the Password Expiration settings (idk which one) after that the mmc crashed it won't open the security tab without crashing.
Windows OS: Windows Server 2016 (installed in german)
ADFS is used to auth user to our Moodle (just Saml)
The mfa plugin is configured to use SQL.
The only allowed 2fa is TOTP.

**Comment by redhook62** [comment]
Hi,

firstly, to check and put things back in place.

In PowerShell
PS C:\Windows\system32> $s = Get-MFASecurity
PS C:\Windows\system32> $s.UsePasswordPolicy = $false
PS C:\Windows\system32> $s.UsePSOPasswordPolicy = $false
PS C:\Windows\system32> $s.LockUserOnPasswordExpiration = $false
PS C:\Windows\system32> Set-MFASecurity $s

Then try to re-access the “Security” tab.
If everything is OK.
To be able to access the password validity settings, the ADFS account or the interactive operator must have the appropriate rights to Active Directory. Or use the “super account”.

regards

**Comment by Dennisschu** [comment]
hey,

I've run the powershell commands and it's still not working.

My Account has the appropriate rights.

**Comment by redhook62** [comment]
Hi,

Sorry, I can't help you.
Look online if you can't find a better solution.

regards
