### ISSUE TITLE
The MFA wizard is skipped.

### ISSUE THREAD

**Issue by kleingeld-de** [neos-sdi/adfsmfa#330]
Hi,
whenever the user wants to register, the MFA wizard is skipped completely and the user is redirected directly to the application/website. No wizard is shown. The next time the user logs in, the second factor (TOTP) will be queried directly.
![image](https://github.com/neos-sdi/adfsmfa/assets/164230901/856b345a-1128-4e9f-8fc9-f418f3056920)
Mouse click on "Aktivieren" => no wizard is shown, redirect to app/website, mmc says: user active

I have tried all templates. Whenever the user tried to self-register, the wizard was skipped.
Any idea what could be causing this?

Window2019 / ADFS 2019 / ADFSMFA 3.1.2402.0

Regards,
Jens

**Comment by redhook62** [comment]
Hi, @kleingeld-de 

I cannot reproduce your problem.
Are you in SQL (recommended) or ADDS mode?

The only way to avoid having MFA is to use and activate the ADFS KMSI, in this case the plugin is not even called by ADFS. Either for registered users who have deactivated MFA for x days, if this is authorized in your configuration.

You can force in the ADFS configuration, forcing the user to reconnect each time.

in any case the wizards are not disabled in view of your screenshot.

regards

**Comment by redhook62** [comment]
Hi, @kleingeld-de 

What's weird is that you don't show the logos of the authentication apps.
Are you using ADFS 2019 in standard mode (UI like 2016) or in paginated mode (UI 2019+) ?

regards

**Comment by kleingeld-de** [comment]
Hi,
i am using ADDS mode. The language for OS, ADFS and ADFSMFA is german (if that's important).
ADFS KMSI is not enabled. I have only one Server, no farm.
Only the TOTP provider is active.
I'll try to describe the problem in detail again:
When the user clicks on "aktivieren" (enroll), I expect a page to come up where they can set up their authenticator (the page with the QR code). But this page doesn't come. Without a chance to register their authenticator, the user is redirected to their app/website. Nevertheless, his status changes from  deactivated to activated so that he has to enter his authentication code the next time he tries to log in. Which unfortunately he can't do.
![grafik](https://github.com/neos-sdi/adfsmfa/assets/164230901/522c398e-9b69-4e31-8659-18a90839271c)

![grafik](https://github.com/neos-sdi/adfsmfa/assets/164230901/c60b8f84-4291-41e1-bd3d-b9c8491d1e18)

**Comment by redhook62** [comment]
Hi @kleingeld-de 

I'm coming back to you and I'm not a soothsayer, I'm very busy at the moment.
If you would like me to be able to identify your concerns, I need a lot more information.

Indeed, there are 4 platforms, at least two storage configurations (SQL, ADDS, Custom), two display modes for ADFS (standard, Paginated), several authentication modes (TOTP, Bio, Mail) and multiple strategies for the MFA (around ten).
all of this represents hundreds of configurations.

I think the easiest way is for you to send me your MFA configuration file with PowerShell: Export-MFASystemConfiguration edit the xml file and remove critical information. and transmit this file in .zip to the address indicated in the source codes.

Regards

**Comment by kleingeld-de** [comment]
Here is my configuration. Nothing secret in it. It's just a test environment.
[kleingeld-de.zip](https://github.com/neos-sdi/adfsmfa/files/14705470/kleingeld-de.zip)

**Comment by redhook62** [comment]
Hi, @kleingeld-de 

Yes, there were some unreported changes to the standard UI. so everything works well on the paginated interface (Username then on another page the UI 2019/2022 creds)
Please test this version, and give me feedback.

[adfsmfa 3.1.2403.0.zip](https://github.com/neos-sdi/adfsmfa/files/14705524/adfsmfa.3.1.2403.0.zip)

regards

**Comment by kleingeld-de** [comment]
Hi,
I have done the following:
- uninstall the old version
- install the new version
- New-AdfsWebTheme -Name MyTheme -SourceName defaultadfs2019
- Set-MFAThemeMode -UIKind Default2019 -Theme MyTheme -Paginated
- reboot
![grafik](https://github.com/neos-sdi/adfsmfa/assets/164230901/ca1e3dc5-cf2e-44ff-957d-e96183b3c9a6)

I still have the same problem

regards

**Comment by redhook62** [comment]
Yes, the key is already registered for the user.
Delete this user with the console, and retry a registration of this user.

**Comment by redhook62** [comment]
Hi @kleingeld-de 

I think now it's OK for you.
I still recommend that you get the latest version online.

regards
