### ISSUE TITLE
Improve enrollment process

### ISSUE THREAD

**Issue by Ikke** [neos-sdi/adfsmfa#34]
Hello,

We notice our users are struggling to get through the enrollment process. Together with #32, we try to streamline this process.

When a new user tries to sign in, they first have to click the '*I do not have the code*' link:
![sign_in_no_code](https://user-images.githubusercontent.com/135698/46144904-aa9e1000-c25e-11e8-970a-9f856e2eda38.png)

Then they will reach the following screen, which has several options:
![enroll_options](https://user-images.githubusercontent.com/135698/46144902-aa057980-c25e-11e8-9cde-19e43c44a98d.png)

We feel that option marked as 1 is confusing in this case, because the user already expressed that they do not have the code. Perhaps this could be hidden when the user does not have a code yet, or came at this page after clicking on that link.

The option marked as 2 could perhaps be replaced by a cancel button, because it would end up at an error message.

By making this form a little simpler, we believe it would be less confusing for end-users.

Thanks in advance, Kevin.

**Comment by redhook62** [comment]
@Ikke 

Ok thank you.
We will integrate this evolution into the next release, which is coming soon

Regards

**Comment by redhook62** [comment]
New Release 2.2.0.39

**Comment by anorstrom** [comment]
Very nice!
