### ISSUE TITLE
Email provider

### ISSUE THREAD

**Issue by razcenergy** [neos-sdi/adfsmfa#340]
hi,
i am getting error when trying to authenticate by mail this is my configuration:

<img width="578" alt="image (1)" src="https://github.com/neos-sdi/adfsmfa/assets/168974629/e599a03e-d254-43ce-97fe-bd5fa77c0a15">

<img width="419" alt="image" src="https://github.com/neos-sdi/adfsmfa/assets/168974629/2d2be0e7-9686-46c4-b13f-6033fb7af46d">

will appreciate every help,
thanks

**Comment by redhook62** [comment]
Hi @razcenergy 

which country for .il ?
Have you tried sending a test email ?

regards

**Comment by razcenergy** [comment]
which country for .il ? yes
Have you tried sending a test email ? yes, from the adfs server its work perfectly, from other PC that have en-IL the error pops up.

LCID 4096 is not supported by ADFS and MFA.
LCID 4096 is your browser language ? my region setting are IL (get-culture => en-IL) on my pc (not on the adfs), when i change it to en its working fine.

is there a way to add IL to be supported?

🙏

**Comment by redhook62** [comment]
Hi, @razcenergy 

Certainly, I don't have the possibility to modify the ADFS languages. and obviously doing it for just the MFA part would make no sense. 
Ask Microsoft to see if they can add EN-IL to supported translations.

For our part, we will make sure to do a fallback in "en" for emails as in the rest of the component elsewhere..

regards

**Comment by redhook62** [comment]
Don't worry I'm on vacation, a new version next week

**Comment by redhook62** [comment]
Hi @razcenergy 

Please find the modified version, which will allow you to send emails in ENGLISH.
Please let us know if this is functional before we release this version.

[adfsmfa 3.1.2405.0.zip](https://github.com/neos-sdi/adfsmfa/files/15276752/adfsmfa.3.1.2405.0.zip)

regards
