### ISSUE TITLE
Security Problem

### ISSUE THREAD

**Issue by helloboy1980** [neos-sdi/adfsmfa#351]
Hi

I have set configuration like the picture below but when users start to enroll, in the first step that MFA shows QR code, if user type the TOTP code incorrect, the user will be created in enable state and he/she will be able to login to MFA without the admin confirmation for enabling him/her. How can I prevent this? I want to enroll my user in disable state in MFA in all possible scenarios.

<img width="477" alt="image" src="https://github.com/user-attachments/assets/cdcbcd7f-d4c6-44dd-a31b-0e1e88d1b93f">
<img width="559" alt="image" src="https://github.com/user-attachments/assets/70a94627-30d4-4057-86d1-ccf623717454">
<img width="186" alt="image" src="https://github.com/user-attachments/assets/e1e87be8-33b7-4548-aaeb-0baa88b6b4bb">

**Comment by redhook62** [comment]
In your case, users provide various information to IT support. They are disabled by default. It is up to the administrators to enable users with the console or in powershell

**Comment by helloboy1980** [comment]
If users scan QR code and try to type incorrect number, the user will be created in enable status in MFA and at the next time that he/she wants to connect to MFA, he/she will be able to connect to MFA without admin approval!

**Comment by redhook62** [comment]
No, this is not a security issue at all, and besides I know what allows you to say that.
Your users have abandoned the registration process in a messy way and have not validated the TOTP which is nevertheless mandatory in your case. Good for them, they will have to go through you to unblock them.
Basically, if all this can really annoy them, it's great...
