### ISSUE TITLE
secondary upn domain invalid mail address

### ISSUE THREAD

**Issue by mastertIT** [neos-sdi/adfsmfa#352]
we receive this error in the mfa plugin when users using a secondary domain try to do the initial registration.

both domains are part of the UPN list in Active directory.
storage uses Active directory MFA Schema.

```

Error details: user@domain.com : user@domain.com : invalid mail address for user : user@domain.com
Node name: b4a0cf60-06e3-4942-88ee-05e867a8acf8
```

the user has an email address configured in ad that matches the upn domain.
both domains are part of the same AD, and both domains are resolveable to the same AD servers.

**Comment by redhook62** [comment]
Hi,

Sorry, although this is not consistent with authentication issues (identifying a user reliably). I can only confirm that having multiple users (in different domains) with one and the same email address is quite possible.

regards
