### ISSUE TITLE
Possible problems with version 3.1.2411.0

### ISSUE THREAD

**Issue by apr-un** [neos-sdi/adfsmfa#360]
Hi @redhook62,

### There are 3 problems in 2411.0 solution (one possible and two real) and one problem in example in wiki.

Long description for problem 1:
I prepared my custom sms implementation based on class NeosSMSProvider from 3.1.2410.0 and found some problems  which are possibly repeated in build 3.1.2411.0. 

I was using System.Text.Json (version 8.0.5 which is first non-vulnerable version) JsonSerializer class to deserialize my data from json in mfa console External Provider parameters and to serialize data to send to sms api. 
This dll has dependency on few other dlls: 
_System.Text.Encoding.Webs >= 8.0.0 
System.Memory >= 4.5.5 
System.Runtime.CompilerServices.Unsafe >= 6.0.0_

But using that configuration caused errors during application initialization - because System.Memory in 4.5.5 has dependency on System.Runtime.CompilerServices.Unsafe >= 4.5.3 and tries to load wrong version of ...Unsafe dll:
```
Could not load file or assembly 'System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

It can be solved in two ways:
_**A)**_ manually add dependentAssembly entry to adfs config file ( C:\Windows\ADFS\Microsoft.IdentityServer.Servicehost.exe.config ) so it uses correct newer version of ...Unsafe dll:
```
      <dependentAssembly>
        <assemblyIdentity name="System.Runtime.CompilerServices.Unsafe" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-6.0.0.0" newVersion="6.0.0.0" />
      </dependentAssembly>
```
**_B)_** upgrade System.Memory in project to version 6.0.1 because it has correct ...Unsafe dll dependency (> 6.0.0)

In newest build 2411.0 I see that You added dependency to System.Text.Json 8.0.5 to other projects:
_Neos.IdentityServer.MultiFactor.NotificationHub.csproj
Neos.IdentityServer.MultiFactor.WebAuthN.Provider
Neos.IdentityServer.MultiFactor.WebAuthN.Core_

In these projects JsonSerializer is not used directly anywhere ( it's present as non used parameter in few functions )
but reference to this version can lead to problem with System.Memory and ...Unsafe version in the future versions of MFA.
It would be best to consolidate useage of dependent packages in entire solution.

### **TL;DR version of problems  :)**

**1)** Fix dependency version of System.Memory to 6.0.1 for System.Text.Json 8.0.5 OR find a way to modify adfs config file from installer

**2)** Neos.IdentityServer.Deployment/CustomAction.config was removed without removing it from project file ( it was added there twice!)

**3)** example to install ExternalProvider in wiki is wrong, it should be like this:
```
$c = Get-MFAProvider -ProviderType External
$c.Enabled = $True # needed this to work :)
$c.TimeOut = 300
$c.IsTwoWay = $True
$c.Company = "contoso corp"
$c.FullQualifiedImplementation = "Neos.IdentityServer.MultiFactor.Samples.QuizProviderSample,Neos.IdentityServer.MultiFactor.Samples, Version=3.0.0.0, Culture=neutral, PublicKeyToken=175aa5ee756d2aa2" # there was improper character ">" at end
$c.Parameters = "My parameters string, value1=1, value2=2" # this string was not closed
Set-MFAProvider -ProviderType External $c
```

**4)** I believe that there is error (leftover blobPayload line of code) in Neos.IdentityServer.MultiFactor.WebAuthN.Core/Metadata/MDSConstrainedMetadataRepository.cs

```
            if (!validateTokenResult.IsValid)
            {
                 throw new Exception("Blob is not valid");
            }
            var blobPayload = ((JsonWebToken)validateTokenResult.SecurityToken).EncodedPayload;
            var blobPayload = ((JwtSecurityToken)validatedToken).Payload.SerializeToJson(); // <--- this overwrite good version of blobpayload
#else
            var blobPayload = Encoding.UTF8.GetString(Base64Url.Decode(jwtParts[1]));
#endif 
```

Please fix problems 2, 3 and 4 and consider fixing problem 1 ( I know it can be time consuming)

**Comment by redhook62** [comment]
Hi 

I understand your concern. but, I'm not going to spend my time managing Microsoft bugs (I already have enough of my own).
Previously, everything worked very well, the reference to Newtonsoft for the json part and I think that everything will still work very well with it.

wanting to follow Microsoft added dozens of packages and DLLs, without any added value for this project at least.

I have been using Microsoft for 40 years, I worked for the MTC for several years with a lot of public presentations and for many clients, 6 times speaker at techdays (the good old days..). 
So it is with full knowledge of the facts that I think I will return to the initial solution with NewtonSoft.

In the meantime, if you have a pull request to provide for the current solution, I am interested. and will do a build taking into 
account your comments.

thank you for your help

**Comment by redhook62** [comment]
For point 4, this is a problem of Microsoft components. The fido alliance jwt is too big (version .Net Framework 4.8).
So, we disable signature verification for the momment. then eventually removal of these poorly maintained components by Microsoft

For point 3, I assure you that it works correctly. However in your example the first parameter is not correct.
this should be ParamName = ParamValue

For point 2, it seems that this does not pose any problem during runtime, the file will be added in the future, otherwise add yours to compile

**Comment by apr-un** [comment]
Ad .4: You don't get error because this code is currently disabled:

![image](https://github.com/user-attachments/assets/9b9f2a61-3e67-431f-864e-ae54d1156b78)

Ad 3. Copied straight from wiki to powershell:
![image](https://github.com/user-attachments/assets/c1179a04-8683-4c6c-8ba9-45581d81295d)

Ad 2. If someone uses MSI installer then yes it works, but if someone maintains own version then missing files are trouble, because we don't know what they should contain

**Comment by apr-un** [comment]
In case someone has problems with recovering contents for CustomAction.config file (which has to be set as BuildAction=Content in file properties in VS):
```
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <startup useLegacyV2RuntimeActivationPolicy="true">
        <!--
          Use supportedRuntime tags to explicitly specify the version(s) of the .NET Framework runtime that
          the custom action should run on. If no versions are specified, the chosen version of the runtime
          will be the "best" match to what Microsoft.Deployment.WindowsInstaller.dll was built against.

          WARNING: leaving the version unspecified is dangerous as it introduces a risk of compatibility
          problems with future versions of the .NET Framework runtime. It is highly recommended that you specify
          only the version(s) of the .NET Framework runtime that you have tested against.

          Note for .NET Framework v3.0 and v3.5, the runtime version is still v2.0.

          In order to enable .NET Framework version 2.0 runtime activation policy, which is to load all assemblies
          by using the latest supported runtime, @useLegacyV2RuntimeActivationPolicy="true".

          For more information, see http://msdn.microsoft.com/en-us/library/bbx34a2h.aspx
        -->
        <supportedRuntime version="v4.0" />
		<supportedRuntime version="v2.0.50727"/>
    </startup>
    <!--
      Add additional configuration settings here. For more information on application config files,
      see http://msdn.microsoft.com/en-us/library/kza1yk3a.aspx
    -->
</configuration>
```

Unfortunetly without this file custom solution cannot be installed :(
