### ISSUE TITLE
Failing Over MFA to Secondary Server

### ISSUE THREAD

**Issue by SamdaniPashaa** [neos-sdi/adfsmfa#361]
Hi

Hope you are doing well.

we have encountered an issue with (MFA Provider) while transferring the ADFS Farm to secondary node.

we have 2 nodes

Node 1: ADFS01 (Primary Computer for ADFS+ Primary Computer for MFA)
Node 2: ADFS02 (Secondary Computer)

So, we had to failover the Primary role to Secondary Node we did as follows

Set-AdfsSyncProperties -Role "PrimaryComputer"  (Executed on ADFS02.domain.com)
Set-AdfsSyncProperties -Role "SecondaryComputer" -PrimaryComputerName "ADFS02.domain.com" (Executed on ADFS01)

So, we were able to transfer the primary role to ADFS02.
and we had to turn off ADFS01 for some maintenance and mean while we were unable to process SSO MFA and unable to access the  MFA console on ADFS02. it throws below error

"must be executed with ADFS administration rights granted". 
though we are able to access the console from ADFS02 only if the ADFS01 is up.

Note: we followed all the steps you provided under installation.

So, my issue is how I can transfer the MFA Farm to ADFS02 as it is still shows ADFS01 as Primary Computer in the snip below after transfer of Primary Role to ADFS02.

Additionally, I tried below to fix but no luck
UnRegister ADFSMFA Authentication Provider (PowerShell)
Register ADFSMFA Authentication Provider (PowerShell)
Activating Product (Again)

![mfafarminfo](https://github.com/user-attachments/assets/9b185d4c-6bd4-491b-8c60-1532c95120aa)

Regards

**Comment by redhook62** [comment]
Hi, @SamdaniPashaa 

I think you have done what is necessary to switch the primary server. although it is not useful for a simple maintenance of a server.
You should not touch the configuration.

But first please restart the MFA service
**restart-service mfanotifhub**
And then make sure that you are part of the authorized users.

regards

**Comment by SamdaniPashaa** [comment]
Hi @redhook62 

Thanks for your response.

I restarted the service and I am part of authorized users.

Actually we are in a situation that we have to destroy the ADFS01 permanently as it resides in a site that we are about to close and transfer all the services to site2.

The above test was performed along with ADDS (Transfer FSMO Roles), Exchange (Transfer DAG) and others. 


Please advice.

Regards

**Comment by SamdaniPashaa** [comment]
Hi @redhook62 

could you advice any workaround for the above situation?



Regards
