### ISSUE TITLE
How to uninstall / deactivate external provider (for example for SMS)

### ISSUE THREAD

**Issue by apr-un** [neos-sdi/adfsmfa#362]
Hi @redhook62 

How should I uninstall previously activated ExternalProvider?

Currently I have installed and activated my own ExternalProvider based on NeosSMSProvider, but after I upgraded MFA to version 2411 it shows in console in MFA Providers view as External Multi-Factor Provider (Plug) with all options disabled.

From debugging I know that in that view console incorrectly recognizes it as NeosPlugProvider (which is builtin and has AllowDisable=false), but in provider view settings it correctly recognize it as my provider. I cannot set it to Enabled=false in powershell due to AllowDisable = false :( 

What should I do to effectively get rid of my ExternalProvider? 

Regards
@apr-un

**Comment by redhook62** [comment]
Well, just put the default values ​​back in PowerShell.
Otherwise, you're a big boy, edit your config and it will be fixed.

regards
