### ISSUE TITLE
Delay in MFA Session

### ISSUE THREAD

**Issue by SamdaniPashaa** [neos-sdi/adfsmfa#364]
Hello @redhook62 

Hope you are doing well
I am here to raise an issue we encountered in our prod env.
The issue is delay/slowness during 2FA Session. After entering the 2FA code there is a delay of at least 20 seconds to load the password form page.

we have 3 nodes
ADFS1
ADFS2
ADFS3

Current version: adfsmfa.3.1.2411.0.msi

Below is the logs

**_Error on Check Remote Service method : adfs3.corp.com => This request operation sent to net.tcp://adfs3.corp.com:5987/ReplayService did not receive a reply within the configured timeout (00:00:15).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client._

Error on Check Remote Service method : adfs1.corp.d360.com => This request operation sent to net.tcp://adfs1.corp.com:5987/ReplayService did not receive a reply within the configured timeout (00:00:15).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client.**

For each session, I see the above event logs on all nodes with a difference in net.tcp://adfs(X).corp.com:5987
So, to mitigate this I re-added the firewall rule below

Set-MFAFirewallRules -ComputersAllowed '10.2.2.13,10.2.2.14,10.2.2.15' and verified that in-bound/out-bound rules are exist on all the nodes. Additionally, I created separate rules to allow remote subnet (10.2.20/24) for all tcp ports on each node. But above work around did not work for me.

Please advice.

**Comment by redhook62** [comment]
Hi,

If the ports are correctly opened, with correct routing (why not in the host files of the machines). it is instantaneous.
So correct your network problems.
The different ADFS Servers must be able to communicate in real time.
Otherwise disable anti-replay

regards

**Comment by SamdaniPashaa** [comment]
@redhook62 thanks for response

The issue has been resolved automatically. I patched all adfs farm nodes and rebooted recently. but could not figure the cause.
BTW, could you guide me how to disable the anti-reply? (incase if the issue re-surfaces)


Regards
