### ISSUE TITLE
Web Page Texts

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#39]
Hi,
There are a few different ways to configure the MFA adapter, which is really nice! Different configurations gives different user experiences. We recognized that sometimes the text on the some pages, during TOTP enrollment for example, does not makes sense because of my configuration.

Would it be possible to enable customization of theses texts? In that way you could tailor it to your needs.

Kind Regards,
Andreas

**Comment by anorstrom** [comment]
Understand that, and support multi-language may be hard with that feature.
Maybe changing the text a little bit would help. Let me think about it, and I'll give you examples and some suggestions on text changes.

**Comment by redhook62** [comment]
Ok

**Comment by anorstrom** [comment]
Created a pull request, #43, with some suggestions.

Example from our environment where we have the settings:
- MFA Status: Mandatory
- User Registration: Administrative
- Options Management: Disabled User Management, Disabled Password Management, Disabled User can select default provider
- TOTP MFA Active - Enrollment Enabled, Disallow my options Enabled.  
- Email MFA Active, Enrollment Disabled

With this config, the page where you click Enroll my authenticator application is not displayed, which is very good!! We like it, simplified user experience! But we also recognized that it is hard for the user to understand the he/she comes into an enrollment process. In the suggestion we added a title to the totp enrollment pages that says Enroll Authenticator App, which helps the user to understand the they are in a process of enrolling an app.  

It was also hard for some users to understand that they should use their mobile device and install the app there, so we tried to clarify that in the text.

We think these changes would fit also when you configure the MFA plugin differently.

Andreas

**Comment by redhook62** [comment]
Thanks, we will look at this next week

Best Regards

**Comment by redhook62** [comment]
Hi,

I totally agree with you
We will implement your proposals in version 2.3.
We looked in detail at the ADFS 2019 code...

We will activate the good graphic chart according to the setting of the themes of ADFS 2019. 
We will also improve UI for the default theme, 
Later we will ship a Custom API with an example for the 2016 and 2012r2 version.

Best Regards
