### ISSUE TITLE
Domain filter on Email enrollment

### ISSUE THREAD

**Issue by kimlee1024** [neos-sdi/adfsmfa#45]
Hi,

Is it possible to add a filter list to block some domain (email suffixes) in the email enrollment process ? The reason to do so is that our Exchange server uses ADFS for authentication, so I want to make sure users are using their personal/external email address instead of my domain's email addresses to receive token, otherwise it may cause a dead loop.

Thanks a lot.

**Comment by redhook62** [comment]
Hi,

Yes, good idea !
Please wait for next release

Regards

**Comment by kimlee1024** [comment]
Thanks so much for your help.

By the way, is it possible to:
1. In MFA providers, disable TOTP MFA and only use email as default provider? 
2. In Global parameters, choose "Mandatory" in MFA status and  "User -Registration made by the user" in User Registration at the same time? 

Thanks again for you development.

**Comment by redhook62** [comment]
Hi

At this time, TOTP provider cannot be disables (we need at least one)
So you can, disable "manage my options", disable TOTP wizard, and disable "User can select default provider".

Regards

**Comment by redhook62** [comment]
Hi, if you want absolutely disable TOTP Provider

```
$p = Get-MFAProvider -ProviderType code
$p.Enabled = $false
Set-MFAProvider -ProviderType code -Data $p
```
Remember, at least one Provider must be active. and it is recommended to have 2 providers availlable
if the first one is not available.
This is why the Provider TOTP must in principle remain active, because it does not need an internet connection

Regards

**Comment by redhook62** [comment]
Email domain exclusion is done in version 2.3.0.7

Regards
