### ISSUE TITLE
Translate 'Racine de la console'

### ISSUE THREAD

**Issue by Ikke** [neos-sdi/adfsmfa#46]
Hello,

When you open the MFA MMC, the root element is called 'Racine de la console'. Would it be possible to get that translated? When you import it as a snapp-in, it's called 'Console Root'.

Thanks, Kevin.

**Comment by redhook62** [comment]
Hi,

The node is not a part of the project. 
You can change it and use new view from this node, and save.
In future releases we are going to provide a MMC file without this node

Regards
