### ISSUE TITLE
Self registration fails, Version 2.2.0.1000

### ISSUE THREAD

**Issue by Snorre33** [neos-sdi/adfsmfa#47]
Hello

Thank you for your great tool!

I am storing the information in ActiveDirectory, activated Registration Wizard and activated TOTP with Enrollment Wizard and tried to setup selfregistration.

Every time the user klicks on "Register a new Key" an error occures.

I already tried different configurations without success, always the same error.

![image](https://user-images.githubusercontent.com/45385886/49462479-6f880200-f7f6-11e8-8b24-d85b1bfa436b.png)

![image](https://user-images.githubusercontent.com/45385886/49462376-3354a180-f7f6-11e8-9178-f1cf9897c5bc.png)

**Comment by redhook62** [comment]
Hi,

On your ADFS server, Can you look in the eventlog (Applications and Services), the errors under the key "ADFS".
Can you detail these errors ?

Regards

**Comment by GuentherRupitzPewag** [comment]
Hello

The problem was in front of the computer, the ADFS serviceuser had only read access to the AD.

For testing i set write access of the ADFS serviceuser, but this is something i do not prefer.
So i tried to configure the login for the domain in "Active Directory Configuration", but without success.
And the login data is for sure ok, also checked this in PowerShell.

![image](https://user-images.githubusercontent.com/45385886/49504099-52e0de00-f879-11e8-9fee-2a07e38db0bd.png)

**Comment by redhook62** [comment]
Hello,

It seems that the account, have no access, or no write access to ADDS.
I agree with you, writing on ADDS, is not recommended and must be reserved for lab testing i think. 
Remember, taht in this case, that the interactive user (MMC, PowerShell), the ADFS Servcie account (Runtime) MUST have read/write access to ADDS. Access is made with LDAP, so you can also watch to Firewall Rules.

You can use SQL Configuration, if you don't want to write on your ADDS.

**Comment by Snorre33** [comment]
Hi

I can guarantee that the credentials (DomainAddress, Account, Password) are correct and that this account has admin rights on the domain.

Maybe i have the wrong schema of typing in?

DomainAddress: domain.local
Account: domain\username

Firewall is deactivated on both ends for testing.
I can not find any error in the standard logfiles.

Günther

**Comment by redhook62** [comment]
Hi,

As i says before, thgis error occurs when you cannot connect to you ADDS Server !
Nothing for momment does involve your ADDS schema or attribute mapping.
You can also verify DNS resolution.

Otherwise, vous pouvez passer en mode SQL.

**Comment by redhook62** [comment]
Some News ?
