### ISSUE TITLE
Possibility to change some of the Error messages

### ISSUE THREAD

**Issue by tcvall86** [neos-sdi/adfsmfa#49]
Hello!

First of all I think this is a great adapter and most of it is really nice. We needed a new and improved on-prem mfa for our federation service and this seems to do the job for us

I have an issue before launching this in the company and that is with some of the texts. I have read issue #39 but maybe I am just missing something. If this has already been answered I apologize.

The main problem is with the error_strings.resx for ErrorAccountAuthorized
"Access allowed ! but your account is not enabled ! it is recommanded that you provide now all required informations or contact your administartors, they will notify you about the activation process"
The text is confusing for the small group that we have tried this on so far. We would like to change it. Is there anyway to change this text without recompiling the whole project? From what I have read so far it seems not.
What we would like for it to say would be something like
"Access to this application requires additional authentication. To initate additional authentication setup press '"Change my options"
Or something similar 

Thanks in advance!

**Comment by redhook62** [comment]
Label changed in version 2.2.0.1003

In next version 2.3, you could have possibilities to change resources text for WebUI

Regards
