### ISSUE TITLE
German Translation

### ISSUE THREAD

**Issue by Snorre33** [neos-sdi/adfsmfa#51]
Hello

It would be nice to have German text in the Webinterface

I can offer you to translate the Text patterns from English to German.

Günther

**Comment by redhook62** [comment]
@Snorre33 

Hello Günther

Yes, great idea.

Of course, we are applicants.
We will integrate German into the languages supported and integrated into the setup.
We will also do our best during the following evolutions to maintain this functionality.

I'm just asking you to wait until this end of week, a version 2.3 will be available for integrating resources files without having to recompile the project, it may be able to help you.

Then, simply put the .resx files in pull-request.

Yes! Yes! :)

Redhook

**Comment by redhook62** [comment]
Done in version 2.3.0.217

Regards
