### ISSUE TITLE
2.3.0.1000: problem with user creation with RSA option

### ISSUE THREAD

**Issue by Snorre33** [neos-sdi/adfsmfa#55]
Hello

I did a clean install of version 2.3.0.1000.
Like with the previos 2.2 version i activated RSA mode and the config saved in ActiveDirectory.
When creating a new user in the MMC i get the following error message.
Creating a user in powershell does not show a error, but the secret key in the attributes is also missing.

When using RNG mode everything is working without problems.

In TOTP config i can see a certificate thumbprint, so the certificate was created, but maybe not correctly?

Günther

Anwendung: mmc.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.NullReferenceException
   bei Neos.IdentityServer.MultiFactor.RSAKeyManager.EncodedKey(String upn)
   bei Neos.IdentityServer.MultiFactor.KeysManager.EncodedKey(String upn)
   bei Neos.IdentityServer.MultiFactor.RuntimeRepository.GetEncodedUserKey(MFAConfig config, String upn)
   bei Neos.IdentityServer.MultiFactor.Administration.ManagementService.GetEncodedUserKey(String upn)
   bei Neos.IdentityServer.Console.MMCService.GetEncodedUserKey(String upn)
   bei Neos.IdentityServer.Console.UserPropertyPage.CanApplyDataChanges(Registration registration)
   bei Neos.IdentityServer.Console.UserPropertyPage.OnApply()
   bei Neos.IdentityServer.Console.UserPropertyPage.OnOK()
   bei Microsoft.ManagementConsole.PropertySheet.ProcessRequestMessage(PropertyPageMessageRequestInfo requestInfo)
   bei Microsoft.ManagementConsole.PropertySheetManager.ProcessRequestMessage(PropertyPageMessageRequestInfo requestInfo, IRequestStatus requestStatus)
   bei Microsoft.ManagementConsole.SnapInBase.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.NamespaceSnapInBase.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.SnapIn.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.Internal.SnapInClient.Microsoft.ManagementConsole.Internal.IMessageClient.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.Internal.IMessageClient.ProcessRequest(Request request)
   bei Microsoft.ManagementConsole.Executive.RequestStatus.BeginRequest(IMessageClient messageClient, RequestInfo requestInfo)
   bei Microsoft.ManagementConsole.Executive.SnapInRequestOperation.ProcessRequest()
   bei Microsoft.ManagementConsole.Executive.Operation.OnThreadTransfer(SimpleOperationCallback callback)

Ausnahmeinformationen: System.Reflection.TargetInvocationException
   bei Microsoft.ManagementConsole.Executive.MmcThreadMessageWindow.OnThreadException(Exception e)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   bei System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   bei System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   bei System.Windows.Forms.Application.Run()
   bei Microsoft.ManagementConsole.Internal.SnapInMessagePumpProxy.Microsoft.ManagementConsole.Internal.ISnapInMessagePumpProxy.Run()
   bei Microsoft.ManagementConsole.Internal.ISnapInMessagePumpProxy.Run()
   bei Microsoft.ManagementConsole.Executive.SnapInThread.OnThreadStart()
   bei System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Threading.ThreadHelper.ThreadStart()

**Comment by redhook62** [comment]
Hello,

Yes, bug confirmed !

We will try to push a new version as quickly as possible

Regards

**Comment by redhook62** [comment]
@Snorre33 

New version available 2.3.0.1001.
An old bug... only in RSA mode

Regards
