### ISSUE TITLE
Login on one ADFS Clustermember does not work

### ISSUE THREAD

**Issue by Snorre33** [neos-sdi/adfsmfa#56]
Hello

We have 2 ADFS server in our cluster. MFA is configured for RSA mode.
On the main server everything works fine, on the backup server i am not able to login with MFA

I always get the message "Invalid identification, please restart your session"

![image](https://user-images.githubusercontent.com/45385886/52065190-48d81480-2576-11e9-8d86-280166bd656f.png)

In Eventviewer i get the following error message: 
Error on authentication process ! 
Invalid decryption certificate !

Is it necessary to copy the certificate from one ADFS server to the other one?
If yes, what should i do?

When executing Register-MFASystem i can see that MFA was inizialized on both machines correctly.

![image](https://user-images.githubusercontent.com/45385886/52064997-fac31100-2575-11e9-9f1d-68a57c1041c0.png)

**Comment by redhook62** [comment]
Yes  ! you MUST install the RSA certificate on all other ADFS Servers
Automatic deployment of the RSA certificate on all servers is removed form 2.0 solution.
Too much problems with this...

Regards
