### ISSUE TITLE
AD attributes in ADDS mode

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#58]
Hi,
A question on the ADDS mode and the attributes being used.
We tried to use another AD attribute for the MailAttribute and the KeyAttribute. We used attributes that are multi-value attributes (for example otherMailbox). That is working perfectly fine with the MFA, as long as we stick to only having one value in the attribute (that we are also fine with).

We would just like to ask if you guys have any concerns using a multi-value attribute in that way?

Kind regards,
Andreas

**Comment by redhook62** [comment]
Hi,

As we know, we are expecting a singlevalued attribute. 
However, in reading I don't think it poses the slightest problem of pointing to a multivalued attribute. 
On the other hand, I think that in writing you will lose all other values.

We will test, if it's is possible to work only with the value "0" of the multivalued attribute for the email.

Regards

**Comment by redhook62** [comment]
Hi,

We have done tests, 
The attributes mluti-valued do not guarantee in any case a storage order, so you are not certain to fall on the desired value.
In this case **ADDS sorts the different values in ascending order**.
See: https://docs.microsoft.com/en-us/windows/desktop/adsi/single-vs--multiple-value-attributes.
We will make changes to use this type of properties, especially to avoid losing information. 
*We cannot guarantee that we always use the same Email or the same phone number*

Best Regards

**Comment by anorstrom** [comment]
Thanks!
If we make sure that we only allow the MFA adapter to use this attribute in our AD, it should be fine then? Then the MFA adapter will store only one value in the attribute.

**Comment by redhook62** [comment]
Hi, 

Yes, if you are storing only one value in the attribute, everything should be OK.

In next version, we allow to store mutiple values in the attribute, but with only one value for MFA (tagged)

Regards

**Comment by anorstrom** [comment]
I saw the support for multi-value AD attribute on Mail and Phone in latest version. Nice, thank you for that!
Would it be possible to support multi-value AD attribute also for the Secret Key?

**Comment by redhook62** [comment]
Hi,

Hi,

No I do not think it will be possible, I explain, TOTP is the safest method, a key unveiled must be regenerated.
Some applications like authy allow to enter the key manually to share it between several devices, so here we stay on a single key.
If you want to transfer a key to several devices, go to the administration console and on the user's properties choose to send the key by email (textual key and QRCode). this will allow you to use the same key on multiple devices.
In the future, concerning biometric authentication, it will be possible to register for example several fingers for a single account. this is planned.

Regards

**Comment by anorstrom** [comment]
Hi,
Thanks, make sense to only have one Secret Key value for TOTP.

We had to use a multi-value AD attribute for the Secret Key for other reasons not related to the MFA adapter itself. That works fine as long as we only have one value (the MFA Secret Key), and we're fine with having only one value in that attribute. 

However, I could see in the latest release (2.3.0.1126) in the MMC that the MFA adapter didn't like that. After upgrade there is a little exclamation mark saying "Invalid ADDS attribute for key!".

Could it be supported to use a multi-value attribute for the key (with only one value stored, or a tagged value)?

Kind regards

**Comment by redhook62** [comment]
Hi,

Yes, it's possible to allow the Key to be stored on multi-value Property. at this time a checking is made and we just allow Multi-values (tagged) on email and phone properties.

On all others, properties, it will not be reasonable and not supported

Regards

**Comment by redhook62** [comment]
Done in 2.3.0.1200

**Comment by anorstrom** [comment]
Thank you so much!
I tested the new version, 2.3.0.1200, with the TOTP key on multi-value, and it now writes mfa: as prefix on that value so that is nice. 

But it seems like there is a bug when reading the key. It is not getting it right when generating the QR code. And also the secret key string when viewed in MMC or emailed is not correct. I MFA enabled two users and I get the same secret key on both users. I'm using SHA-1, RSA and 1024.

Kind regards,
Andreas

**Comment by redhook62** [comment]
Testing !

**Comment by anorstrom** [comment]
Is working in new version.
Super, thanks!
