### ISSUE TITLE
TOTP code can be reused

### ISSUE THREAD

**Issue by user56558** [neos-sdi/adfsmfa#59]
Currently the TOTP code can be used more than once. The code should be invalidated once used.
Previous codes allowed for time sync issues should also be invalidated once the current code has been used to login.

**Comment by redhook62** [comment]
TOTP is generated with a TimeStamp, It's an implementation of the rfc of IETF rfc4226 and rfc6238.

https://tools.ietf.org/html/rfc6238

Regards

**Comment by user56558** [comment]
rfc6238 - 5.2
Note that a prover may send the same OTP inside a given time-step
   window multiple times to a verifier.  The verifier MUST NOT accept
   the second attempt of the OTP after the successful validation has
   been issued for the first OTP, which ensures one-time only use of an
   OTP.

**Comment by redhook62** [comment]
It's a **TOTP** Code, as i said, it's based on TimeStamp and is only valid for 30 seconds. 
The implementation is conform, and compatible with the Google (and GAFA) implementations.
Google do not implement fully the RFC (Hash supported, time).

**Comment by redhook62** [comment]
Done in V 2.4.4720.0010
