### ISSUE TITLE
cannot install adfsmfa 2.0.2.963 msi

### ISSUE THREAD

**Issue by unchannam** [neos-sdi/adfsmfa#6]
It seems the newest release msi cannot be installed, it will be rolled back during the installation.
Attached the install log file and installed Windows roles and feature list.
I can install 2.0 version https://github.com/neos-sdi/adfsmfa/releases/download/2.0.1.112/adfsmfa.msi.zip successfully.

[adfsmfa.log](https://github.com/neos-sdi/adfsmfa/files/1593227/adfsmfa.log)
[features.txt](https://github.com/neos-sdi/adfsmfa/files/1593228/features.txt)

**Comment by redhook62** [comment]
New version 2.02.964 
https://github.com/neos-sdi/adfsmfa/releases
