### ISSUE TITLE
ADFS 4.0 Relying Party Trust empty

### ISSUE THREAD

**Issue by davoli1919** [neos-sdi/adfsmfa#60]
Hi,
I've installed the AD FS 4.0 and the adfsmfa (no error) but in the AD FS console the Relying Party Trusts is empty so when I login in ADFS the TOTP page doesn't show.
I have to put manually a Relay Party Trust  ? What's the data sources ?
If I add https://_fqdn_/FederationMetadata/2007-06/FederationMetadata.xml
I can see the code request but I receive the error:

Error details: MSIS3110: impossibile trovare un oggetto AssertionConsumerService configurato nell'attendibilità del componente 'http://.../adfs/services/trust' che corrisponda ai parametri della richiesta: AssertionConsumerServiceIndex=, AssertionConsumerServiceUrl='', ProtocolBinding=''.
Node name: 1aebf936-5bcc-405f-aa52-a314c342133a
Error time: Fri, 05 Apr 2019 14:48:05 GMT
Cookie: enabled
User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

Can you help me ? What I'm doing wrong ?

Thank you

**Comment by redhook62** [comment]
Hello,

Yes, you must have at least one Relying Party to test login on ADFS.
If not, you can test with "IdpInitiatedsigon" adfs's page. be sure that this feature is enbled.
Please look at this : https://blogs.technet.microsoft.com/rmilne/2017/06/20/how-to-enable-idpinitiatedsignon-page-in-ad-fs-2016/
After, you must be sure that MFA is enabled

Kind Regards
