### ISSUE TITLE
Feature request - Alert user when user information changes

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#61]
Hi,
For security compliance, it would be nice with the following feature.

Alert user when by email when the user's TOTP key, email or phone number is changed from the user Web UI. If it was not changed by the user, they should reset their TOTP key and change back phone/email settings (would need to email to the old email if it was the email that was changed.)  

Maybe also an option to email that warning to the MFA email only or MFA email + AD email (primary smtp).

(Alert should not be needed if the change is done by an admin via the console or the PowerShell module.)

What do you think?

Kind regards

**Comment by redhook62** [comment]
Yes, we can do that.




Wait for version 2.4, with new security encryption features.
Around the 1 may

Regards

**Comment by redhook62** [comment]
Done, in version 2.4.0.0

Regards
