### ISSUE TITLE
Mandatory MFA with user registration

### ISSUE THREAD

**Issue by miked1313** [neos-sdi/adfsmfa#63]
Is there any way to set MFA Status to Mandatory and also allow the user to register/self enroll an authenticator app?  I only have the TOTP Multi-Factor Provider enabled.  With MFA Status set to Optional users can skip enrolling in MFA.

I tried setting MFA to Mandatory w/user reg. set to Administrative and the user enrolled an authenticator app but then failed to sign in.

**Comment by redhook62** [comment]
Hi,

With the different security templates you can define more or less free self-enrollment processes, however users can override. 
For a more closed management you can use the strict mode and the administrative mode for something completely mastered and closed.

The strict mode approaches what you want, however, your administrators will have to validate the registration, the account is created but not active.

To activate a registered user, you can use Enable-MFAUsers or the MMC.
You can also use the import modules (Xml, CSV and ActiveDirectory).

```powershell
Import-MFAUsersADDS -LDAPPath "dc = domain, dc = com"
Import-MFAUsersADDS -LDAPPath "dc = domain, dc = com" -DisableAll -SendMail -NewKey
Import-MFAUsersADDS -LDAPPath "dc = domain, dc = com" -Method Code -ModifiedSince ([DateTime] :: UtcNow.AddHours (-4))
Import-MFAUsersADDS -LDAPPath "dc = domain, dc = com" -Method Code -ModifiedSince ([DateTime] :: UtcNow.AddMinutes (-30))
```

    LitteralPath is required, full file path
    Newkey generation of a new key only if an add-on occurs when a key is always generated
    DisableAll Status of Added users set to disabled.

Last point, I advise you to activate a second mode like email for example, in case the phone is lost or stolen.
