### ISSUE TITLE
Installing MFA MMC on remote RDS server

### ISSUE THREAD

**Issue by miked1313** [neos-sdi/adfsmfa#64]
I tried to install the adfsmfa MSI on a remote RDS server to test out if a Help Desk staff could run the MMC console remotely to manage MFA on the ADFS server.  It appears that this is not supported, error "This machine is not an ADFS Server 2012R2 / 2016!"

I am testing adfsmfa MFA with ADFS 2019 and ADDS user attribute storage.  What is the recommended way for a Help Desk staff to manage MFA for the AD users?  The Help Desk staff does not have administrator permissions to the ADFS servers because it is a large organization and security policies do not permit it.  Thank you.

**Comment by redhook62** [comment]
Yes, PowerSheel cmdlets and MMC can only be used when logged on an ADFS Server (Like Micorosft for ADFS part)
Some cmdlets and MMC actions can only be run on a Primary ADFS Server (Like Microsoft).
In ADFS 2016/2019, you can allow non administrators to manage ADFS features.
See (Get-ADFSProperties).DelegateServiceAdministration, and also Set-ADFSProperties.

If your server is not a part ot the MFA Farm as described in documentation. you must run the cmdlet 
Register-MFAComputer -ServerName servernametoadd
https://github.com/neos-sdi/adfsmfa/wiki/01-Installation

Regards
