### ISSUE TITLE
version 2.4 - Issue with notify user

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#66]
Hi,
Thanks for the new version 2.4. 
We tested it, but didn't get the new feature "Notify users after configuration changes" to work.
When we have that enabled, and the user goes to the "Change my configuration options", change something and click Save we get the message An Error Occurred, and on the server we get this event id 364 in the ADFS event log:

> Exception details: 
> Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationException: user@domain.com : Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
>    at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryRegistration(AuthenticationContext usercontext, IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
>    at Neos.IdentityServer.MultiFactor.AuthenticationProvider.TryEndAuthentication(IAuthenticationContext context, IProofData proofData, HttpListenerRequest request, Claim[]& claims)
>    at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandlerBase.TryEndAuthentication(IAuthenticationContext authContext, IProofData proofData, HttpListenerRequest request, Claim[]& adapterClaims)
>    at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandler.Process(ProtocolContext context)
>    at Microsoft.IdentityServer.Web.Authentication.AuthenticationOptionsHandler.Process(ProtocolContext context)
>    at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

If we disable "Notify users after configuration changes" the Save button works fine.

Kind regards,
Andreas

**Comment by redhook62** [comment]
Hi @anorstrom

Yes, there was a little mistake in ressources templates for english and spanish languages
placeholder {2} instead of {1}.

New Build available.

**Comment by anorstrom** [comment]
Thanks!
Is it possible to also get a new .msi?

**Comment by redhook62** [comment]
why a new msi ?

**Comment by anorstrom** [comment]
I added the updated .resx resources to C:\Program Files\MFA\ResourceSet and that worked fine.
The Notify users feature works nicely. Would it be possible to add one more thing to that feature?

The user gets notified when clicking the Save button. In addition to that, could the use also get notified  when a new TOTP key is generated during authenticator app enrollment (when someone click "Get a new key")? 
(Someone can Cancel out after TOTP enrollment, and then the user is not notified.)

What do you think?

Regards,
Andreas

**Comment by redhook62** [comment]
No need to add ressouces, correction is un the available msi.

Yes, we can move the email message just after generationg a new key, but it seem not the good solution, if the user don't cancel the process, he can receive 2 emails. so we are going to track generation of a new key, an email will be sent even if the user cancel the registration

Best Regards

**Comment by redhook62** [comment]
Done in version 2.4.0.0001

Best Regards

**Comment by anorstrom** [comment]
Thanks, understood. I removed the resource and installed 2.4.0001 and it works nicely.

I understand the point of not spamming the user with emails. But in this case I think I would prefer that, since someone could generate a new MFA key, scan the QR and then just close the browser without the user getting notified.  
Or would i t be possible to send one email directly at the first change and not the subsequent changes in that session?

**Comment by redhook62** [comment]
Ho Yes ! i'have missed this. if the user close the browser.
We will provide a new build 2.4.0.0003, to send immediatly the mail.

Regards

**Comment by anorstrom** [comment]
I just tested with 2.4.0.0003, but I don't get any notifications. Not sure if I messed up my lab environment, but looks like it should work. I tested to re-enroll TOTP and I have:
ChangeNotificationsOn=True

**Comment by redhook62** [comment]
you can download the msi again. another little mistake, and a lack of concentration :)
The notification will be transmitted only during the first modification during a session (TOTP, Mail, Phone and Passord Change)

Regards

**Comment by anorstrom** [comment]
Nice, works good in 2.4.0.004 :)
Thanks!
