### ISSUE TITLE
Customizing email subject

### ISSUE THREAD

**Issue by miked1313** [neos-sdi/adfsmfa#67]
Hello,
  Thank you for the information on how to customize the email notifications (#65).  Are there any plans to allow us to customize the email subject when adding in a custom email templates?  Perhaps this could be allowed to be set in a new value when we're editing the email template config via PowerShell?

For example for the MailSecureKey template we'd prefer to change "Security informations" to something like "{0} MFA Enrollment Required" and for the MailNotifications template something like "{0} Security Code" or "{0} One-time Security Code" where {0} is the Company Name from the email configuration (or {1} in the case of MailNotifications).

**Comment by redhook62** [comment]
Hello,

No, it is not possible at the moment. 
However we will think about putting the "Subject" in the Head part of the HTML file.

Please, wait a few days for a new version.

**Comment by miked1313** [comment]
Being able to set the subject in the HTML file would work great, thank you.  :)

**Comment by redhook62** [comment]
Done in version 2.4.0.0004

Regards

**Comment by miked1313** [comment]
Thank you for the prompt update.  :)  Can we use {0} in the HTML <title></title>?  I tried but in the email it said "{0} MFA Enrollment Required" and I was hoping that {0} would be replaced with the Company Name that is set in the email provider.  {0} was also in the body of the email and it was properly replaced.

**Comment by redhook62** [comment]
Yes, we will implement it

regards
