### ISSUE TITLE
AdvertisingDays (Registration Notifications)

### ISSUE THREAD

**Issue by miked1313** [neos-sdi/adfsmfa#68]
How does AdvertisingDays (Registration Notifications) work and what are the days based off of?  If you are using the Mixed Template with MFA Mandatory and Registration made by user with Registration Notifications set to Start 1 and End 31 what happens after the 31st day?  I shorted the end to 2 and the user is no longer prompted to enroll in MFA, they're allowed to authenticate without seeing an enforced MFA enrollment prompt.

**Comment by redhook62** [comment]
Indeed, Advertising Days should have no impact on the Mixed mode.
In principle this is useful when the mode allows to connect without being registered or active. in order to avoid soliciting the user permanently, while encouraging him to use the MFA.
Regards
