### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#69]
Hi,
We started to test the support of different languages, but we couldn't get it to work. 
French and Spanish is supported by default, is that correct?

I tested to change the language in Google Chrome to French/Spanish. The ADFS user/pwd pages then shows up in French/Spanish, but not the MFA pages (tested with version 2.4.0.0004). The MFA pages is still in English and when I look at the Elements of the web page it says 
`<html lang="en-US">`
 vs. on the ADFS user/pwd pages it says 
`<html lang="fr">`

Is there anything we need to do to enable language support?

Regards,
Andreas

**Comment by redhook62** [comment]
Hello Andreas.

Regarding the support of different languages, I want to assure you that we apply the language that is transmitted to us by ADFS in parameter. adfsmfa is a pluggin that runs completely in the context of Microsoft's standard ADFS pages.

That said, we hoped that the community would offer us translations, which we also committed to integrate into the project. for example a German translation. we had no pull request about it, this is a shame.
Incidentally we have a lot more downloads when we were on codeplex. Git is just a repository of source code ...

When you change language in chrome (or any other browser), the standard ADFS pages remain in the language of your session and not in the language of your browser, this is also the case of adfsmfa pluggin.

You must change the language of your user session (at the operating system level).

### Under windows 10

If you only edit the language in the browser, the standard ADFS pages remain in the language of the session, so Chrome offers to translate this page clumsily.

<img width="644" alt="lng0" src="https://user-images.githubusercontent.com/26826945/57884691-8ca31100-7829-11e9-9972-8faaed4080e2.png">

You must therefore install additional languages for the Windows interface, but continue to keep the same keyboard.

<img width="224" alt="lng1" src="https://user-images.githubusercontent.com/26826945/57884814-da1f7e00-7829-11e9-80d3-c482cd96e781.png">

<img width="960" alt="lng2" src="https://user-images.githubusercontent.com/26826945/57884876-fb806a00-7829-11e9-924d-3dd703de6bc2.png">

### If your session is in English

<img width="377" alt="lng3" src="https://user-images.githubusercontent.com/26826945/57884969-32ef1680-782a-11e9-8747-8936fc635da6.png">

<img width="358" alt="lng4" src="https://user-images.githubusercontent.com/26826945/57884985-3aaebb00-782a-11e9-8bcb-a7c1c7dc4157.png">

### Change your session to Spanish
<img width="960" alt="lng5" src="https://user-images.githubusercontent.com/26826945/57885040-62058800-782a-11e9-9244-a7ff79a3eaae.png">

#### ADFS pages are in Spanish
<img width="384" alt="lng6A" src="https://user-images.githubusercontent.com/26826945/57885188-ac870480-782a-11e9-8e80-fba944742f22.png">

#### adfsmfa pages are also in Spanish
<img width="354" alt="lng6b" src="https://user-images.githubusercontent.com/26826945/57885275-dd673980-782a-11e9-9fd5-b11bd764f141.png">

The mail templates are also dependent on the language of the session.

We hope this can help you !

Best Regards

redhook

**Comment by anorstrom** [comment]
Thanks, make sense.
Yes, that worked when I tested.
