### ISSUE TITLE
Need UI Enhancement for easy access in Mixed mode

### ISSUE THREAD

**Issue by nathanxa** [neos-sdi/adfsmfa#75]
Hi,
the MFA is an awesome tool. but my suggestion is
The current Configuration option to enroll for MFA is somewhat not user-friendly with drop-down menu.  if the flow is as below, it makes simple for end-user registration.

**User OTP Enrollment**

After Sign ADFS with UPN --> Click "Change my Option" -> instead of Configuration menu with drop down directly go to Mobile TOTP enrollment as default and secondary enrollment like email OTP in consecutive option --> then Choose the default authentication method. --> sign in

[MFA.pdf](https://github.com/neos-sdi/adfsmfa/files/3381697/MFA.pdf)

Also, mask the personal email ID at sign-in page.

![image](https://user-images.githubusercontent.com/37096138/61046418-af514080-a3fa-11e9-8410-ee6b232a2f49.png)

please help me out this. thanks in advance.

**Comment by redhook62** [comment]
Hi,

Each user asks us for such modification of the interface, such modification of functionality, etc ...
This solution, among many others focuses on security ... (GAFAM and others).
This remains a source code sharing solution, we thank for recompiling and perhaps implementing your solution.
However, there are wizards you can activate. But if you have an interface modification proposal that can be generic ... you can post a pull request.

**Comment by redhook62** [comment]
Hi, 

Sorry, our return a bit abrupt.
We will study your proposals. 
But it will still be necessary to wait for the month of August to have a new version.

Regards

**Comment by nathanxa** [comment]
thanks for your response. email mask is now recommended in GDPR.

**Comment by asartheen-chaosa** [comment]
I am using visual studio 2019... it showing lot of error how can I bypass this action

**Comment by redhook62** [comment]
I don't really understand your problems !
You want to recompile ?
Be more explicit please.

Regards

**Comment by nathanxa** [comment]
Hi 

I need your help on below errors.


1.  unable to update dll file location of  Neos.IdentityServer.Console.NativeResources under Neos.IdentityServer.MultiFactor.WixSetup


![image](https://user-images.githubusercontent.com/37096138/65042473-84ddaf80-d976-11e9-8b8d-55810f5156ab.png)

2.  what is the content of App.config under  Neos.IdentityServer.MultiFactor.NotificationHub

![image](https://user-images.githubusercontent.com/37096138/65042558-b2c2f400-d976-11e9-9935-955504cc3c3f.png)

3.  i m getting the below error when i built the sms.sample. 

![image](https://user-images.githubusercontent.com/37096138/65042644-e736b000-d976-11e9-85b3-a7550a9c7df3.png)

**Comment by redhook62** [comment]
My comments inline (bold)

Regards

**Comment by redhook62** [comment]
Done in version 2.4.4720.1000

Regards
