### ISSUE TITLE
Contributing?

### ISSUE THREAD

**Issue by fluffypony** [neos-sdi/adfsmfa#76]
Since there’s no ```CONTRIBUTING``` file / guide, only a handful of minor PRs that have been merged, and almost no issues, I’d like to try and establish if you accept outside contributions or if this is just an upstream repo you push to internally? If we want to add features relevant to our organisation would you prefer we just maintain our own fork and rebase off your work, or would it be possible to contribute relevant features upstream?

**Comment by redhook62** [comment]
Hi,

Of course you can contribute if you wish, it is still the main interest of GitHub.
We will be able to discuss this again in early August.
I am currently on leave with limited internet access.

Regards
