### ISSUE TITLE
QR code not valid with any of the OTP apps

### ISSUE THREAD

**Issue by Pietro1982** [neos-sdi/adfsmfa#77]
Hi, 

when i try to read the QR code for a new user i always get the error "Invalid QR code".
Tested with Android and iOS, same issue. Tested with Google authenticator, MS authenticator, Authy and other free OTP apps, same issue.
If i use the code received by email, i can safely login.
I'm using SQL as DB repository

adfsmfa version = 2.4.0.0
Os = Win2016 std

**Comment by redhook62** [comment]
Hi,

This, can happen on IOS, then it is necessary to launch the camera to scan the QRCode.
It is possible to manage the size of the QRCode from 128 to 2048 bits for its display.

With Android, we have never had this kind of trouble. which version is it ?
To change the display size of the QRCode check these properties in the documentation: https://github.com/neos-sdi/adfsmfa/wiki/06A-MFA-TOTP-Provider#managing-mfa-keys-properties

Regards

**Comment by Pietro1982** [comment]
Hi, 

i tried with all key size, no way to make it work. With IOS we used the camera but no luck.
Android version = 9
Google auth = version 5
FYI i'm talking about the QR code generated for  a new user (in the user properties).
Tried with an user imported from AD and with a user created within MFA console.
Sorry, I've installed the last release, it's my first time i use it so i installed from scratch.

Thanks and regards

**Comment by Pietro1982** [comment]
I found an error in the event viewer, i guess it popup when i generate a new key from user properties.

"Crytograpphic Error for user Exception has been thrown by the target of an invocation."

**Comment by Pietro1982** [comment]
Hi @redhook62 , 

i uninstalled and reinstalled using msi file adfsmfa.2.4.4720.0001
When i check on the MFA mmc "About MFA" it's version 2.4.0.0
![MFa version](https://user-images.githubusercontent.com/26363402/61450055-85e26880-a956-11e9-8a31-aeda556863d4.jpg)

**Comment by redhook62** [comment]
Hi @Pietro1982 

Did this solve your problem? 
Did you have an older version before (2.3.x.x)? if yes please follow the procedure indicated here https://github.com/neos-sdi/adfsmfa/releases
Files versions are 2.4.4720.001, Assemblies Versions are 2.4.0.0
Version 2.4.4720.0001 is the latest version 2.4. (as described in releases)

For information
2 -> Major version (big evolutions)
4 -> Minor version (adding important features)
4720 -> Build Framework Version .net (4.7.2)
0001 -> Build version (bug fixes) / +1000 when adding features

Regards

**Comment by Pietro1982** [comment]
Hi @redhook62 , 

no i was not able to fix the issue.
I am in a DEV environment, i will install everything from scratch.

Anyway, thanks for your help

**Comment by redhook62** [comment]
Hi,

If you are using a certificate to encrypt your keys (RSA or CUSTOM), make sure the ADFS account is able to access the private key. this is necessary to encrypt and decrypt.
On the other hand during the generation of a new cetificat (CUSTOM) when requesting a new key, the ADFS account must have the rights.(check to put the account as local admin to test)
