### ISSUE TITLE
getting Default access method though the option is unchecked in mixed template

### ISSUE THREAD

**Issue by nathanxa** [neos-sdi/adfsmfa#78]
Hi

In Mixed mode Template. i have unchecked "User can select default provider ". but still users are getting that option at the time of registration. is there any option to make it TOTP MFA as a default method without admin intervention?. kindly help on the same. thanks in advance.

![image](https://user-images.githubusercontent.com/37096138/61578084-e5837400-ab0e-11e9-84f8-a44a5c105d6f.png)

![image](https://user-images.githubusercontent.com/37096138/61578092-f9c77100-ab0e-11e9-9a8f-a15dad2743f2.png)

**Comment by redhook62** [comment]
Done in 2.4.4720.002

Regards
