### ISSUE TITLE
How  use MFA in ADFS 4.0 (2016)

### ISSUE THREAD

**Issue by Bastien-RB** [neos-sdi/adfsmfa#8]
Hello

I don't have problème with 2012 r2, I check in internal et external the MFA and its ok in the ADFS console
With 2016 is différent, In authentification Method I have checked the Multifactor Authentification Extension But when I try to log the MFA is not required
I dont understand in 2016 how do it

**Comment by redhook62** [comment]
Hello,

In ADFS 2016, MFA configuration has changed for configuring RL.
There's new Access Policies (great improvment !)

* Assign Access Policy to an RL

![accespolicy](https://user-images.githubusercontent.com/26826945/34770616-72c1dc70-f5f9-11e7-9a7a-e35d1ac19491.png)

* Manage Access Policies

![accespolicygroup](https://user-images.githubusercontent.com/26826945/34770617-72f0dc28-f5f9-11e7-937a-9f9b4b04815c.png)

Regards

**Comment by Bastien-RB** [comment]
thx
