### ISSUE TITLE
Email not correctly formatted on Configuration Options

### ISSUE THREAD

**Issue by kimlee1024** [neos-sdi/adfsmfa#82]
Hi, 

I have encountered an error in the "Configuration Options" page
.
I have enabled TOTP and Email Multi-Factor Provider and I have no problem registering / verifying both the TOTP/Email.

However, if the "configuration options" is set to "Personal email address" and try to click the "Save" button, it always return "Email not correctly formatted".

Screen Capture:
![MFA_EmailEnrollment_Error](https://user-images.githubusercontent.com/45556358/63292966-21336a00-c284-11e9-94a2-1cbc91e8c001.jpg)

The only way I can by-pass this error is to choose "Authentication Application" instead.

I wonder if there is some issue on the email format checking issue on the configuration options.

Thanks,
Kim

**Comment by redhook62** [comment]
@kimlee1024 

Yes, it was a bug, now emails and phone numbers are never displayed.
Correction done in version **2.4.4720.0005**

Thank you for your help
