### ISSUE TITLE
Localization feature problem for non-English browsers

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#85]
Hi,
We've upgraded to version 2.4.4720.0005 and ran into a problem with the localization feature https://github.com/neos-sdi/adfsmfa/wiki/09-Localization. We also upgraded to 2.4.4720.0011 and it has the same problem.

The localization works good with the default browser/OS language set to English. When we have another language set we get different results. (We only have English resource files for the localization, so other languages should default back to the English resource files.)

It sometimes works, and it defaults back to the English customized text we have. But sometimes it does not, and the browser then ends up in a loop after typing username and password not moving forward to the MFA "Enter Code" page. 

It seems like this happens when the browser sets the html language attribute to something that is not in this list https://github.com/neos-sdi/adfsmfa/commit/f3bd6c5246bcd5c78dcc1f0c2632fb56de905822
For example, my Google Chrome sets `lang=sv`, and then the MFA works, while my Edge browser sets `lang=sv-SE` and then I end up in the loop and are not prompted for MFA. We also got the same problem in Google Chrome when the browser sets  `lang=nl-NL`.

When this problem occur we get this error log in the ADFS event log.

> Encountered error during federation passive request. 
> 
> Additional Data 
> 
> Protocol Name: 
> Saml 
> 
> Relying Party: 
> rp.domain.com
> 
> Exception details: 
> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture (or the neutral culture) on disk.
> baseName: Neos.IdentityServer.MultiFactor.Resources.STitle  locationInfo: <null>  fileName: Neos.IdentityServer.MultiFactor.Resources.STitle.resources
>    at System.Resources.FileBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
>    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
>    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
>    at Neos.IdentityServer.MultiFactor.ResourcesLocale.GetString(ResourcesLocaleKind kind, String name)
>    at Neos.IdentityServer.MultiFactor.BasePresentation.GetPageTitle(Int32 lcid)
>    at Neos.IdentityServer.MultiFactor.AdapterPresentation.GetPageTitle(Int32 lcid)
>    at Microsoft.IdentityServer.Web.UI.CustomAuthenticationPage.get_PageTitle()
>    at Microsoft.IdentityServer.Web.UI.PageBase.ApplyTheme(String template)
>    at Microsoft.IdentityServer.Web.UI.PageBase.GetPageHtml()
>    at Microsoft.IdentityServer.Web.UI.PageBase.Render()
>    at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandler.Process(ProtocolContext context)
>    at Microsoft.IdentityServer.Web.Authentication.AuthenticationOptionsHandler.Process(ProtocolContext context)
>    at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

When we remove the customized localize resource files the default text works from any html language attribute.

Could this be a bug?

Kind regards,
Andreas

**Comment by redhook62** [comment]
Hi,

as you can see, the language "sv-se" is not supported by ADFS out of the box only "sv" language is supported.
So, in the code, in first we try to find a 4 digits aka "sv-se" localization files, this it wrong, your files must be localized as "sv" files

You can rename al your "sv-se" files to "sv" files.

I don't think ist's a bug, but an unsupported ADFS feature.

**Comment by anorstrom** [comment]
HI,
We don't have resource files for `sv` only for `en`.
But on the ADFS 2016 the username and password page I for example get `sv-SE`. So in this case it should default back to English.

**Comment by redhook62** [comment]
Hi,
Yes i agree with that !

I will test that situation.
Is it in the MFA pages or on ADFS pages ?

Regards

**Comment by anorstrom** [comment]
In the Adfs page I get se-Sv. 
I never come to the MFA page, because some kind of hanging loop starts after pwd.

This in on Swedish Windows 10 and Edge. On the same computer I get sv in Chrome. 

On a Dutch iPhone a user got nl-NL, and that also didn't work.

**Comment by redhook62** [comment]
Hi,

No, as i can know, ADFS does not have "se-sv" pages (in ADFS 2016, on ADFS 2019 is seems that you must add additional languages).

Does your nl-NL have the save problems with his workstation (W10 or W7) ??

Regards

**Comment by anorstrom** [comment]
Yes, nl-NL have the same problem on Win 10. It did nl-NL both in Chrome and Edge.

**Comment by redhook62** [comment]
Please EdgeHTML or Edge Chromium ?

**Comment by redhook62** [comment]
I'am facing the same problem with latest version of Edge chromium.
I have to reset all settings

**Comment by anorstrom** [comment]
Edge html

**Comment by redhook62** [comment]
I have tested with **nl** as default language for Edge Chromium, Chrome, Firefox and IE...

at startup Edge Chromium and Chrome did not work and caused the same concerns as you. FireFox and IE were working properly.

Disconnecting the network, then passing through 4G, then the local network, all went back to work. I said that I kept the AZERTY keyboard.

Small peculiarity, with Edge Chromium fallback is in French (OS language) while for Chrome it is English ???

I do not really see, but suspect Chromium dysfunction.
By debugging the code, I did not notice anything weird, except for the need to reset Edge Chromium (beta developper)

Wait and see tomorrow

Regards

**Comment by anorstrom** [comment]
Thank for your help and testing!
We've had users reporting it from Germany too, with German OS/Browser.
And I can see in ADFS logs that other countries have the problem too.
We have had several iPhone users in Netherlands with Dutch language that reported the problem.

We've tried restarting services, but can also try reboot ADFS servers tomorrow.

Is there anything that could be done in the code to address these situations do you think?

**Comment by redhook62** [comment]
Hi,

The only things changed since previous version are Italian Ressources.
Perhaps...
I will check ressources in detail tomorrow.

Very strange behavoir today.
Resources resolution code has not been changed

Regards

**Comment by anorstrom** [comment]
Hi,
-No other errors in the event log.
-Restarted ADFS servers, but that didn't help.
-Remove the specific translations. **Yes, that works**, but then we don't get our customized text.

We only have three English resources files in C:\Program Files\MFA\ResourceSet (we customize some text that way):
-Neos.IdentityServer.MultiFactor.Common.Resources.CSHtml.en.resources
-Neos.IdentityServer.MultiFactor.Resources.SHtml.en.resources
-Neos.IdentityServer.MultiFactor.Resources.STitle.en.resources
I tried only using one of them, and then use them one by one, but they all give the error. 

I'll paste the error again, because I can see that one thing disappeared in the md formatting. Maybe the   `locationInfo: <null>` is helpful?

> Encountered error during federation passive request. 
> 
> Additional Data 
> 
> Protocol Name: 
> Saml 
> 
> Relying Party: 
> rp.domain.com
> 
> Exception details: 
> System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture (or the neutral culture) on disk.
> baseName: Neos.IdentityServer.MultiFactor.Resources.SHtml  locationInfo: null  fileName: Neos.IdentityServer.MultiFactor.Resources.SHtml.resources
>    at System.Resources.FileBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
>    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
>    at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
>    at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
>    at Neos.IdentityServer.MultiFactor.ResourcesLocale.GetString(ResourcesLocaleKind kind, String name)
>    at Neos.IdentityServer.MultiFactor.AdapterPresentation2019.GetFormHtmlIdentification(AuthenticationContext usercontext)
>    at Neos.IdentityServer.MultiFactor.BasePresentation.GetFormHtml(Int32 lcid)
>    at Neos.IdentityServer.MultiFactor.AdapterPresentation.GetFormHtml(Int32 lcid)
>    at Microsoft.IdentityServer.Web.Authentication.External.AdapterPresentationWrapper.GetFormHtml(Int32 lcid)
>    at Microsoft.IdentityServer.Web.UI.CustomAuthenticationPage.get_PageTemplate()
>    at Microsoft.IdentityServer.Web.UI.PageBase.GetPageHtml()
>    at Microsoft.IdentityServer.Web.UI.PageBase.Render()
>    at Microsoft.IdentityServer.Web.Authentication.External.ExternalAuthenticationHandler.Process(ProtocolContext context)
>    at Microsoft.IdentityServer.Web.Authentication.AuthenticationOptionsHandler.Process(ProtocolContext context)
>    at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)

**Comment by redhook62** [comment]
Hi,

I've compared resx sources, everything is ok.

If you want you can send me your custom resx files (via private way).
i will check them

Regards

**Comment by anorstrom** [comment]
Hi,
We tested a little bit more. 

If we copy the English resource files, and then just rename the copy to a language attribute that does not work, **that is then working for that language**.

So we tested with this in this in the C:\Program Files\MFA\ResourceSet floder:
-Neos.IdentityServer.MultiFactor.Common.Resources.CSHtml.en.resources
-Neos.IdentityServer.MultiFactor.Resources.SHtml.en.resources
-Neos.IdentityServer.MultiFactor.Resources.STitle.en.resources
-Neos.IdentityServer.MultiFactor.Common.Resources.CSHtml.nl-NL.resources
-Neos.IdentityServer.MultiFactor.Resources.SHtml.nl-NL.resources
-Neos.IdentityServer.MultiFactor.Resources.STitle.nl-NL.resources

So `en` and `nl-NL` have then exactly the same content. 
**With this configured the MFA page now works on Dutch iPhones etc.**

Could the MFA default back to the `en` files when there is a html language attribute that are not supported, nl-NL?

The error message says `locationInfo: <null>`. Could it be a solution to just default back to English whenever locationInfo is null?

Regards,
Andreas

**Comment by redhook62** [comment]
Hi,

All this seems normal to me, if you provide the right resource file it will be taken into account.
Remember, the internal (compiled) resources languages are (en, fr, es, it)

The resources manager search resources in this order : 
- **Two** Letter language (in case of **nl-NL -> no match**)
- **Four** Letter language (in case of **nl-NL -> no match**)
- search for **en-US** resources file (in this case no file corresponding)
- search for **en** resources file (in this case should match, but for **nl-NL -> error**)
- Finally Search for fallback language compiled resources -> **en**

At first sight, there seems to be an incompatibility between the 4th and 5th cases. the same culture is required ... which seems to cause you a problem when the language is not taken into account (ex nl, nl-NL, de, etc ...)

This problem must exists for a long time (lack of tests ...), or, the permanent patches of the framework are in question.

I also told you that I had different behaviors depending on the different browsers. Chrome falback to english, Edge Chromium falback to French (OS language?), Edge IE and Firefox fallback in english.

Not having the ability to translate all languages, we strongly insist that the translations are transmitted by the users in the form of "Pull Requests". I would not go back to the basics of integrating these resources into compiled mode, which is the standard development.

For your concerns, you can think I leave only one version of your resource files with an extension **"en-US.resources"** in this case the resources will be found in step 3, and normally **the conflict should no longer exists** .

We will seriously consider removing the case 4 (**en**) in future versions, moreover why "**en**" and not "**fr**", "**es**", "**it**" ??? especially if my platform is in french

Can you test with "**en-US**" resources files ?

Stay tuned

Best Regards

**Comment by anorstrom** [comment]
Thanks
