### ISSUE TITLE
Localizing adfsmfa instructions not working

### ISSUE THREAD

**Issue by gishh** [neos-sdi/adfsmfa#86]
Hello,
I don't know if I'm doing anything wrong, but when we try to follow the steps in "Localizing adfsmfa" wiki entry, it doesn't work.
I paste the .resources files in C:\Program Files\MFA\ResourceSet for the spanish version but nothing happens after restarting the service.
It is possible that there's some missing step maybe?

Thanks!

**Comment by redhook62** [comment]
Hello,

As you can see in this code source :https://github.com/neos-sdi/adfsmfa/blob/master/Neos-IdentityServer%202.4/Neos.IdentityServer.MultiFactor/Neos.IdentityServer.Multifactor.ResourcesManager.cs

Iin first we Search In ResourceSet folder for the **full cluture of the client** (4 letters), 
after we search for a **2 letter culture**, 
after we search for **en-us culture**, 
after for **en culture** 
and finally we fallback to the **default .Net localization machanism**.

So, do you fallback to our spanish translation or on english translation ?

At this time for Spanish language ADFS implements **es** and **es-MX**

You can look at issue https://github.com/neos-sdi/adfsmfa/issues/85. Browser or Framework ?
The loading of resources was almost identical in previous versions (eg 2.3)

Does your ressouces files ar well named an compiled with resgen ?
Can you verify your browser configuration for language ?

As written in Wiki, localizing with ressources files is not the recommended way.
You can rebuild the solution with your specific ressources, 
or better
if you think that your translations are quite generic and may be suitable by default for many users, it is better to push a "Pull Request" that we will be happy to quickly integrate into a new build.
Now, this is the only way to ask about Typos and localization problems.

Remember that the localization in Spanish was done quickly with Google Translate, a very average tool...

Let us know

Brest Regards
