### ISSUE TITLE
Unknown mfa provider

### ISSUE THREAD

**Issue by ImpulsoAngular** [neos-sdi/adfsmfa#87]
Hi!

I am currently testing version 2.4.4720.2000 and during the registration process (defined security policy: mixed / MFA providers configured: TOTP and Email) a 3rd authentication factor based on mobile phone appears.
Attached 3 captures where the mentioned is evidenced

![Capture1](https://user-images.githubusercontent.com/56454191/67891212-ec1f7f80-fb30-11e9-9c21-6ad49ea2e0dc.PNG)
![Capture2](https://user-images.githubusercontent.com/56454191/67891214-ecb81600-fb30-11e9-8315-5e4421e049df.PNG)
![Capture3](https://user-images.githubusercontent.com/56454191/67891215-ecb81600-fb30-11e9-93e8-fe4f0223eb96.PNG)

**Comment by redhook62** [comment]
Hi, 

Not sure that it's a bug. The only thing that is nor correct is on your first capture : -> **(*)** must be : **Proporcione un número de teléfono móvil (*)**, we cannot reproduce this.

In your case the External Provider (Phone demo) is Active with flag NotRequired.
If you dont want to use the Phone Provider you must disable it

With **MMC**
MFA\Proveedores de MFA -> SMS Multi-Factor Provider - Activo (unchecked) -> Salvar

With **PowerShell**

> $prov = Get-MFAProvider -ProviderType External
> $prov.Enabled = $false
> Set-MFAProvider -ProviderType External $prov

Does this solve your problem ?
Let us know

Regards

**Comment by ImpulsoAngular** [comment]
Apparently that provider could not be disabled. Below are screenshots of the settings

![Capture4](https://user-images.githubusercontent.com/56454191/67946220-9cd46000-fbbf-11e9-9226-b129b66c0d58.PNG)

![Capture5](https://user-images.githubusercontent.com/56454191/67946226-a067e700-fbbf-11e9-83b8-8f1d7885d83f.PNG)

**Comment by redhook62** [comment]
Hi, 

this is not the phone Provider like in your screens.
It's a "plug", when no provider has been set. 
Has you can see, thye property Enabled is set to False when you get it with PowserShell

So, thanks for the information, we are going to test with this

Regards

**Comment by redhook62** [comment]
Ok, 

Problem confirmed !
Please wait for an update

Regards

**Comment by redhook62** [comment]
Hi, 

New Version 2.4.4720.2001

Regards

Feedback on Spanish translation welcome !
