### ISSUE TITLE
MFA Security info changed Email - Text change proposal

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#90]
Hello,
We got some good suggestions from our native English speaking colleagues, on some text corrections/changes to make it more clear for the end-user. We would like to propose changing the text, in the email informing users that security information was changed.

Current Email:
> **Your security information has been changed**
> 
> user@domain.com, it is you who are responsible for these changes ?
> 
> We will notify you when your security information will be changed.
> If you have not asked for these changes, please contact your administrators or reset your informations.
> 
> Best Regards,
> Domain Accounts Team

We suggest to change the Email to:
> **You requested changes to your security information**
> 
> We received a request to change security information for your user@domain.com account. If you did not request any changes, contact your help desk for assistance or reset your security information.
>
> Best Regards,
> Domain Accounts Team

What do you think?

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Hi,

Ok, but for the next release.

Otherwsie, it's possible to customize email as Html Files and register them

Regards

**Comment by redhook62** [comment]
Done in version 2.4.4720.3002 only for english
