### ISSUE TITLE
MFA Email Code - Text change proposal

### ISSUE THREAD

**Issue by anorstrom** [neos-sdi/adfsmfa#91]
Hello,
We got some good suggestions from our native English speaking colleagues, on some text corrections/changes to make it more clear for the end-user. We would like to propose changing the text, in the email sending one time code the the users.

Current Email:
> **Security Code**
> 
> Domain account
> 
> Security Code
> 
> Use this security code for Domain account : FS*********@domain.com.
> 
> Security Code : 123456
> 
> If you never ask for any code, you must ignore this e-mail. Another user may have mistakenly entered your email address.
> 
> Best Regards,
> Domain Accounts Team

We suggest to change the Email to:
> **Security Code**
> 
> Domain account
> 
> Security Code
> 
> Use this security code for Domain account : FS*********@domain.com.
> 
> Security Code : 123456
> 
> If you did not request a code, you may ignore this message.
> 
> Best Regards,
> Domain Accounts Team

What do you think?

Kind Regards,
Andreas

**Comment by redhook62** [comment]
Hi,

is this the modification you want?

If you never ask for any code, you must ignore this e-mail. Another user may have mistakenly entered your email address.
--->
f you did not request a code, you may ignore this message.

No problem, but you will have to wait for a next release

Regards

**Comment by redhook62** [comment]
Done in version 2.4.4720.3002 only for english
