### ISSUE TITLE
Logging Question

### ISSUE THREAD

**Issue by pnwhitmore** [neos-sdi/adfsmfa#92]
Dear Neos-sdi,
I am interested in obtaining ADFS MFA plugin logging information in Windows.  Could you provide the locations and event IDs for this logging data?  Thank you!

**Comment by redhook62** [comment]
Hi,
You can find errors or warnings in standard eventlog, and in specific ADFS evenlog.
Keep, in mind, ist's a preview, if you are using 2.5 version.
We, found some little bugs, and we are going to push a new release soon.
Please wait some days.
We think, taht the final release at the beginning of 2020
 Happy christmas

Regards
