### ISSUE TITLE
Need help on Secure Key Mail template

### ISSUE THREAD

**Issue by kimlee1024** [neos-sdi/adfsmfa#95]
Hello,

I need some help on making a Secure Key Mail template in html.

According to https://github.com/neos-sdi/adfsmfa/wiki/08C-MFA-Email-Provider#secure-key-mail,
I think I can just add {3} in email content to display the QR code in secure key mail.

However, when I send the email, I receive a numeric code like "0ccc17ff-5465-43cf-9d8f-f23bfbeabcde" instead of graphic QR code.

Do you know what should I do to properly display the QR code in email content?

Thanks a lot.

Best Regards,
Kim

**Comment by redhook62** [comment]
Hi @kimlee1024 

QR code is an image, in your html put something like this

`<img id="qr" src="cid:{3}" />`

Regards

**Comment by kimlee1024** [comment]
Thanks so much. It works well.
