### ISSUE TITLE
Fresh install of version 3: service fails to start

### ISSUE THREAD

**Issue by evanlaar** [neos-sdi/adfsmfa#96]
Hi,

I just tried a fresh install of version 3.0.0.0 in a lab environment.
The msi installs fine, but afterwards register-mfasystem seems to hang.
Also starting the MFA console seems to hang indefinetely.

The ADFS is server 2019, fully patched.

In the windows eventlog I see the following errors:
```
Faulting application name: Neos.IdentityServer.MultiFactor.NotificationHub.exe, version: 3.0.0.0, time stamp: 0x5e879363
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ffe11d113c6
Faulting process id: 0x1114
Faulting application start time: 0x01d60c3ec100b328
Faulting application path: C:\Program Files\MFA\Neos.IdentityServer.MultiFactor.NotificationHub.exe
Faulting module path: unknown
Report Id: e7369936-d87b-47c7-9855-a83afcebfbbc
Faulting package full name: 
Faulting package-relative application ID:
``` 
Followed by
```
Application: Neos.IdentityServer.MultiFactor.NotificationHub.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Neos.IdentityServer.MultiFactor.NotificationHub.CleanUpManager..ctor()
   at Neos.IdentityServer.MultiFactor.NotificationHub.MFANOTIFHUB..ctor()
   at Neos.IdentityServer.MultiFactor.NotificationHub.Program.Main()
```

I then removed version 3, installed the latest 2.5 version, performed register-mfasystem, removed version 2.5 and installed version 3 again.

Now everything seems to work.

Regards

**Comment by redhook62** [comment]
Hi @evanlaar 

Bug confirmed !
The installer no longer creates the "hkey_local_machine\Software\MFA" registry key which causes the service to flatten on startup.
if you experience this problem, the workaround is to create this subkey ("MFA").

A new build soon.

Regards

**Comment by redhook62** [comment]
Done in build 3.0.0.1

Regards

**Comment by evanlaar** [comment]
Thanks !
