### ISSUE TITLE
... (invalid key) ... 

### ISSUE THREAD

**Issue by MrPanNikt** [neos-sdi/adfsmfa#97]
Hi,

My solution configuration
ADFSMFA version 3.0
Domain server 2016
ADFS server 2016
Configuration using ActiveDirectory

ADFS connected to local.ad domain
The local.ad domain has two children domains advance.local.ad and users.local.ad.
Logging in to adfs from any domain is successful.
User from the root local.ad domain can easily perform MFA registration using TOTP, mail, SMS.
A user from a child domain cannot register. an error appears in the field "... (invalid key) ...".
![image](https://user-images.githubusercontent.com/63781655/79439136-c0a42a80-7fd4-11ea-8f12-f2964d36b292.png)

After attempting to login, an error appears: "Your account is not valided! You can try the operation again by selecting" previous "."
![image](https://user-images.githubusercontent.com/63781655/79439183-cbf75600-7fd4-11ea-9e54-ca1a6f9f1c65.png)

I will ask for support if possible. There are no errors in the system logs.
It looks like logging in to the application using the child domain could not connect to it at the MFA level, because the adfs login passes correctly.

**Comment by redhook62** [comment]
Hi @MrPanNikt 

I will re-test this case today, 
But, verify that the account used to access your subdomains have Read/Write access on all parameterized attributes

Regards

**Comment by MrPanNikt** [comment]
Yes, the user on which ADFS works has read / write permissions for the root domain and both child domains

**Comment by redhook62** [comment]
Hi @MrPanNikt 

New release tomorrow.
More testing needed

**Comment by MrPanNikt** [comment]
Thank you very much. After uploading the patch, everything works very well.
