### ISSUE TITLE
Mail template - Danish

### ISSUE THREAD

**Issue by MDaugaardDK** [neos-sdi/adfsmfa#99]
Hello again

I have tried making an danish Localization version, and all seems to work perfekt... until i tried sending an email, which is still english.
I have tried restarting MFA service, ADFS service an no chances.

Is there something im missing? I have attach  my email lozalization version. Just remove .txt ext. 

[CSMail.da.resx.txt](https://github.com/neos-sdi/adfsmfa/files/4514573/CSMail.da.resx.txt)

**Comment by redhook62** [comment]
Hi @MDaugaardDK 

Great news !

For email, all the trick is under email provider.
You must provide a valid html file for each mail. and each file must contains some placeholders.
When your html files are ok, you must deploy them on each adfs server in a directory with read rights for the Adfs account.

And finally, you must register with your LCID (eg : 1030 ?) your templates with PowerShell Cmdlet

**$c = Get-MFAProvider -ProviderType Email**

**$c.MailOTP.AddTemplate(1030, "c:\yourpath\yourotptemplate.html", $True)**
**$c.MailInscription.AddTemplate(1030, "c:\yourpath\yourtinscriptionsemplate.html", $True)**
**$c.MailSecureKey.AddTemplate(1030, "c:\yourpath\yoursecretkeystemplate.html", $True)**
**$c.MailNotifications.AddTemplate(1030, "c:\yourpath\yourNotificationstemplate.html", $True)**

**Set-MFAProvider -ProviderType Email -Data $c**

You can find more details here : https://github.com/neos-sdi/adfsmfa/wiki/08C-MFA-Email-Provider#replacing-default-emails-templates

Regards

**Comment by MDaugaardDK** [comment]
Hmm.... i tried following and my HTML contains the placeholders thats described in the documentation, but still no changes...
My SecureKey is attach to this answer

By the way AWESOME product!!

[TOTPSecureKey.html.txt](https://github.com/neos-sdi/adfsmfa/files/4516320/TOTPSecureKey.html.txt)

**Comment by redhook62** [comment]
Please try to register with LCID 1033 !
Perhaps your LCID is wrong 
Otherwise the HTML seems correct

Regards

**Comment by redhook62** [comment]
The MMC console and PowerShell use the operating system language by default, no particular language context is available. However, it is possible to think in order to be able to force this for a future release.
I don't think the default built-in languages have this problem.

Regards

**Comment by redhook62** [comment]
@MDaugaardDK 

A new build available 3.0.0.3
You can register all your templates with LCID = 6
For the mail Key (administrative) this should work

Regards
